ALTER TABLE CAST_DOCUMENT ADD PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT ADD META_KEYWORDS_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT ADD META_DESCRIPTION_PATTERN	VARCHAR2(300)	NULL;

ALTER TABLE CASTO_MAGASIN ADD STORE_ID VARCHAR2(40) DEFAULT '0';

ALTER TABLE CAST_PROMO_INFORMATION ADD PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT ADD PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;

ALTER TABLE CAST_PRODUCT ADD FLAG_IMAGE	VARCHAR2(100)	NULL;
ALTER TABLE CAST_PRODUCT ADD FLAG_TEXT	VARCHAR2(200)	NULL;

UPDATE CAST_DOCUMENT 
SET PAGE_TITLE_PATTERN = '{title} - CASTORAMA';

UPDATE CAST_DOCUMENT 
SET META_KEYWORDS_PATTERN = '{keywords,sep=,}';
     
UPDATE CAST_DOCUMENT 
SET META_DESCRIPTION_PATTERN = '{description}';

UPDATE CAST_PROMO_INFORMATION 
SET PAGE_TITLE_PATTERN = '{title} - CASTORAMA';

commit;