  CREATE TABLE "THEME" 
   (
	"IDTHEME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(255 BYTE), 
	 CONSTRAINT "PK_THEME" PRIMARY KEY ("IDTHEME")
	);
	
  CREATE TABLE "SOUS_THEME" 
   (	
	"IDSOUSTHEME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"LIBELLESOUSTHEME" VARCHAR2(255 BYTE), 
	"IDTHEME" VARCHAR2(40 BYTE), 
	 CONSTRAINT "PK_SOUS_THEME" PRIMARY KEY ("IDSOUSTHEME")
	);
	
  CREATE TABLE "CASTO_CONTACT" 
   (	
	"IDCONTACT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IDORDER" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"NUMCONTACT" NUMBER(8,0), 
	"NUMDOSSIER" NUMBER(8,0), 
	"CONTENU" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"DATECONTACT" DATE NOT NULL ENABLE, 
	"DATELECTURECLIENT" DATE, 
	"DATEENVOYEBO" DATE, 
	"CMOTIF_C618" NUMBER(4,0) NOT NULL ENABLE, 
	"TYPECONTACT_C632" NUMBER(4,0) NOT NULL ENABLE, 
	"INITIATEURCONTACT_C659" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CASTO_CONTACT_FO" PRIMARY KEY ("IDCONTACT")
	);
	
  CREATE TABLE "QUESTION_REPONSE" 
   (	
	"LIBELLE_QUESTION" VARCHAR2(512 BYTE), 
	"LIBELLE_REPONSE" VARCHAR2(2048 BYTE), 
	"IDSOUSTHEME" VARCHAR2(40 BYTE), 
	"IDQR" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_QUESTION_REPONSE" PRIMARY KEY ("IDQR")
	);
	
  CREATE TABLE "CASTO_CONTACT_STATUS" 
   (	
	"STATUS_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IDCONTACT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IDORDER" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"NUMCONTACT" NUMBER(8,0), 
	"CVENTE" NUMBER(8,0), 
	"DATEREADED" DATE, 
	"DATEREPLIED" DATE, 
	 CONSTRAINT "PK_CASTO_CONTACT_STATUS" PRIMARY KEY ("STATUS_ID")
	);
	
