CREATE TABLE "CASTO_LOGS_ADMIN" 
(	
	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(254 BYTE), 
	"DATECREATION" DATE, 
	"NOMLOGIN" VARCHAR2(50 BYTE), 
	"ADRESSEIP" VARCHAR2(40 BYTE), 
	"ACTION" VARCHAR2(254 BYTE), 
	"COMMENTAIRE" VARCHAR2(4000 BYTE), 
	 PRIMARY KEY ("ID")
);