CREATE TABLE CASTO_ORDER (
  ORDER_ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_ORDER(ORDER_ID),
  ISGIFT NUMBER (1,0) CONSTRAINT ISGIFT_CH CHECK (ISGIFT in (0,1)),
  COMMENTAIRE VARCHAR2 (200),
  EXPORTDATE DATE,
  DATESUPPRESSION DATE,
  AUTEUR VARCHAR2 (150),
  NUMCHEQUE VARCHAR2 (50),
  LIBELLE_BANQUE VARCHAR2 (30),
  MONTANT_CHEQUE_FRANCS NUMBER (12,2),
  MONTANT_CHEQUE_EUROS NUMBER (12,2),
  CHEQUE_NON_VALIDE NUMBER,
  COMMENTAIRE_CHEQUE VARCHAR2 (500),
  NUM_CARTE_ATOUT VARCHAR2 (50),
  DATE_VALID_ATOUT DATE,
  OPTION_PAIEMENT_ATOUT NUMBER,
  MESSAGE_TRANSPORTEUR VARCHAR2 (500),
  BOSTATE VARCHAR2 (40),
  BOSTATE_DETAIL VARCHAR2 (254),
  BOSTATE_NUM NUMBER (2,0),
  PREPARATION_PRICE_INFO VARCHAR2 (40) REFERENCES DCSPP_AMOUNT_INFO(AMOUNT_INFO_ID),
  CVENTE NUMBER (12,0),
  FETAT_INTEGRATION NUMBER (1,0),
  MONTANT_CHEQUE_CADEAU NUMBER (12,2),
  PAIEMENT_CHEQUE_CADEAU NUMBER (1,0),
  ENREG_CCP_PRESENT VARCHAR2 (1),
  COMMENTAIRE_PAIEMENT VARCHAR2 (100),
  ETAGE_LIVRAISON NUMBER,
  NUM_FIC_EXPORT NUMBER (10,0),
  ORIGINE_MAGASIN NUMBER,
  JSESSIONID VARCHAR2 (60),
  MNT_TOTAL_TTC NUMBER (10,2),
  MNT_LIV_NON_REMISE NUMBER (10,2),
  MNT_MONTEE_ETAGE NUMBER (10,2),
  MNT_REMISE_LIV_ETAGE NUMBER (10,2),
  MNT_PREPA_NON_REMISE NUMBER (10,2),
  MNT_FRAIS_PREPA_REMISE NUMBER (10,2),
  MNT_REMISES_COMMANDE NUMBER (10,2),
  CARTE_ATOUT_INDETERMINE NUMBER (1,0),
  MONTANT_PFL NUMBER (12,2),
  MONTANT_PFT NUMBER (12,2),
  COMMANDE_ADMIN NUMBER (1,0),
  LOGIN_ADMIN VARCHAR2 (50),
  CP_ACCEPTEES NUMBER,
  PRIMARY KEY (ORDER_ID)
);

CREATE TABLE CASTO_ORDER_EMAILS (
	ORDER_ID VARCHAR2 (40) NOT NULL REFERENCES CASTO_ORDER(ORDER_ID),
	EMAIL_TYPE VARCHAR2 (50),
	IS_SENT NUMBER (1,0),
	PRIMARY KEY (ORDER_ID, EMAIL_TYPE) 
);

CREATE TABLE CASTO_ORDER_COMMENTAIRE (
  REPOSITORYID VARCHAR2 (50) NOT NULL PRIMARY KEY,
  COMMENTAIRE VARCHAR2 (2000)
);

CREATE TABLE CASTO_TRADEDOUBLER (
  ORDER_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  TDUID VARCHAR2 (32) NOT NULL
);

CREATE TABLE CASTO_CARTE_ATOUT (
  PAYMENT_GROUP_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  ID_TRANSACTION NUMBER (18,0),
  NUM_AUTORISATION VARCHAR2 (20),
  NUM_TRANSACTION NUMBER (18,0),
  DATE_TRANSACTION TIMESTAMP(6),
  DATE_PAIEMENT TIMESTAMP(6),
  DATE_VALID_ATOUT TIMESTAMP(6),
  NUM_CARTE_ATOUT VARCHAR2 (40),
  OPTION_PAIEMENT_ATOUT NUMBER
);

CREATE TABLE CASTO_CARTE_CHEQUE (
  PAYMENT_GROUP_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  NUMCHEQUE VARCHAR2 (50),
  LIBELLE_BANQUE VARCHAR2 (30),
  MONTANT_CHEQUE_FRANCS NUMBER (12,2),
  MONTANT_CHEQUE_EUROS NUMBER (12,2),
  CHEQUE_NON_VALIDE NUMBER,
  COMMENTAIRE_CHEQUE VARCHAR2 (500)
);

CREATE TABLE CASTO_BILL_ADDR (
  PAYMENT_GROUP_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  CIVILITE NUMBER,
  TEL_PORTABLE VARCHAR2 (30),
  TEL_PROFESSIONNEL VARCHAR2 (30),
  ADRESSE_LIBELLE VARCHAR2 (60),
  TVA_INTRACOMUNAUTAIRE VARCHAR2 (13),
  ALERTE_AUTO NUMBER (1,0),
  MOYEN_CONTACT VARCHAR2 (1)
);

CREATE TABLE CASTO_COMMERCE_ITEM (
  COMMERCE_ITEM_ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_ITEM (COMMERCE_ITEM_ID),
  POIDS NUMBER,
  HORS_NORMES NUMBER (1,0),
  EXONERATION_PFE NUMBER (1,0) CONSTRAINT EXONERATION_PFE_CH CHECK (EXONERATION_PFE in (0,1)),
  CADEAU NUMBER (1,0) DEFAULT 0,
  CODEARTICLE VARCHAR2 (40),
  ENVENTE NUMBER (1,0),
  DATEFINVIE DATE,
  COEFFICIENTDESATISFACTION NUMBER (10,2),
  GENERALEMENTLIVREENHEURES NUMBER (4,0),
  SOMME_FORFAITAIRE NUMBER (19,7),
  EXONERATION_PFT NUMBER (1,0),
  CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
  PRIMARY KEY (COMMERCE_ITEM_ID)
);

CREATE TABLE CASTO_HARDGOOD_SHIPPING_GROUP (
  SHIPPING_GROUP_ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_SHIP_GROUP (SHIPPING_GROUP_ID),
  POIDS_TOTAL NUMBER,
  FRAIS_PREPARATION NUMBER (10,2),
  DELAI_ENGAGEMENT NUMBER (5,0),
  LIBELLE_DELAI_ENGAGEMENT VARCHAR2 (50),
  TRANCHE_HORAIRE_CLIENT_MAD VARCHAR2 (75),
  POIDS_PFL NUMBER,
  POIDS_PFT NUMBER,
  PRIMARY KEY (SHIPPING_GROUP_ID)
);

CREATE TABLE CASTO_SHIP_ADDR (
  SHIPPING_GROUP_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  CIVILITE NUMBER,
  TEL_PORTABLE VARCHAR2 (30),
  TEL_PROFESSIONNEL VARCHAR2 (30),
  ADRESSE_LIBELLE VARCHAR2 (60),
  TVA_INTRACOMUNAUTAIRE VARCHAR2 (13),
  ALERTE_AUTO NUMBER (1,0),
  MOYEN_CONTACT VARCHAR2 (1)
);

CREATE TABLE CASTO_PFE_POIDS (
  ID VARCHAR2 (30) NOT NULL PRIMARY KEY,
  POIDS_INF NUMBER NOT NULL,
  POIDS_SUP NUMBER NOT NULL,
  PRIX_AU_KG NUMBER (12,2) NOT NULL,
  FORFAIT_TTC NUMBER (12,2) NOT NULL,
  FORFAIT_HN_TTC NUMBER (12,2) NOT NULL,
  GRILLE_PFE_ID VARCHAR2 (40) DEFAULT '1'
);

CREATE TABLE CASTO_PREPARATION_POIDS (
  ID VARCHAR2 (30) NOT NULL PRIMARY KEY,
  POIDS_INF NUMBER NOT NULL,
  POIDS_SUP NUMBER NOT NULL,
  MONTANT NUMBER (12,2) NOT NULL
);

CREATE TABLE CASTO_CODESPOSTAUX_PFE (
  CODE_POSTAL VARCHAR2 (5) NOT NULL PRIMARY KEY,
  GRILLE_PFE_ID VARCHAR2 (40) NOT NULL,
  POID_MINIMUM NUMBER NOT NULL,
  VOLUME_MINIMUM NUMBER NOT NULL
);

CREATE TABLE CASTO_PREPARATION_PRICE_INFO (
  ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_AMOUNT_INFO (AMOUNT_INFO_ID),
  POIDS NUMBER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CASTO_ORDER_PRICE_INFO (
  ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_AMOUNT_INFO (AMOUNT_INFO_ID),
  FRAISDEPREPARATION NUMBER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE cast_commerce_item (
    COMMERCE_ITEM_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE DCSPP_BILL_ADDR MODIFY (   
    FIRST_NAME          varchar2(100),  
    LAST_NAME           varchar2(100),
    ADDRESS_1            varchar2(100),  
    ADDRESS_2            varchar2(100),
    ADDRESS_3            varchar2(100),
    POSTAL_CODE         varchar2(16),
    CITY                varchar2(100)
);


ALTER TABLE DCSPP_SHIP_ADDR MODIFY (   
    FIRST_NAME          varchar2(100),  
    LAST_NAME           varchar2(100),
    ADDRESS_1            varchar2(100),  
    ADDRESS_2            varchar2(100),
    ADDRESS_3            varchar2(100),
    POSTAL_CODE         varchar2(16),
    CITY                varchar2(100)
);

ALTER TABLE CASTO_ORDER ADD (
                TOTAL_DISCOUNT NUMBER (10,2) NULL,
                PROCESSING_FEES NUMBER (10,2) NULL,
                SHIPPING_FEES NUMBER (10,2) NULL,
                SHIPPING_DISCOUNT NUMBER (10,2) NULL,
                TOTAL_WEIGHT NUMBER (10,2) NULL
);

ALTER TABLE CASTO_COMMERCE_ITEM ADD DELIVERY_PERIOD NUMBER (4,0) NULL;

ALTER TABLE CASTO_ORDER ADD TOTAL_DISCOUNT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD PROCESSING_FEES NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD SHIPPING_FEES NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD SHIPPING_DISCOUNT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD TOTAL_WEIGHT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD ITEMS_DISCOUNT NUMBER (10,2) NULL;

ALTER TABLE CASTO_COMMERCE_ITEM ADD DELIVERY_PERIOD NUMBER (4,0) NULL;

ALTER TABLE CASTO_COMMERCE_ITEM ADD DISPLAY_NAME VARCHAR2(255 BYTE) NULL;

ALTER TABLE CASTO_ORDER ADD TRANSACTION_COUNT NUMBER(2,0) DEFAULT 0 NOT NULL;
ALTER TABLE CASTO_ORDER ADD PAYBOX_HANDLED NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE CASTO_ORDER ADD PAYMENT_SOURCE VARCHAR2(16);

ALTER TABLE CASTO_BILL_ADDR ADD (
  PHONE_NUMBER_2 VARCHAR2 (15),
  LOCALITY VARCHAR2 (100) );

ALTER TABLE CASTO_SHIP_ADDR ADD (
  PHONE_NUMBER_2 VARCHAR2 (15),
  LOCALITY VARCHAR2 (100) );

ALTER TABLE CASTO_ORDER ADD PAYMENT_USER_ID VARCHAR2(40);

CREATE TABLE CAST_ITEM_PRICE_INFO (
  ID VARCHAR2 (40) NOT NULL REFERENCES DCSPP_AMOUNT_INFO (AMOUNT_INFO_ID),
  ON_SALE_DISCOUNT_DISPLAY NUMBER(1,0) DEFAULT 0 NULL,
  PRIMARY KEY (ID)
);

alter table CASTO_ORDER modify COMMENTAIRE varchar2(400);
