CREATE TABLE "CASTO_ORDER_TRANSACTION" 
(
	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATE_TRANS_EXPIRE" DATE, 
	"AUTHORISATION_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID"),
	 UNIQUE ("ORDER_ID")
);