CREATE TABLE CAST_DOCUMENT (
    DOCUMENT_ID								 VARCHAR2(40)	NOT NULL,
	DOCUMENT_TYPE 							 INTEGER	    NULL,
	TITLE									 VARCHAR2(254)	NULL,
	IMAGE									 VARCHAR2(40)   NULL,
	DESCRIPTION								 VARCHAR2(2048) NULL,
	RELATIVE_URL							 VARCHAR2(2048) NULL,
	RATING                                   NUMBER(19,3)	NULL,
	TEMPLATE_ID								 VARCHAR2(40)   NULL
,   CONSTRAINT CAST_DOCUMENT_P PRIMARY KEY (DOCUMENT_ID));

CREATE TABLE CAST_CAT_DOCUMENT (
    SEQUENCE_NUM	       					INTEGER	       NOT NULL,
	DOCUMENT_ID 							VARCHAR2(40)   NOT NULL,
	CATEGORY_ID 							VARCHAR2(40)   NOT NULL,
	CONSTRAINT CAST_CAT_DOCUMENT_P PRIMARY KEY (CATEGORY_ID, SEQUENCE_NUM),
    CONSTRAINT CAST_CAT_DOCUMENT_C_F FOREIGN KEY (CATEGORY_ID) REFERENCES DCS_CATEGORY (CATEGORY_ID),
    CONSTRAINT CAST_CAT_DOCUMENT_D_F FOREIGN KEY (DOCUMENT_ID) REFERENCES CAST_DOCUMENT(DOCUMENT_ID));

CREATE TABLE CAST_DOC_KEYWRDS (
	ID 										VARCHAR2(40) NOT NULL REFERENCES CAST_DOCUMENT(DOCUMENT_ID),
	SEQ_NUM 								INTEGER NOT NULL,
	KEYWORDS 								VARCHAR2(254) NULL,
	PRIMARY KEY(ID, SEQ_NUM));

CREATE TABLE cast_style (
    style_id VARCHAR2 (40) NOT NULL PRIMARY KEY,
    color VARCHAR2 (7) DEFAULT '#000000',
    foreground VARCHAR2 (7) DEFAULT '#FFFFFF',
    dropdown_color VARCHAR2 (7),
    font_name VARCHAR2 (30),
    font_size VARCHAR2 (5),
    font_weight NUMBER DEFAULT 0 NOT NULL,
	tab_style VARCHAR2 (30),
	bg_style VARCHAR2 (30),
	link_style VARCHAR2 (30),
	facet_style VARCHAR2 (30),
	breadcrumbs_style VARCHAR2 (30),
	product_promo_style VARCHAR2 (30),
	paging_style VARCHAR2 (30),
	cloud_style VARCHAR2 (30),
	right_menu_style VARCHAR2 (30),
	list_style VARCHAR2 (30),
	border_style  VARCHAR2 (30)
);

CREATE TABLE cast_category_style (
    category_id VARCHAR2 (40) NOT NULL REFERENCES dcs_category(category_id),
    style_id VARCHAR2 (40) NOT NULL REFERENCES cast_style(style_id),
    PRIMARY KEY (category_id)
);

CREATE TABLE CAST_PROMO_TEMPLATE (
	PROMO_TEMPLATE_ID                       VARCHAR2(40)        NOT NULL,
	LAYOUTTYPE                              INTEGER             NOT NULL,
	PRIMARY KEY (PROMO_TEMPLATE_ID));

CREATE TABLE CAST_PROMO_INFORMATION (
	PROMO_INFORMATION_ID                    VARCHAR2(40)        NOT NULL,
	IMAGE                                   VARCHAR2(40)        NULL,
	FLASH                                   VARCHAR2(40)        NULL,
	DESCRIPTION                             VARCHAR2(400)       NULL,
	URL                                     VARCHAR2(255)        NULL,
	VIDEOURL                                VARCHAR2(500)       NULL,
	TITLE									VARCHAR2(100)		NULL,
	DOCUMENT_ID								VARCHAR2(40)    	NULL REFERENCES CAST_DOCUMENT(DOCUMENT_ID),
	PRODUCT_ID 								VARCHAR2(40)		NULL REFERENCES DCS_PRODUCT (PRODUCT_ID),
	CATEGORY_ID								VARCHAR2(40) 		NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
	PRIMARY KEY (PROMO_INFORMATION_ID));

CREATE TABLE CAST_TEMPLATE_INFORMATION (
	PROMO_TEMPLATE_ID                       VARCHAR2(40)        NOT NULL REFERENCES CAST_PROMO_TEMPLATE(PROMO_TEMPLATE_ID),
	PROMO_INFORMATION_ID                    VARCHAR2(40)        NOT NULL REFERENCES CAST_PROMO_INFORMATION(PROMO_INFORMATION_ID),
	PROMO_KEY                              INTEGER             NOT NULL,
	PRIMARY KEY (PROMO_TEMPLATE_ID, PROMO_INFORMATION_ID, PROMO_KEY));

CREATE TABLE CASTO_COULEUR (
  	ID       								VARCHAR2(32)   NOT NULL,
  	COULEUR  								VARCHAR2(32)   NOT NULL,
  	NOM      								VARCHAR2(100)  NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_SKU (
	SKU_ID 									VARCHAR2(40) 		NOT NULL REFERENCES DCS_SKU(SKU_ID), 
	CODEARTICLE 							INTEGER				NULL, 
	MODELE 									VARCHAR2(45)		NULL, 
	MARQUECOMMERCIAL 						VARCHAR2(100)		NULL, 
	RESTRICTIONSUSAGE 						VARCHAR2(300)		NULL, 
	MENTIONSLEGALESOBLIGATOIRES 			VARCHAR2(1200)		NULL, 
	CONTRAINTESUTILISATION 					VARCHAR2(1200), 
	PLUSDUPRODUIT 							VARCHAR2(1200)		NULL, 
	LIBELLECLIENTCOURT 						VARCHAR2(2200)		NULL, 
	GENERALEMENTLIVREENHEURES 				NUMBER(2, 0)		NULL, 
	LIVRAISONDIRECTEFOURNISSEUR 			NUMBER(1, 0), 
	CHAMPSDYNAMIQUE 						NUMBER(1, 0)		NULL, 
	ENVENTE 								NUMBER(1, 0)		NULL, 
	HORSNORMES 								NUMBER(1, 0)		NULL, 
	CODEFOURNISSEUR 						INTEGER				NULL, 
	NOMFOURNISSEUR 							VARCHAR2(45)		NULL, 
	POIDSUV 								INTEGER				NULL, 
	CODERAYON 								INTEGER				NULL, 
	CODEFAMILLE 							INTEGER				NULL, 
	CODEMODULE 								INTEGER				NULL,	
	TAUXTVA 								NUMBER(12, 2)		NULL, 
	PRIXVENTETTCFRANCS 						NUMBER(12, 2)		NULL, 
	PRIXVENTETTCEURO 						NUMBER(12, 2)		NULL, 
	PRIXVENTEHTFRANCS 						NUMBER(12, 2)		NULL, 
	PRIXVENTEHTEURO 						NUMBER(12, 2)		NULL, 
	HAUTEURUV 								INTEGER				NULL, 
	LARGEURUV								INTEGER				NULL, 
	PROFONDEURUV 							INTEGER				NULL, 
	DATECREATIONCODEARTICLE 				DATE				NULL, 
	DATEFINVIE 								DATE				NULL, 
	FRAISEXCEPTIONNEL 						NUMBER(12, 2)		NULL, 
	GARANTIE 								VARCHAR2(70)		NULL, 
	LIBELLEDESCRIPTIFARTICLE 				VARCHAR2(300)		NULL, 
	LIBELLECLIENTLONG 						VARCHAR2(1200)		NULL, 
	UNITEUV 								VARCHAR2(30)		NULL, 
	NORMESTEXT 								VARCHAR2(400)		NULL, 
	CADEAU 									NUMBER(1, 0)		NULL, 
	VENTEENMAGASINSEULEMENT 				NUMBER(1, 0)		NULL, 
	COULEUR 								VARCHAR2(32)		NULL REFERENCES CASTO_COULEUR (ID), 
	COEFFICIENTDESATISFACTION 				NUMBER(10, 2)		NULL, 
	TYPE_DE_TRANSPORT 						INTEGER				NULL,  --unused
	EXONERATION_PFE							NUMBER(1, 0)		NULL, 
	LIBELLEPROMOTIONNEL 					VARCHAR2(80)		NULL, 
	URLGRANDPICTOREMISE 					VARCHAR2(80)		NULL, 
	URLPETITPICTOREMISE 					VARCHAR2(80)		NULL, 
	DATEDEBUTFONCTIONNELLE 					DATE				NULL, 
	DATEFINFONCTIONNELLE 					DATE				NULL, 
	DATEDEBUTAFFICHAGE 						DATE				NULL, 
	UNIQUEMENTSURLESITE 					NUMBER(1, 0)		NULL, 
	LISTPRICEXLS 							NUMBER(19, 7)		NULL, 
	TYPEEXPEDITION							NUMBER(8, 0)		NULL, 
	TYPEARTICLE 							NUMBER(8, 0)		NULL, 
	TRANSPORTEUR 							VARCHAR2(40)		NULL, 
	EXONERATIONPFT 							NUMBER(1, 0)		NULL, 
	RETRAITMOMENTANEDATEDEBUT 				DATE				NULL, 
	RETRAITMOMENTANEDATEFIN 				DATE				NULL, 
	RETRAITMOMENTANEMOTIFSCODIFIES 			NUMBER(8, 0)		NULL, 
	RETRAITMOMENTANEUTILISATEUR 			VARCHAR2(60)		NULL, 
	DELAIEXPEDITIONBO 						NUMBER(8, 0)		NULL, --unused
	ECOTAXEENEURO							NUMBER(14, 2)		NULL, 
	VIDEO_URL 								VARCHAR2(50)		NULL, 
	BAROMETRE 								NUMBER				NULL, 
	CHAPO_CONTENU 							VARCHAR2(100)		NULL, 
	CHAPO_STYLE 							NUMBER				NULL, 
	PROMOTIONSEXCLUES 						NUMBER(1, 0)		NULL, 
	PRIXDETAIL 								NUMBER(12, 0)		NULL, 
	PRIXTYPEDETAIL 							NUMBER				NULL, 
	FIABILITESTOCK 							NUMBER(3, 0)		NULL, 
	CACHESKUCOMPTEUR 						NUMBER(11, 2)		NULL, 
	CODENEWMODULE 							VARCHAR2(100)		NULL, 
	SOUMISAD3E 								NUMBER(1, 0)		NULL, 
	PRMP 									NUMBER(12, 2)		NULL, 
	DELAIAPPROFOURNISSEUR 					NUMBER(12, 2)		NULL, 
	PROMOTIONCARTEATOUT 					NUMBER(1, 0)		NULL, 
	PURCENTPROMOCARTEATOUT 					INTEGER				NULL, 
	ISPURCENT 								INTEGER				NULL, 
	QUANTITE_LIMITEE 						NUMBER(1, 0)		NULL, 
	THEME_SKU 								VARCHAR2(70)		NULL, 
	URL_PAGE 								VARCHAR2(260)		NULL, 
	CONDITIONSPARTICULIERES 				NUMBER				NULL,
	EXCLUSIONLIVRAISONCORSE 				NUMBER				NULL, 
	SOMMEFORFAITAIRE 						NUMBER(19, 7)		NULL, 
	FLASH_PRODUIT 							VARCHAR2(100)		NULL, 
	FLASH_ZOOM 								VARCHAR2(100)		NULL, 
	DATE_DEB_DESTOCK 						DATE				NULL, 
	DATE_FIN_DESTOCK 						DATE				NULL, 
	DATE_INIT_DESTOCK 						DATE				NULL, 
	VAL_STOCK_DESTOCK 						NUMBER(6, 0)		NULL, 
	CUV 									VARCHAR2(2)			NULL, 
	CUP 									VARCHAR2(2)			NULL, 
	PUPUV 									NUMBER(10, 6)		NULL,
	PRIX_REF 								NUMBER(12, 2)		NULL,
	PRIX_SOLDE								NUMBER(12, 2)		NULL,
	F_SOLDE									NUMBER(1, 0)		NULL,	
	DATE_FIN_SOLDE							DATE				NULL,
	PRIMARY KEY (SKU_ID));

CREATE INDEX CASTO_SKU_CODEARTICLE_IDX ON CASTO_SKU (CODEARTICLE);
CREATE INDEX CASTO_SKU_MARQUECOMMERCIAL_IDX ON CASTO_SKU (MARQUECOMMERCIAL) ;

CREATE TABLE CASTO_SKU_PICTO (
	SKU_ID 									VARCHAR2(40) 		NOT NULL REFERENCES CASTO_SKU(SKU_ID), 
	SEQ_NUM 								INTEGER	 			NOT NULL, 
	URL_PICTO 								VARCHAR2(100)		NULL,
	PRIMARY KEY (SKU_ID, SEQ_NUM)); 

CREATE TABLE CASTO_SKU_RELATED (
	SKU_ID 									VARCHAR2(40) 		NOT NULL REFERENCES CASTO_SKU(SKU_ID), 
	AUX_ID 									VARCHAR2(40) 		NOT NULL REFERENCES CASTO_SKU(SKU_ID),
	PRIMARY KEY (SKU_ID, AUX_ID));

CREATE TABLE CASTO_SKU_CROSS_SELLING (
	CROSS_ID 								VARCHAR2(40) 		NOT NULL, 
	SKU_ID 									VARCHAR2(40)		NULL REFERENCES DCS_SKU (SKU_ID), 
	PRODUCT_ID 								VARCHAR2(40)		NULL REFERENCES DCS_PRODUCT (PRODUCT_ID),
	PRIMARY KEY (CROSS_ID));

CREATE TABLE CASTO_SKU_CROSS_SELLING_ASSOC (
	SKU_ID 									VARCHAR2(40)		NOT NULL REFERENCES DCS_SKU (SKU_ID), 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	CROSS_ID 								VARCHAR2(40)		NULL REFERENCES CASTO_SKU_CROSS_SELLING (CROSS_ID),
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM));	

CREATE TABLE CASTO_SKU_IK_CS_ASSOC (
	SKU_ID 									VARCHAR2(40)		NOT NULL REFERENCES DCS_SKU (SKU_ID), 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	CROSS_ID 								VARCHAR2(40)		NULL REFERENCES CASTO_SKU_CROSS_SELLING (CROSS_ID),
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM));	

CREATE TABLE CASTO_SKU_ATTR_VALUE (
	ATTRIBUTE_ID 							VARCHAR2(40)		NOT NULL, 
	ATTRIBUTE_NAME 							VARCHAR2(42)		NULL, 
	DISPLAYNAME 							VARCHAR2(50)		NULL, 
	VALUEINTEGER							INTEGER				NULL, 
	VALUESTRING 							VARCHAR2(255)		NULL,	 
	VALUEFLOAT 								NUMBER(12, 2)		NULL, 
	VALUEDATE 								DATE				NULL, 
	VALUEBOOLEAN 							NUMBER(1, 0)		NULL, 
	UNIT 									VARCHAR2(10)		NULL, 
	TYPE 									INTEGER				NULL,
	PRIMARY KEY (ATTRIBUTE_ID)); 

CREATE TABLE CASTO_SKU_ATTR (
	SKU_ID 									VARCHAR2(40) 		NOT NULL REFERENCES CASTO_SKU(SKU_ID), 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	ATTRIBUTE_ID 							VARCHAR2(40)		NULL REFERENCES CASTO_SKU_ATTR_VALUE(ATTRIBUTE_ID),
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM));

CREATE INDEX CASTO_ATTR_SKUID_IDX ON CASTO_SKU_ATTR (ATTRIBUTE_ID DESC);

CREATE TABLE CASTO_NORMES (
	NORMES_ID 								VARCHAR2(40) NOT NULL, 
	URLPICTOGRAMME 							VARCHAR2(254), 
	URLPAGE 								VARCHAR2(254), 
	DESCRIPTION 							LONG, 
	NOMCOURT 								VARCHAR2(20),
	PRIMARY KEY (NORMES_ID));

CREATE TABLE CASTO_SKU_NORMES (
	SKU_ID 									VARCHAR2(40) 		 NOT NULL REFERENCES CASTO_SKU(SKU_ID), 
	SEQUENCE_NUM 							INTEGER	 			 NOT NULL, 
	NORMES_ID 								VARCHAR2(40) 		 NOT NULL REFERENCES CASTO_NORMES(NORMES_ID),
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM));

CREATE TABLE CASTO_SKU_SERVICE_MAGASIN (
	SKU_ID 									VARCHAR2(40) 		NOT NULL REFERENCES DCS_SKU(SKU_ID), 
	ID_COUPLE 								VARCHAR2(40)		NOT NULL REFERENCES CASTO_MAGAS_COUPLE_SERVICE(ID_COUPLE),	
	PRIMARY KEY (SKU_ID, ID_COUPLE));

CREATE TABLE CASTO_SKU_MEDIA (
	QUAL_ID 								VARCHAR2(1) 		NOT NULL ENABLE, 
	MEDIA_ID 								VARCHAR2(40) 		NOT NULL ENABLE,
	PRIMARY KEY (MEDIA_ID, QUAL_ID));


CREATE TABLE CASTO_AFFINAGE_QUESTION (
	ID 										VARCHAR2(40) 		NOT NULL, 
	LIBELLE 								VARCHAR2(500), 
	CONTENTGROUP 							VARCHAR2(500), 
	MULTIVALUE 								NUMBER 				DEFAULT 0	NOT NULL, 
	MEDIA_ID VARCHAR2(40) 					NULL CONSTRAINT MEDIA REFERENCES DCS_MEDIA(MEDIA_ID),
	PRIMARY KEY (ID));

CREATE TABLE CASTO_AFFINAGE_REPONSE ( 
  	ID           							VARCHAR2(32)               NOT NULL,
  	LIBELLE       							VARCHAR2(32)               NOT NULL,
  	CONTENTGROUP  							VARCHAR2(32),
	PRIMARY KEY (ID));

CREATE TABLE CASTO_AFFINAGE_QUEST_REP (
  	QUESTION_ID   							VARCHAR2(32)        NOT NULL REFERENCES CASTO_AFFINAGE_QUESTION (ID),
  	SEQUENCE_NUM  							INTEGER             NOT NULL,
  	REPONSE_ID    							VARCHAR2(32)		NULL REFERENCES CASTO_AFFINAGE_REPONSE (ID),
	PRIMARY KEY (QUESTION_ID, SEQUENCE_NUM));


CREATE TABLE CASTO_DATA_MAGASIN (
	ID_COUPLE 								VARCHAR2(40) 		NOT NULL, 
	DELAI_APPRO_FOURNISSEUR 				NUMBER(12, 2)		NULL, 
	ECO_TAXE 								NUMBER(19, 7)		NULL, 
	SOUMISAD3E 								NUMBER(1, 0)		NULL, 
	COEFFICIENTDESATISFACTION 				NUMBER(10, 2)		NULL, 
	PRMP 									NUMBER(10, 2)		NULL, 
	PROMCORDRE 								NUMBER(4, 0)		NULL, 
	PROMFNAT 								NUMBER(2, 0)		NULL, 
	PRIXLIVRE 								NUMBER(1, 0)		NULL, 
	DDEBPROMO 								DATE				NULL, 
	DFINPROMO 								DATE				NULL,
	PRODUITDETENU							NUMBER(1, 0)		NULL, 
	PRIXVENTETTCEURO 						NUMBER(10, 2)		NULL, 
	PRIXVENTEHTEURO 						NUMBER(10, 2)		NULL,
	PRIMARY KEY (ID_COUPLE));

CREATE TABLE CASTO_SKU_MAGASIN (
	SKU_ID 									VARCHAR2(40)		NOT NULL, 
	ID_MAGASIN 								VARCHAR2(40)		NOT NULL, 
	ID_COUPLE 								VARCHAR2(40) 		NOT NULL, 	
	PRIMARY KEY (SKU_ID,ID_MAGASIN,ID_COUPLE));

CREATE TABLE CASTO_PRODUCT (
	PRODUCT_ID								VARCHAR2(40) 		NOT NULL, 
	BOUTIQUEMARQUES							NUMBER(1, 0)		NULL, 
	PRODUCT_TETEDEGONDOLE					VARCHAR2(40)		NULL, 
	PRODUCT_FIXEDRELATEDPRODUCTUP			VARCHAR2(40)		NULL, 
	COULEUR									VARCHAR2(32)		NULL, 
	AFFICHAGE_ARTICLECOMPARABLE				NUMBER(1, 0)		NULL,	 
	MARQUECOMMERCIAL						VARCHAR2(100)		NULL, 
	URL_FICHE_TECHNIQUE						VARCHAR2(50)		NULL, 
	URL_MODE_EMPLOI 						VARCHAR2(50)		NULL, 
	CHAPO_CONTENU							VARCHAR2(100)		NULL, 
	CHAPO_STYLE								NUMBER				NULL, 
	NATURE_TETE_GONDOLE						NUMBER(1, 0)		NULL, 
	TYPE_AFFICHAGE_PROMO					NUMBER(1, 0)		NULL, 
	VIDEO_URL								VARCHAR2(50)		NULL, 
	URL_PAGE								VARCHAR2(260)		NULL,
	PRIMARY KEY (PRODUCT_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID),
  	FOREIGN KEY (COULEUR) REFERENCES CASTO_COULEUR (ID));

CREATE TABLE CASTO_PRODUCT_QUESTION (
	PRODUCT_ID								VARCHAR2(40) 		NOT NULL, 
	SEQ 									INTEGER	 			NOT NULL, 
	QUESTION_ID								VARCHAR2(40) 		NOT NULL,
	PRIMARY KEY (PRODUCT_ID, SEQ),
	FOREIGN KEY (PRODUCT_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID),
  	FOREIGN KEY (QUESTION_ID) REFERENCES CASTO_AFFINAGE_QUESTION (ID)); 

CREATE TABLE CASTO_PRODUCT_AFFINAGE (
	PRODUCT_ID 								VARCHAR2(40) 		NOT NULL,
	AFFINAGE 								INTEGER				NULL,
	PRIMARY KEY (PRODUCT_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES DCS_PRODUCT (PRODUCT_ID)); 

CREATE TABLE CASTO_PRODUCT_LISTE_MULTISKU (
	PRODUCT_ID								VARCHAR2(40) 		NOT NULL, 
	LIBELLE_LISTE_ID						VARCHAR2(40) 		NULL,
	CONSTRAINT CASTO_PRODUCT_LISTE_MULTI_PK PRIMARY KEY (PRODUCT_ID));  

CREATE TABLE CASTO_IK_CATEGORY_TYPE (
	TYPE_NAME								VARCHAR2(255)		NOT NULL,
	PRIMARY KEY (TYPE_NAME));
	
CREATE TABLE CASTO_CATEGORY (
	CATEGORY_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
	DROPDOWNTEMPLATE                        VARCHAR2(100)       NULL,
    PIVOT	                                NUMBER(1,0)	        NULL,
	PROMOTEMPLATE                           VARCHAR2(100)       NULL REFERENCES CAST_PROMO_TEMPLATE(PROMO_TEMPLATE_ID),
    PRODUCTS_COUNT	                        INTEGER		        NULL,
  	BOUTIQUEMARQUES             			NUMBER(1),
  	REDACTIONNELFAMILLEMARQUE1  			VARCHAR2(255),
  	TITREBOUTIQUEMARQUE         			VARCHAR2(254),
	COULEUR                     			VARCHAR2(32)	  	REFERENCES CASTO_COULEUR (ID),
	HEADER_PAGE_LISTE           			NUMBER(1),
	TYPE_TETE_GONDOLE          				NUMBER(1),
	BOUTIQUE_EVENT             				NUMBER(1)         	DEFAULT 0,
	IMAGE_URL                   			VARCHAR2(255),
	URL_EDITO                   			VARCHAR2(255),
	DESCRIPTIF_CATEGORIE        			VARCHAR2(255),
	URL_INSPIRATION             			VARCHAR2(255),
	URL_AIDE_AU_CHOIX           			VARCHAR2(255),
	ACTIVATION_COMPARATEUR      			NUMBER(1)        	DEFAULT 1,
	REDACTIONNELFAMILLEMARQUE3  			VARCHAR2(100),
	STYLECATEGORIE              			NUMBER(2)         	DEFAULT 0,
	REDACTIONNELFAMILLEMARQUE2  			NUMBER(2)         	DEFAULT 0,
	TITRE_REFERENCEMENT         			VARCHAR2(200),
	DESTOCKAGE                  			INTEGER,
	BONNES_AFFAIRES             			NUMBER(1,0),
	FOOTER                      			CLOB,
	COEFFIABILITE              				NUMBER(14,2),
	URL_PAGE                    			VARCHAR2(260),
	IK_CATEGORY_TYPE						VARCHAR2(255),
	IK_CATEGORY_TYPE_NAV					NUMBER(2)         	DEFAULT 0,
	NE_PAS_AFFICHER             			INTEGER,
	PRIMARY KEY (CATEGORY_ID));

CREATE TABLE CASTO_INSPI (
  	INSPI_ID  								VARCHAR2(100)	              NOT NULL,
	PRIMARY KEY (INSPI_ID));


CREATE TABLE CASTO_CATEGORY_ESPRIT(
  	ESPRIT_ID  								VARCHAR2(100)	              NOT NULL,
  	SEQ        								INTEGER                       NOT NULL,
  	INSPI_ID   								VARCHAR2(100)	              NOT NULL,
	PRIMARY KEY  (ESPRIT_ID, INSPI_ID));

CREATE TABLE CASTO_INSPI_NUANCIER(
  	INSPI_ID  								VARCHAR2(100 )	              NOT NULL,
  	SEQ       								INTEGER                       NOT NULL,
  	ID        								VARCHAR2(100)		          NOT NULL,
	PRIMARY KEY  (INSPI_ID, ID));

CREATE TABLE CASTO_NUANCIER(
  	ID            							VARCHAR2(100)	              NOT NULL,
  	LIBELLE       							VARCHAR2(255)	              NOT NULL,
  	CODE_COULEUR  							VARCHAR2(500)	              NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_CATEGORY_INSPI(
  	CATEGORY_ID  							VARCHAR2(100)   	          NOT NULL,
  	SEQ          							INTEGER                       NOT NULL,
  	INSPI_ID     							VARCHAR2(100)     		      NOT NULL,
	PRIMARY KEY (CATEGORY_ID, INSPI_ID));

CREATE TABLE CASTO_CATEGORY_SEQUENCE(
  	CAT_ID   								VARCHAR2(40)             	  NOT NULL,
  	SEQ_NUM  								INTEGER                       NOT NULL,
  	SEQ_ID   								VARCHAR2(50),
	PRIMARY KEY (CAT_ID, SEQ_NUM),
	FOREIGN KEY (CAT_ID) REFERENCES CASTO_CATEGORY (CATEGORY_ID) ON DELETE CASCADE);

CREATE TABLE CASTO_CATEGORY_BOUTIQUE_MAG(
  	ID_CATEGORY  							VARCHAR2(40)                  NOT NULL,
  	ID_MAGASIN   							VARCHAR2(40)                  NOT NULL,
	PRIMARY KEY (ID_CATEGORY, ID_MAGASIN),
	FOREIGN KEY (ID_MAGASIN) REFERENCES CASTO_MAGASIN (ID),
  	FOREIGN KEY (ID_CATEGORY) REFERENCES CASTO_CATEGORY (CATEGORY_ID));

CREATE TABLE CASTO_THEMES_NORMES (
  	THEME_ID     VARCHAR2(40 BYTE)          NOT NULL,
 	NAME         VARCHAR2(254 BYTE),
  	DESCRIPTION  LONG,
	PRIMARY KEY (THEME_ID));

CREATE TABLE CASTO_THEMES_NORMES_ASSOC (
  	THEME_ID      VARCHAR2(40 BYTE)         NOT NULL,
  	SEQUENCE_NUM  INTEGER                   NOT NULL,
  	NORMES_ID     VARCHAR2(40 BYTE)         NOT NULL,
	PRIMARY KEY (THEME_ID, SEQUENCE_NUM),
	FOREIGN KEY (THEME_ID) REFERENCES CASTO_THEMES_NORMES (THEME_ID),
  	FOREIGN KEY (NORMES_ID) REFERENCES CASTO_NORMES (NORMES_ID));

CREATE TABLE CASTO_MARQUE (
  	MARQUE_ID            VARCHAR2(40)        NOT NULL,
  	NOMMARQUE            VARCHAR2(254)       NOT NULL,
  	DESCRIPTION          LONG,
  	LOGOMARQUE           VARCHAR2(40),
  	PREMIER_PRIX         VARCHAR2(20),
  	QUALITE_PRIX         VARCHAR2(20),
  	SELECTION_EXCLUSIVE  VARCHAR2(20),
  	GRANDE_MARQUE        VARCHAR2(20),
	URL 				 VARCHAR2(254),
	PRIMARY KEY (MARQUE_ID));

CREATE TABLE CASTO_CODES_UNITE (
  CODE_UNITE            VARCHAR2(2 BYTE),
  DESIGNATION           VARCHAR2(50 BYTE),
  FLAG_AFFICHAGE_UP     VARCHAR2(1 BYTE),
  LIBELLE_AFFICHAGE_UP  VARCHAR2(10 BYTE),
  PRIMARY KEY (CODE_UNITE));

------------------------- EPAM ----------------------------------------

CREATE TABLE CAST_SKU (
    SKU_ID                                  VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU(SKU_ID),
    TEST                                    VARCHAR2(40),
	MESSAGE_INFORMATION	    				VARCHAR2(500));

CREATE TABLE CAST_CATEGORY (
	CATEGORY_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
	DROPDOWNTEMPLATE                        VARCHAR2(100)       NULL,
    PIVOT	                                NUMBER(1,0)	        NULL,
	FEATUREDPRODUCT	                        VARCHAR2(60)	    NULL REFERENCES DCS_PRODUCT(PRODUCT_ID),
	PROMOTEMPLATE                           VARCHAR2(100)       NULL REFERENCES CAST_PROMO_TEMPLATE(PROMO_TEMPLATE_ID),
    PRODUCTS_COUNT	                        integer		        NULL,
	META_KEYWORDS_PATTERN					VARCHAR2(300)		NULL,	
	META_DESCRIPTION_PATTERN				VARCHAR2(300)		NULL,
	PAGE_TITLE_PATTERN				 		VARCHAR2(300)		NULL,
    INFO_TEXT                               VARCHAR2(500)       NULL,
    COMMERCE_TEXT                           VARCHAR2(500)       NULL,
	PRIMARY KEY (CATEGORY_ID));

CREATE TABLE CAST_CATALOG_CATEGORY (
	SEQUENCE_NUM	       					INTEGER	            NOT NULL,
	CATEGORY_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
	CATALOG_ID                              VARCHAR2(40)        NOT NULL REFERENCES DCS_CATALOG(CATALOG_ID),
	PRIMARY KEY (CATEGORY_ID, CATALOG_ID));

CREATE TABLE CAST_GROUPED_PRODUCT (
	GROUPED_PRODUCT_ID                      VARCHAR2(40)        NOT NULL REFERENCES DCS_PRODUCT(PRODUCT_ID),
	GROUPINGTYPE 							INTEGER             NOT NULL,
	PRIMARY KEY (GROUPED_PRODUCT_ID));

CREATE TABLE CAST_SKU_LINK (
    SKU_LINK_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU_LINK(SKU_LINK_ID),
    TABNAME									VARCHAR2(60)        NULL,
	PRIMARY KEY (SKU_LINK_ID));

CREATE TABLE CAST_SKU_PACKS (
	SKU_ID                                  VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU(SKU_ID),
	PACKS_ID                                VARCHAR2(40)        NOT NULL REFERENCES DCS_PRODUCT(PRODUCT_ID),
	PRIMARY KEY (SKU_ID, PACKS_ID));

CREATE TABLE CAST_PRODUCT (
	PRODUCT_ID	                             VARCHAR2(40)	NOT NULL REFERENCES DCS_PRODUCT (PRODUCT_ID),
	RATING                                   NUMBER(19,3)	NULL,
	PRODUCT_BENEFIT                          VARCHAR2(80)	NULL,
	PRODUCT_PROMO_DESCRIPTION                VARCHAR2(80)	NULL,
	PROMO_BACKGROUND_COLOR					 VARCHAR2(40)	NULL,
	PROMO_FONT_COLOR					 	 VARCHAR2(40)	NULL,
	PROMO_START_DATE					 	 DATE           NULL,
	PROMO_EXPIRATION_DATE					 DATE           NULL,
	META_KEYWORDS_PATTERN					 VARCHAR2(300)	NULL,	
	META_DESCRIPTION_PATTERN				 VARCHAR2(300)	NULL,
	PAGE_TITLE_PATTERN				 		 VARCHAR2(300)	NULL,
	SHOW_BRAND_LINK_PDP						 NUMBER(1, 0)	NULL,
	PRIMARY KEY (PRODUCT_ID));

CREATE TABLE CAST_SKU_IMAGES (
    SKU_ID                                  VARCHAR2(40) NOT NULL REFERENCES DCS_SKU(SKU_ID),
    MINIATURE_IMAGE_ID                      VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),
    CAROUSEL_IMAGE_ID                       VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),  
	SUPPORTING_IMAGE_ID                     VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),
	COMPARATOR_IMAGE_ID						VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),
	PRIMARY KEY (SKU_ID)); 

CREATE TABLE CASTO_GESTPROMO_ACTIONCO (
	ACTIONCO_ID VARCHAR2(50) NOT NULL, 
	ACTIONCO_NOM VARCHAR2(50), 
	ACTIONCO_DESCRIPTION VARCHAR2(100), 
	NOTICE VARCHAR2(100),
	PRIMARY KEY (ACTIONCO_ID) 
);

CREATE TABLE CASTO_GESTPROMO_OPECO (
	PROMOTION_ID 			VARCHAR2(50) NOT NULL REFERENCES DCS_PROMOTION(PROMOTION_ID), 
	CREATEUR 				VARCHAR2(50), 
	CONDITIONAPPLICATION 	VARCHAR2(2000), 
	MESSAGECOUPON 			VARCHAR2(2000), 
	TYPEAFFICHAGE 			NUMBER(*,0), 
	APPLICATIONMAGASIN 		NUMBER(*,0), 
	ACTIONCO_ID 			VARCHAR2(50) NULL REFERENCES CASTO_GESTPROMO_ACTIONCO(ACTIONCO_ID), 
	CHAPO 					VARCHAR2(255), 
	USAGEUNIQUE 			NUMBER(*,0), 
	OPECO_NC_ALL 			NUMBER(*,0),
	PRIMARY KEY (PROMOTION_ID) 
);  

CREATE TABLE CASTO_GESTPROMO_ELEMENT (
	PROMOTION_ID VARCHAR2(50) NOT NULL REFERENCES DCS_PROMOTION(PROMOTION_ID), 
	SEQUENCE_NUM NUMBER(*,0) NOT NULL, 
	ELEMENT VARCHAR2(100),
	PRIMARY KEY (PROMOTION_ID, SEQUENCE_NUM) 
);

CREATE TABLE CASTO_GESTPROMO_OPECO_NC (
	PROMOTION_ID VARCHAR2(50) NOT NULL REFERENCES DCS_PROMOTION(PROMOTION_ID), 
	SEQUENCE_NUM NUMBER(*,0) NOT NULL, 
	PROMOTIONNC_ID VARCHAR2(50),
	PRIMARY KEY (PROMOTION_ID, SEQUENCE_NUM) 
); 

CREATE TABLE CASTO_PROMOTION (
	PROMOTION_ID VARCHAR2(50) NOT NULL REFERENCES DCS_PROMOTION(PROMOTION_ID), 
	TYPAGE_PROMOTION NUMBER(*,0),
	PRIMARY KEY (PROMOTION_ID) 
);

CREATE TABLE CAST_PRODUCT_CHARACTERISTICS (
	CATALOG_ID                              VARCHAR2(40)        NOT NULL REFERENCES DCS_CATALOG(CATALOG_ID),
	SEQUENCE_NUM 							INTEGER NOT NULL,
	CHARACTERISTIC_PROPERTY					VARCHAR2(50)	NULL,
	PRIMARY KEY(CATALOG_ID, SEQUENCE_NUM));

ALTER TABLE DCS_CATEGORY 
	MODIFY (DESCRIPTION VARCHAR2(300));

CREATE TABLE CASTO_LEGACY_URL (
	ID 					VARCHAR2(40) 	NOT NULL, 
	URI 				VARCHAR2(400) 	NOT NULL UNIQUE,
	CATEGORY_ID   		VARCHAR2(40) 	NOT NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
	PRIMARY KEY (ID) 
);

CREATE TABLE CASTO_STAGE (
	ID                  VARCHAR2(40) NOT NULL,
	NOM                 VARCHAR2(100),
	descriptif          VARCHAR2(800),
	datestage           DATE,	
	horaires            VARCHAR2(100),
	VIDEO_URL 			VARCHAR2(400),
	PRIMARY KEY(ID));


CREATE TABLE CAST_CATALOGUE (
	ID					VARCHAR2(40) 	NOT NULL,
	TITLE				VARCHAR2(100) 	NOT NULL,
	DESCRIPTION			VARCHAR2(300) 	NOT NULL,
	PROMO_MESSAGE		VARCHAR2(300) 	NULL,
	ACTIVE				NUMBER(1,0)		default 0 not null,
	FEATURED			NUMBER(1,0)		default 0 not null,
	BOOKABLE			NUMBER(1,0)		default 0 not null,
	IMAGE				VARCHAR2(40) 	NOT NULL,
	BROWSE_URL			VARCHAR2(300) 		NULL,
	DISPLAY_ORDER		NUMBER(*,0)		default 0,
	RELEASE_DATE		DATE,
	AVAILABLE_COPIES	NUMBER(*,0),
	PRIMARY KEY (ID));

CREATE TABLE CASTO_SKU_INTEGRATION (
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	CYBERCOACH		 						NUMBER(1, 0)		NULL, 
	RATIO 									NUMBER(8, 2)		NULL,
	BORNES		 							NUMBER(1, 0)		NULL, 
	KITCHEN_PLANNER	 						NUMBER(1, 0)		NULL, 
	PRIMARY KEY (SKU_ID)); 

CREATE TABLE CAST_SKU_INSTRUCTIONS (
    SKU_ID                                  VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU(SKU_ID),
    MEDIA_ID                                VARCHAR2(40)        NOT NULL REFERENCES DCS_MEDIA(MEDIA_ID),
    INSTRUCTION_NAME                        VARCHAR2(100)       NOT NULL,
    PRIMARY KEY(SKU_ID, MEDIA_ID));

ALTER TABLE CASTO_SKU_MAGASIN ADD FOREIGN KEY (SKU_ID) REFERENCES DCS_SKU (SKU_ID) ON DELETE CASCADE;

CREATE TABLE CAST_GROUPED_ASSEMBLY_OPTIONS (
    SEQUENCE_NUM                            INTEGER             NOT NULL,
    GROUPED_PRODUCT_ID                      VARCHAR2(40)        NOT NULL REFERENCES DCS_PRODUCT(PRODUCT_ID),
    SKU_LINK_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU_LINK(SKU_LINK_ID),
    PRIMARY KEY (GROUPED_PRODUCT_ID, SKU_LINK_ID));

ALTER TABLE CAST_PROMO_INFORMATION ADD HTMLURL VARCHAR2(255) NULL;

ALTER TABLE CAST_STYLE ADD LIST_VIEW NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE CAST_PROMO_INFORMATION MODIFY TITLE VARCHAR2 (200);
ALTER TABLE CAST_PROMO_INFORMATION MODIFY DESCRIPTION VARCHAR2 (500);

ALTER TABLE CAST_PROMO_INFORMATION ADD WRAPPAGE NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE CAST_GROUPED_PRODUCT ADD PROMOTEMPLATE VARCHAR2(100) NULL REFERENCES CAST_PROMO_TEMPLATE(PROMO_TEMPLATE_ID);
ALTER TABLE CAST_SKU ADD ON_SALE_DISCOUNT_DISPLAY NUMBER(1,0) DEFAULT 0 NULL;
ALTER TABLE CASTO_SKU MODIFY FLASH_PRODUIT VARCHAR2(255);

ALTER TABLE CAST_DOCUMENT ADD PROMOTEMPLATE VARCHAR2(100)  NULL REFERENCES CAST_PROMO_TEMPLATE(PROMO_TEMPLATE_ID);

ALTER TABLE CAST_PRODUCT ADD FLAG_IMAGE	VARCHAR2(100)	NULL;
ALTER TABLE CAST_PRODUCT ADD FLAG_TEXT	VARCHAR2(200)	NULL;

ALTER TABLE CAST_PRODUCT ADD KITCHEN_CONTENT_HTML	VARCHAR2(200)	NULL;

ALTER TABLE CASTO_SKU ADD video_aux_url	VARCHAR2(2000) NULL;
ALTER TABLE CASTO_SKU ADD video_full_size NUMBER(1, 0) DEFAULT 0;

alter table CAST_CATEGORY modify info_text varchar2(1000);
alter table CAST_CATEGORY modify commerce_text varchar2(1000);

ALTER TABLE CASTO_SKU RENAME COLUMN URL_PAGE TO EAN;

ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_START_DATE DATE NULL;
ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_END_DATE DATE NULL;

update CASTO_SKU set EAN = substr(EAN, 1, 13);
ALTER TABLE CASTO_SKU MODIFY EAN VARCHAR2(13);

