  CREATE TABLE "CASTO_SIPS_LOG" 
   (
	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RESPONSE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(50 BYTE), 
	"MONTANT" NUMBER(*,0), 
	"TRANSACTION_ID" VARCHAR2(20 BYTE), 
	"AUTHORISATION_ID" VARCHAR2(20 BYTE), 
	"PAYMENT_MEANS" VARCHAR2(20 BYTE), 
	"CARD_NUMBER" VARCHAR2(20 BYTE), 
	"PAYMENT_CERTIFICATE" VARCHAR2(20 BYTE), 
	"PAYMENT_TIME" VARCHAR2(20 BYTE), 
	"PAYMENT_DATE" VARCHAR2(20 BYTE), 
	"DEVISE" VARCHAR2(20 BYTE), 
	"PROFILE_ID" VARCHAR2(20 BYTE), 
	"DATE_TRANS_EXPIRE" VARCHAR2(8 BYTE), 
	"TRANSACTION_IDENTIFICATOR" VARCHAR2(20 BYTE), 
	"PAYMENT_SYSTEM" VARCHAR2(8 BYTE), 
	"ABONNEMENT" VARCHAR2(20 BYTE),
	 PRIMARY KEY ("ID")
	);

ALTER TABLE CASTO_SIPS_LOG ADD (
    TRANSACTION_INDEX VARCHAR2(10),
    REQUEST_URL VARCHAR2(1000)
);

