CREATE TABLE "CASTO_ORDER_BACKUP" 
(
	"ORDER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"NOM_CLIENT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PRENOM_CLIENT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TEL_PORTABLE" VARCHAR2(40 BYTE), 
	"TEL_FIXE" VARCHAR2(40 BYTE), 
	"ADRESSE_LIBELLE_FACTU" VARCHAR2(500 BYTE), 
	"ADRESSE_LIBELLE_LIV" VARCHAR2(500 BYTE), 
	"DATE_COMMANDE" DATE NOT NULL ENABLE, 
	"TOTAL_ARTICLES" NUMBER(12,2) NOT NULL ENABLE, 
	"FRAIS_LIVRAISON" NUMBER(12,2) NOT NULL ENABLE, 
	"FRAIS_TRAITEMENT" NUMBER(12,2) NOT NULL ENABLE, 
	"TOTAL_COMMANDE" NUMBER(12,2) NOT NULL ENABLE, 
	"ORIGINE_MAGASIN" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"MOYEN_PAIEMENT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID")
);

CREATE TABLE "CASTO_CCE_ITEM_LISTE_BACKUP" 
(
	"ORDER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COMMERCE_ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID", "COMMERCE_ITEM_ID")
);


CREATE TABLE "CASTO_COMMERCE_ITEM_BACKUP" 
(
	"CDE_REF" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COMMERCE_ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CODE_ARTICLE" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"QUANTITE" NUMBER(*,0) NOT NULL ENABLE, 
	"PRIX_UNITAIRE" NUMBER(12,2) NOT NULL ENABLE, 
	 PRIMARY KEY ("COMMERCE_ITEM_ID", "CDE_REF")
); 

ALTER TABLE CASTO_ORDER_BACKUP MODIFY (   
    NOM_CLIENT            varchar2(100),  
    PRENOM_CLIENT     varchar2(100)
);