CREATE TABLE CASTO_MAILSUIVICOMMANDE (
	ID VARCHAR2(40) NOT NULL, 
	PROFILE_ID VARCHAR2(40) NOT NULL, 
	ORDER_ID VARCHAR2(40) NOT NULL, 
	QUESTIONNAIRE_ID VARCHAR2(40) NOT NULL, 
	LCOMMENTAIRE VARCHAR2(1000), 
	CCONTACT NUMBER(8, 0), 
	CENLEVEMENT NUMBER(8, 0), 
	DATE_ENVOIE DATE, 
	CREMBOURSEMENT NUMBER(8, 0),
	CONSTRAINT PK_CASTO_MAILSUIVICMD PRIMARY KEY (ID));