CREATE TABLE CASTO_QUESTIONS 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(200 BYTE), 
	ORDRE_AFFICHAGE VARCHAR2(10 BYTE), 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_PROFESSION 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(100 BYTE), 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_NIVEAUX_BRICOLAGE 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(100 BYTE), 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_SAUVEGARDE_PAGE 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(200 BYTE), 
	URL VARCHAR2(200 BYTE), 
	 PRIMARY KEY (ID)
);

CREATE TABLE CASTO_E_DECORATEUR_OBJET 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	NOM VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	COULEUR VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_SAUVEGARDE_CREATION 
(
	ID NUMBER(*,0) NOT NULL ENABLE, 
	NOM_SAUVEGARDE VARCHAR2(100 BYTE), 
	NOM_PIECE VARCHAR2(100 BYTE), 
	NOM_MOBILIER VARCHAR2(100 BYTE), 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_LISTE_OBJETS_DECO 
(
	SAUVEGARDE NUMBER(*,0) NOT NULL ENABLE, 
	SEQ NUMBER(*,0) NOT NULL ENABLE, 
	OBJET NUMBER(*,0) NOT NULL ENABLE, 
	PRIMARY KEY (SAUVEGARDE, SEQ),
	FOREIGN KEY (SAUVEGARDE)
	  REFERENCES CASTO_SAUVEGARDE_CREATION (ID), 
	FOREIGN KEY (OBJET)
	  REFERENCES CASTO_E_DECORATEUR_OBJET (ID)
);

CREATE TABLE CASTO_CONTACT_INFO 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CIVILITE NUMBER(*,0), 
	SOCIETE VARCHAR2(100 BYTE), 
	TYPE_ADRESSE NUMBER(1,0), 
	EMAIL VARCHAR2(255 BYTE), 
	TEL_GSM VARCHAR2(30 BYTE), 
	TEL_PROFESSIONNEL VARCHAR2(30 BYTE), 
	NUMERO_TVA VARCHAR2(25 BYTE), 
	INFOS_SMS VARCHAR2(1 BYTE), 
	ACTIVE_ADRESSE NUMBER(1,0), 
	phone_number_2	varchar2(15) 	null,
	locality 	varchar2(100) 	null,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID)
	  REFERENCES DPS_CONTACT_INFO (ID)
);


ALTER TABLE dps_contact_info MODIFY (	
	FIRST_NAME 			varchar2(100),  
    LAST_NAME 			varchar2(100),
	ADDRESS1 			varchar2(100),  
	ADDRESS2 			varchar2(100),
	ADDRESS3 			varchar2(100),
	POSTAL_CODE 		varchar2(16),
	CITY 				varchar2(100)
);

CREATE TABLE CASTO_OTHER_BILLING_ADDR 
(
	USER_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	TAG VARCHAR2(42 BYTE) NOT NULL ENABLE, 
	ADDRESS_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (TAG, USER_ID)
);

CREATE TABLE CASTO_OTHER_BILLSHIP_ADDR 
(
	USER_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	TAG VARCHAR2(42 BYTE) NOT NULL ENABLE, 
	ADDRESS_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (TAG, USER_ID)
);

CREATE TABLE CASTO_LISTE_DE_COURSES 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	DATE_CREATION DATE NOT NULL ENABLE, 
	 PRIMARY KEY (ID)
);

CREATE TABLE CASTO_LISTE_DE_COURSES_CONTENU 
(
	LISTE_DE_COURSES_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SKU_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (LISTE_DE_COURSES_ID, SKU_ID),
	FOREIGN KEY (LISTE_DE_COURSES_ID)
	  REFERENCES CASTO_LISTE_DE_COURSES (ID) ENABLE
);
ALTER TABLE dps_user MODIFY (	
	FIRST_NAME 			varchar2(64),  
	LAST_NAME 			varchar2(64),
	LOGIN 				VARCHAR2(255)
); 
CREATE TABLE CASTO_USER 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PROSPECT_SINCE DATE, 
	STATUT NUMBER(*,0), 
	DATE_CHANGE_STATUT DATE, 
	CIVILITE NUMBER(*,0), 
	PROFESSION_ID NUMBER(*,0), 
	TOP_ROBINSON_LIST NUMBER(*,0), 
	NB_RECLAMATIONS NUMBER(*,0), 
	NB_APPELS_CALLCENTER NUMBER(*,0), 
	PROVENANCE_URL VARCHAR2(50 BYTE), 
	CARTE_ATOUT NUMBER(*,0), 
	ADRESSE_FACTURATION_ID VARCHAR2(40 BYTE), 
	ADRESSE_LIVRAISON1_ID VARCHAR2(40 BYTE), 
	ADRESSE_LIVRAISON2_ID VARCHAR2(40 BYTE), 
	SOCIETE VARCHAR2(100 BYTE), 
	BLOQUE NUMBER(1,0), 
	ID_MAGASIN_REF VARCHAR2(255 BYTE), 
	ACCES_FO NUMBER(22,0), 
	NUMEROCARTEATOUT VARCHAR2(100 BYTE), 
	SUPPRIME NUMBER(1,0), 
	TYPEMAJPROFIL NUMBER, 
	DATEMAJPROFIL DATE, 
	DATE_DERNIERE_COMMANDE DATE, 
	UTILISATEUR_CONCEPTION_CUISINE NUMBER(1,0), 
	price_list		varchar2(40) 	null,
	sale_price_list		varchar2(40)	null,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID), 
	 FOREIGN KEY (ADRESSE_FACTURATION_ID)
	  REFERENCES CASTO_CONTACT_INFO (ID), 
	 FOREIGN KEY (ADRESSE_LIVRAISON1_ID)
	  REFERENCES CASTO_CONTACT_INFO (ID), 
	 FOREIGN KEY (ADRESSE_LIVRAISON2_ID)
	  REFERENCES CASTO_CONTACT_INFO (ID), 
	 FOREIGN KEY (PROFESSION_ID)
	  REFERENCES CASTO_PROFESSION (ID)
);

CREATE TABLE CASTO_USER_LISTE_DE_COURSES 
(	
	USR_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	LISTEDECOURSES_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (USR_ID, LISTEDECOURSES_ID),
	FOREIGN KEY (LISTEDECOURSES_ID)
	  REFERENCES CASTO_LISTE_DE_COURSES (ID), 
	FOREIGN KEY (USR_ID)
	  REFERENCES DCS_USER (USER_ID)
);

CREATE TABLE CASTO_USER_FOGROUPS 
(	
	USR_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	GROUP_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (USR_ID, GROUP_ID)
);	

CREATE TABLE CASTO_IDENTIFICATION_HELPER 
(	
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	REMINDER_PASSWORD VARCHAR2(100 BYTE), 
	REPONSE_REMINDER VARCHAR2(50 BYTE), 
	PRIMARY KEY (ID),
	FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);
 
CREATE TABLE CASTO_CLUB_CASTO 
(	
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	MEMBRE_CLUB NUMBER(*,0), 
	DATE_ENTREE_CLUB DATE, 
	DATE_SORTIE_CLUB DATE, 
	TOP_PARRAIN NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT CLUB_CASTO_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);
 
CREATE TABLE CASTO_STAT_LAST_VISIT 
(	
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	NB_PAGE_DERNIERE_SESSION NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT STAT_LAST_VISIT_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);
 
CREATE TABLE CASTO_SCORES 
(	
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CODE_SEG_COMPORT_1 NUMBER(*,0), 
	POTENTIEL NUMBER(*,0), 
	CONTRIBUTION_A_LA_MARGE NUMBER(*,0), 
	SATISFACTION_CLIENT NUMBER(*,0), 
	CLUB_READERS NUMBER(*,0), 
	BLACK_LIST NUMBER(*,0), 
	NB_PROJETS_ENVOYE_AMI NUMBER(*,0), 
	CODE_RFM NUMBER(*,0), 
	RENTABILITE NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT CASTO_SCORES_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);
 

CREATE TABLE CASTO_MON_NIVEAU_BRICOLAGE 
(	
   ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	NIVEAU_CATEGORIE_1_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_2_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_3_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_4_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_5_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_6_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_7_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_8_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_9_ID NUMBER(*,0), 
	NIVEAU_CATEGORIE_10_ID NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT MON_NIVEAU_BRICOLAGE_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID) ENABLE, 
	FOREIGN KEY (NIVEAU_CATEGORIE_1_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_2_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_3_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_4_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_5_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_6_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_7_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_8_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_9_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE, 
	 FOREIGN KEY (NIVEAU_CATEGORIE_10_ID)
	  REFERENCES CASTO_NIVEAUX_BRICOLAGE (ID) ENABLE
);


CREATE TABLE CASTO_STAT_COMMERCE 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	NB_SESSION NUMBER(*,0), 
	NB_SESSION_AVEC_ACHAT NUMBER(*,0), 
	NB_TOTAL_COMMANDES NUMBER(*,0), 
	MONTANT_TOTAL_COMMANDE_HT NUMBER(*,0), 
	MONTANT_TOTAL_COMMANDE_TTC NUMBER(*,0), 
	MONTANT_TOTAL_FACTURE_TTC NUMBER(*,0), 
	NB_ARTICLE_COMMANDE_EN_PROMO NUMBER(*,0), 
	MONTANT_PROMO_CUMULE_TTC NUMBER(*,0), 
	NB_COUPONS_UTILISE NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT STAT_COMMERCE_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);


CREATE TABLE CASTO_RAYONS_UTILISE 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	COMPTEUR_USAGE_RAYON_1 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_2 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_3 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_4 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_5 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_6 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_7 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_8 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_9 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_10 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_11 NUMBER(*,0), 
	COMPTEUR_USAGE_RAYON_12 NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT RAYONS_UTILISE_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);
 
CREATE TABLE CASTO_LOGEMENT 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	ANCIENNETE_LOGEMENT VARCHAR2(20 BYTE), 
	DATE_ENTREE_LOGEMENT DATE, 
	SITUATION_HABITAT NUMBER(*,0), 
	JARDIN NUMBER(*,0), 
	TYPE_LOGEMENT NUMBER(*,0), 
	BALCON NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT LOGEMENT_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID) ENABLE
);

CREATE TABLE CASTO_TELEPHONIE 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	TELEPHONE_PRIVE VARCHAR2(40 BYTE), 
	TELEPHONE_PORTABLE VARCHAR2(40 BYTE), 
	TELEPHONE_TRAVAIL VARCHAR2(40 BYTE), 
	SMS_ACCEPTED NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT TELEPHONIE_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID) ENABLE
);


CREATE TABLE CASTO_USER_MAILING 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	EMAIL_HTML NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT USER_MAILING_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);

CREATE TABLE CASTO_SITUATION_FAMILIALE 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SITUATION_FAMILIALE NUMBER(*,0), 
	NB_ENFANTS NUMBER(*,0), 
	PRIMARY KEY (ID),
	CONSTRAINT SITUATION_FAMILIALE_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
); 

CREATE TABLE CASTO_USER_NEWSLETTER 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	ABONNEMENT_NEWSLETTER_ID VARCHAR2(100 BYTE), 
	PRIMARY KEY (ID),
	CONSTRAINT USER_NEWSLETTER_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID)
);

CREATE TABLE CASTO_MES_PAGES_SAUVEGARDEES 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SEQ NUMBER(*,0) NOT NULL ENABLE, 
	SAUVEGARDE_ID NUMBER(*,0) NOT NULL ENABLE, 
	PRIMARY KEY (ID, SEQ),
	CONSTRAINT MES_PAGES_SAUVEGARDEES_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID), 
	FOREIGN KEY (SAUVEGARDE_ID)
	  REFERENCES CASTO_SAUVEGARDE_PAGE (ID)
); 

CREATE TABLE CASTO_MES_CREA_SAUVEGARDEES 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SEQ NUMBER(*,0) NOT NULL ENABLE, 
	SAUVEGARDE_ID NUMBER(*,0) NOT NULL ENABLE, 
	PRIMARY KEY (ID, SEQ),
	CONSTRAINT MES_CREA_SAUVEGARDEES_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID), 
	FOREIGN KEY (SAUVEGARDE_ID)
	  REFERENCES CASTO_SAUVEGARDE_CREATION (ID)
);

CREATE TABLE CASTO_WISHLIST 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SEQ NUMBER(*,0) NOT NULL ENABLE, 
	SKU_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (ID, SEQ)
);

CREATE TABLE CASTO_SESSION_TRACKING 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	TRACKID VARCHAR2(40 BYTE), 
	DATE_PREMIERE_VISITE DATE, 
	DATE_DERNIERE_VISITE DATE, 
	PRIMARY KEY (ID)
); 

CREATE TABLE CASTO_USER_SESSION_TRACKING 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SEQ NUMBER NOT NULL ENABLE, 
	TRACKID VARCHAR2(40 BYTE), 
	PRIMARY KEY (ID, SEQ),
	CONSTRAINT USER_SESSION_TRACKING_ID FOREIGN KEY (ID)
	  REFERENCES DPS_USER (ID), 
	FOREIGN KEY (TRACKID)
	  REFERENCES CASTO_SESSION_TRACKING (ID)
);

CREATE TABLE CASTO_FOGROUPS
(	
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	DATE_CREATION DATE NOT NULL ENABLE, 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_FOPRIV 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	LIBELLE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (ID)
);

CREATE TABLE CASTO_FOGROUPS_FOPRIV 
(
	GROUP_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIV_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (GROUP_ID, PRIV_ID)
);

CREATE TABLE CASTO_ALERTE_DISPONIBILITE 
(
	ALERTE_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	USER_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SKU_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	ETAT_ALERTE VARCHAR2(1 BYTE), 
	DATE_CREATION_ALERTE DATE, 
	DATE_ENVOI_EMAIL DATE, 
	PRIMARY KEY (ALERTE_ID),
	FOREIGN KEY (USER_ID)
	  REFERENCES DCS_USER (USER_ID)
);

CREATE TABLE CASTO_REFEREE
(
	ID 			VARCHAR2(40) 	NOT NULL,
	EMAIL 		VARCHAR2(100) 	NOT NULL,
	COUPON_ID 	VARCHAR2(40) 	NOT NULL, 
	APPLIED 	number(1,0)		DEFAULT 0 not null,
	PRIMARY KEY (ID)
);
CREATE INDEX CASTO_REFEREE_COUPONID_IDX ON CASTO_REFEREE (COUPON_ID);

CREATE TABLE CASTO_REFERRER_REFEREE 
(
	REFERRER_ID		VARCHAR2(40) 	NOT NULL REFERENCES DPS_USER(id),
	REFEREE_ID 		VARCHAR2(100) 	NOT NULL REFERENCES CASTO_REFEREE(id),  
	PRIMARY KEY (REFERRER_ID, REFEREE_ID)
);

CREATE TABLE CASTO_CODES_POSTAUX
(
	REPOSITORYID 		VARCHAR2(40) 	NOT NULL, 
	CODE_POSTAL 		VARCHAR2(5) 	NOT NULL, 
	VILLE 				VARCHAR2(255) 	NOT NULL,
	PRIMARY KEY (REPOSITORYID)
);
INSERT INTO CASTO_CODES_POSTAUX (REPOSITORYID, CODE_POSTAL, VILLE) VALUES ('36686', '98000', 'MONACO');
INSERT INTO CASTO_CODES_POSTAUX (REPOSITORYID, CODE_POSTAL, VILLE) VALUES ('36687', '20000', 'CORSE');

CREATE TABLE MOTIF 
(
  ID 		  VARCHAR2(40), 
  TITLE       VARCHAR2(100),
  CODE        VARCHAR2(40) DEFAULT '0',
  PRIMARY KEY (ID)
 );

CREATE TABLE CONTACT_US_MOTIF 
(
  ID 		  VARCHAR2(40), 
  MOTIF_ID    VARCHAR2(50) REFERENCES MOTIF(ID),
  FORM_TYPE   VARCHAR2(40),	
  MESSAGE     VARCHAR2(500),
  PRIMARY KEY (ID)
);

CREATE TABLE cast_faq_statistics 
(
  nom                 VARCHAR2(64),
  prenom              VARCHAR2(64),
  email               VARCHAR2(255),
  adresse             VARCHAR2(100),
  code_postal         VARCHAR2(5),
  ville               VARCHAR2(64),
  telephone           VARCHAR2(13),
  stat_id             varchar2(40),
  type_contact        varchar2(40),
  motif               varchar2(50),
  civilite            varchar2(15),
  adresse_reponse     varchar2(81),
  message             varchar2(500),
  question            varchar2(500), 
  reference_produit   varchar2(30),
  magasin             varchar2(60),
  date_contact        date,
  type_machine        varchar2(30),
  type_processeur     varchar2(30),
  systeme_exploit     varchar2(30),
  naviguateur         varchar2(30),
  connexion           varchar2(30),
  lundi               number(1),
  mardi               number(1),
  mercredi            number(1),
  jeudi               number(1),
  vendredi            number(1),
  matin               number(1),
  apres_midi          number(1),
  date_enreg	      date,	
  profile_id	      varchar2(40),	
  code_motif          varchar2(5),
  order_id            varchar2(20),
PRIMARY KEY (stat_id)
);  

CREATE TABLE MESSAGE_MOTIF 
(
  ID            VARCHAR2(40) NOT NULL,
  CMOTIF        NUMBER(4,0) NOT NULL,
  CONSTRAINT MESSAGE_MOTIF_PK PRIMARY KEY (ID),
  CONSTRAINT MESSAGE_MOTIF_FK FOREIGN KEY (ID) REFERENCES MOTIF (ID),
  CONSTRAINT MESSAGE__MOTIF_UNIQUE UNIQUE (CMOTIF)
);

CREATE TABLE MESSAGE_QUESTION 
(
  ID            VARCHAR2(40) NOT NULL,
  MOTIF_ID      VARCHAR2(40),
  QUESTION      VARCHAR2(100) NOT NULL,
  INSTRUCTION   VARCHAR2(500),
  LINKTEXT      VARCHAR2(100),
  LINKVALUE     VARCHAR2(100),
  MESSAGE       VARCHAR2(500),
  ORDRE         INT DEFAULT 1000 NOT NULL ,
  CONSTRAINT MESSAGE_QUESTION_PK PRIMARY KEY (ID),
  CONSTRAINT MESSAGE_QUESTION_MOTIF_FK FOREIGN KEY (MOTIF_ID) REFERENCES MESSAGE_MOTIF (ID)
);

CREATE TABLE CASTO_RESERVATION_CATALOGUE (
	ID 					VARCHAR2(40) 	NOT NULL, 
	EMAIL 				VARCHAR2(255) 	NULL, 
	CIVILITE 			VARCHAR2(50) 	NOT NULL, 
	PRENOM 				VARCHAR2(100) 	NOT NULL, 
	NOM 				VARCHAR2(100) 	NOT NULL, 
	ADRESSE 			VARCHAR2(100) 	NOT NULL,
	ADRESSE2 			VARCHAR2(100),
	ADRESSE3 			VARCHAR2(100),
	ADRESSE4 			VARCHAR2(100),
	CPLTADRESSE 		VARCHAR2(100), 
	VILLE 				VARCHAR2(100) 	NOT NULL, 
	CODEPOSTAL 			VARCHAR2(16) 	NOT NULL, 
	PAYS 				VARCHAR2(40) 	NOT NULL, 
	DATENAISSANCE 		DATE, 
	DATERESERVATION 	DATE 			NOT NULL, 
	NOUVEAUCOMPTE 		NUMBER(*,0) 	NULL, 
	OPTIN 				NUMBER(*,0) 	NULL,
	PHONE_NUMBER_1		varchar2(15) 	NOT NULL,
	PHONE_NUMBER_2		varchar2(15),
	CATALOGUE_ID		VARCHAR2(40) 	NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE HINT_SEARCH (
	ID 					VARCHAR2(40) 	NOT NULL, 
	QUERY				VARCHAR2(400) 	NOT NULL,
	LAST_MODIFIED 		DATE 			NOT NULL,
	HINT_COUNT			INT				NULL,
	PRIMARY KEY (ID));

ALTER TABLE CASTO_REFEREE ADD REF_COUPON_ID VARCHAR2(40) NULL;

ALTER TABLE CASTO_USER ADD PASSWORD_HASHED NUMBER (1,0) DEFAULT 1;
ALTER TABLE CASTO_USER ADD
(
  CONSTRAINT CASTO_USER_PASSWORD_HASHED
  CHECK
  (
    PASSWORD_HASHED in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);

ALTER TABLE dps_contact_info MODIFY PHONE_NUMBER VARCHAR2 (50);
ALTER TABLE dps_contact_info MODIFY FAX_NUMBER VARCHAR2 (50);
ALTER TABLE dps_contact_info MODIFY ADDRESS1 VARCHAR2 (120);
ALTER TABLE dps_contact_info MODIFY ADDRESS2 VARCHAR2 (120);

ALTER TABLE dps_user MODIFY PASSWORD VARCHAR2(40);

ALTER TABLE CASTO_REFEREE MODIFY (EMAIL VARCHAR2(255));

ALTER TABLE CONTACT_US_MOTIF ADD CASTO_DIRECT NUMBER (1,0) DEFAULT 0;

CREATE TABLE CASTO_SHOPPINGLIST 
(
	ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	SEQ NUMBER(*,0) NOT NULL ENABLE, 
	SKU_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	PRIMARY KEY (ID, SEQ)
);
