CREATE TABLE "CASTO_BORNES_EXPORT_JOURNAL" 
(
	"SKU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"URL" VARCHAR2(254 BYTE) NOT NULL ENABLE, 
	"DATE_EXPORT" DATE, 
	CONSTRAINT "PK_BORNES_EXPORT_SKU_JOURNAL" PRIMARY KEY ("SKU_ID")
);

CREATE TABLE "CASTO_PLANNER_EXPORT_JOURNAL" 
(
	"SKU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IMAGE_URL" VARCHAR2(254 BYTE), 
	"BRAND_URL" VARCHAR2(254 BYTE), 
	"IMAGE_DATE_EXPORT" DATE, 
	"BRAND_DATE_EXPORT" DATE, 
	CONSTRAINT "PK_PLANNER_EXPORT_SKU_JOURNAL" PRIMARY KEY ("SKU_ID")
);
