  CREATE TABLE "CASTO_EXPORT_JOURNALISATION" 
   (
	"ID"	NUMBER(19)	NOT NULL,
	"TYPE_DE_FLUX" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"NUMERO_DE_SEQUENCE" NUMBER(8,0) NOT NULL ENABLE, 
	"DATE_CREATION" DATE NOT NULL ENABLE, 
	"DATE_INTEGRATION" DATE, 
	"DATE_RECEPTION" DATE, 
	"REPRISEMANUELLE" VARCHAR2(40 BYTE), 
	"RESULTAT" VARCHAR2(40 BYTE), 
	"NB_BLOCKS_ACQUITES" NUMBER(8,0), 
	"MODE_EXPORT" VARCHAR2(10 BYTE), 
	"CODE_RETOUR" NUMBER(2,0),
	CONSTRAINT "PK_CASTO_EXPORT_JOURNALISATION" PRIMARY KEY ("ID")
   );