CREATE TABLE CASTO_REGION_MESSAGES (
  	MESSAGE_ID  							VARCHAR2(40),
  	REGION_ID   							VARCHAR2(40),
  	SEQ         							INTEGER,
	PRIMARY KEY (MESSAGE_ID, REGION_ID));

CREATE TABLE CASTO_MESSAGES (
  	MESSAGE_ID     							VARCHAR2(40),
  	MESSAGE_NOM    							VARCHAR2(50),
  	MESSAGE_TEXTE  							VARCHAR2(4000),
	PRIMARY KEY (MESSAGE_ID));

CREATE TABLE CASTO_DEPARTEMENT_OLD (
	ID      								VARCHAR2(40)              NOT NULL,
	NUMERO  								VARCHAR2(40)              NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_DEPARTEMENT(
	ID         								VARCHAR2(40)                         NOT NULL,
	NUMERO     								VARCHAR2(40)                         NOT NULL,
	NOM        								VARCHAR2(100),
	REGION_ID  								VARCHAR2(40),
	PRIMARY KEY (ID));

CREATE TABLE CASTO_ADRESSE (
	ID             VARCHAR2(40)                     NOT NULL,
	DEPARTEMENTID  VARCHAR2(40)                     NOT NULL,
	VILLE          VARCHAR2(128)             		NOT NULL,
	CP             VARCHAR2(10),
	RUE            VARCHAR2(128),
	TEL            VARCHAR2(32),
	FAX            VARCHAR2(32),
	COMMENTAIRE    VARCHAR2(500),
	PRIMARY KEY (ID),
	--FOREIGN KEY (DEPARTEMENTID) REFERENCES CASTO_DEPARTEMENT_OLD (ID),
  	CONSTRAINT FK_DEPARTEMENT FOREIGN KEY (DEPARTEMENTID) REFERENCES CASTO_DEPARTEMENT (ID));


CREATE TABLE CASTO_ENTITE (
  	ID           VARCHAR2(40)               NOT NULL,
  	ADRESSEID    VARCHAR2(40)               NOT NULL,
  	NOM          VARCHAR2(64)               NOT NULL,
  	LOGIN_ADMIN  VARCHAR2(64)               NOT NULL,
  	PASS_ADMIN   VARCHAR2(64)               NOT NULL,
  	EMAIL        VARCHAR2(255),
	PRIMARY KEY (ID),
	CONSTRAINT FK_ADRESSE FOREIGN KEY (ADRESSEID) REFERENCES CASTO_ADRESSE (ID));


CREATE TABLE CASTO_COMMANDE_SERVICE (
  	ID_SERVICE           					VARCHAR2(40)              NOT NULL,
  	LIBELLE              					VARCHAR2(255)        NOT NULL,
  	URL_BOUTON           					VARCHAR2(255)        NOT NULL,
  	SHIPPING_GROUP_NAME  					VARCHAR2(255)        NOT NULL,  
	PRIMARY KEY (ID_SERVICE));

CREATE TABLE CASTO_MAGASIN (
  	ID                      				VARCHAR2(40)          NOT NULL,
  	ENTITE_ID               				VARCHAR2(40)          NOT NULL,
  	NOM                     				VARCHAR2(64),
  	URL_IMG_PLAN            				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PDF_PLAN            				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	ACCES_ROUTE             				VARCHAR2(500),
  	ACCES_ROUTE2           					VARCHAR2(500),
  	ACCES_AUTOROUTE         				VARCHAR2(500),
  	ACCES_TRANSPORT_COMMUN  				VARCHAR2(500),
  	HORAIRES                				VARCHAR2(500),
  	NOM_SECONDAIRE          				VARCHAR2(64),
  	URL_IMG_PLAN_MASSE      				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PDF_PLAN_MASSE      				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PHOTO               				VARCHAR2(128)   	  DEFAULT 0                     NOT NULL,
  	POSITION_TOP            				INTEGER             DEFAULT 0                     NOT NULL,
  	POSITION_LEFT           				INTEGER             DEFAULT 0                     NOT NULL,
  	KEYWORDS                				VARCHAR2(254),
  	DESCRIPTION             				VARCHAR2(254),
	STORE_URL								VARCHAR2(254),
  	DELAI_PREPARATION       				NUMBER(14),
  	DELAI_LIVRAISON         				NUMBER(14),
	PRIMARY KEY (ID),
	CONSTRAINT FK_ENTITE FOREIGN KEY (ENTITE_ID) REFERENCES CASTO_ENTITE (ID));

CREATE TABLE CASTO_MAGAS_COUPLE_SERVICE (
  	ID_SERVICE  							VARCHAR2(40)             NOT NULL,
  	ID_MAGASIN  							VARCHAR2(40)             NOT NULL,
  	ID_COUPLE   							VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (ID_COUPLE));

CREATE TABLE CASTO_REGION (
  	ID               						VARCHAR2(40)        NOT NULL,
  	NOM              						VARCHAR2(64)   		NOT NULL,
  	URL_IMG_REGION   						VARCHAR2(128),
  	ORDRE_AFFICHAGE  						VARCHAR2(10),
	PRIMARY KEY (ID));


CREATE TABLE CASTO_SERVICE (
  	ID   									VARCHAR2(40)        NOT NULL,
  	NOM  									VARCHAR2(64)   		NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_MAGASIN_COMM_SERVICE (	
  	ID_SERVICE  							VARCHAR2(40)        NOT NULL REFERENCES CASTO_COMMANDE_SERVICE (ID_SERVICE),
  	ID_MAGASIN  							VARCHAR2(40)        NOT NULL REFERENCES CASTO_MAGASIN (ID),  	
  	PRIMARY KEY (ID_SERVICE, ID_MAGASIN));
	
CREATE TABLE CASTO_MAGASIN_SERVICE (
  	MAGASIN_ID  							VARCHAR2(40)        NOT NULL,
  	SEQ         							INTEGER             NOT NULL,
  	SERVICE_ID  							VARCHAR2(40)        NOT NULL,
	PRIMARY KEY (MAGASIN_ID, SERVICE_ID),
	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID),
	FOREIGN KEY (SERVICE_ID) REFERENCES CASTO_SERVICE (ID));

CREATE TABLE CASTO_OFFRE (
  	ID           							VARCHAR2(40)                NOT NULL,
  	REFERENCE    							VARCHAR2(16)                NOT NULL,
  	TITRE        							VARCHAR2(128),
  	DATEMIN     							DATE,
  	DATEMAX      							DATE,
  	ACTIVATE     							NUMBER(1),
  	DESCRIPTION  							LONG,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_ACTUALITE (
  	ID        								VARCHAR2(40)                NOT NULL,
  	TITRE     								VARCHAR2(128),
  	DATEMIN  								DATE,
  	DATEMAX   								DATE,
  	CONTENU   								VARCHAR2(1000),
  	ACTIVATE  								NUMBER(1),
	PRIMARY KEY (ID));

CREATE TABLE CASTO_OPERATION_SPECIALE (
  	ID            							VARCHAR2(40)                   	NOT NULL,
  	TITRE_HP      							VARCHAR2(255)              		NOT NULL,
  	LIBELLE_LIEN  							VARCHAR2(255)              		NOT NULL,
  	TITRE         							VARCHAR2(255)              		NOT NULL,
  	INTRODUCTION  							VARCHAR2(2000)             		NOT NULL,
  	DATE_DEBUT    							DATE                            NOT NULL,
  	DATE_FIN      							DATE                            NOT NULL,
  	ACTIVATE      							NUMBER                          DEFAULT 0                     NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_OPERATION_MAGASIN (
  	ID         								VARCHAR2(40)                      NOT NULL,
  	SEQ         							NUMBER                            NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)                      NOT NULL,
	PRIMARY KEY (ID, SEQ),
	FOREIGN KEY (ID) REFERENCES CASTO_OPERATION_SPECIALE (ID),
  	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID));

CREATE TABLE CASTO_IMAGE_AUX (
  	IMAGE_AUX_ID     						VARCHAR2(40)                NOT NULL,
  	MAGASIN_ID       						VARCHAR2(40)                NOT NULL,
  	SMALL_IMAGE_URL  						VARCHAR2(128)           	NOT NULL,
  	LARGE_IMAGE_URL  						VARCHAR2(128)           	NOT NULL,
	PRIMARY KEY  (IMAGE_AUX_ID));

CREATE TABLE CASTO_OUVERTURE_EXCEP (
  	ID                 						VARCHAR2(40)               NOT NULL,
  	MAGASIN_ID         						VARCHAR2(40)               NOT NULL,
  	LIBELLE            						VARCHAR2(100),
  	DATE_FIN_VALIDITE  						DATE                       NOT NULL,
	PRIMARY KEY (ID));

CREATE TABLE CASTO_OFFRE_MAGASIN (
  	OFFRE_ID    							VARCHAR2(40)                      NOT NULL,
  	SEQ         							INTEGER	                          NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)                      NOT NULL,
	PRIMARY KEY (OFFRE_ID, MAGASIN_ID),
	FOREIGN KEY (OFFRE_ID) REFERENCES CASTO_OFFRE (ID),
	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID));

CREATE TABLE CASTO_MAGASINS_ACTU (
	MAGASIN_ID  							VARCHAR2(40)                      NOT NULL,
  	SEQ         							INTEGER                        NOT NULL,
  	ACTU_ID     							VARCHAR2(40)                      NOT NULL,
	PRIMARY KEY (MAGASIN_ID, ACTU_ID),
	FOREIGN KEY (ACTU_ID) REFERENCES CASTO_ACTUALITE (ID),
  	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID));

CREATE TABLE CASTO_MAGASIN_IMAGE_AUX (
  	MAGASIN_ID    							VARCHAR2(40)                    NOT NULL,
  	SEQ           							INTEGER                         NOT NULL,
  	IMAGE_AUX_ID  							VARCHAR2(40)                    NOT NULL,
	PRIMARY KEY (MAGASIN_ID, IMAGE_AUX_ID),
	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID),
  	FOREIGN KEY (IMAGE_AUX_ID) REFERENCES CASTO_IMAGE_AUX (IMAGE_AUX_ID));

CREATE TABLE CASTO_MAGASIN_OUVERTURE_EXCEP (
  	MAGASIN_ID  							VARCHAR2(40)                      NOT NULL,
  	SEQ         							INTEGER                           NOT NULL,
  	ID          							VARCHAR2(40)                      NOT NULL,
	PRIMARY KEY  (MAGASIN_ID, ID),
	FOREIGN KEY (MAGASIN_ID) REFERENCES CASTO_MAGASIN (ID), 
	FOREIGN KEY (ID) REFERENCES CASTO_OUVERTURE_EXCEP (ID));

CREATE TABLE CASTO_MAGASIN_PROCHE (
  	MAGASIN_REF     						VARCHAR2(40)                  NOT NULL,
  	SEQ             						INTEGER                       NOT NULL,
  	MAGASIN_PROCHE  						VARCHAR2(40)                  NOT NULL,
	PRIMARY KEY  (MAGASIN_REF, MAGASIN_PROCHE),
	FOREIGN KEY (MAGASIN_REF) REFERENCES CASTO_MAGASIN (ID),
  	FOREIGN KEY (MAGASIN_PROCHE) REFERENCES CASTO_MAGASIN (ID));