alter table CASTO_FAST_LAB_CONFIGS add (
"FIRST_IMAGE" VARCHAR2(40 BYTE), 
"SECOND_IMAGE" VARCHAR2(40 BYTE), 
"THIRD_IMAGE" VARCHAR2(40 BYTE), 
"FIRST_CAT_LINK" VARCHAR2(255 BYTE), 
"SECOND_CAT_LINK" VARCHAR2(255 BYTE), 
"THIRD_CAT_LINK" VARCHAR2(255 BYTE), 
"ERROR_NOT_FOUND_MESSAGE" VARCHAR2(500 BYTE));
commit;