CREATE TABLE IPH_CAT_DISPLAY_IMAGE (
	ASSET_VERSION	                        NUMBER(19)   NOT NULL,
    CATEGORY_ID                             VARCHAR2(40) NOT NULL,
    CAT_DISPLAY_IMAGE                   VARCHAR2(40) NULL,
	PRIMARY KEY (CATEGORY_ID,ASSET_VERSION));

CREATE TABLE IPHONE_AUG_AUX_IMAGE(
	ASSET_VERSION							NUMBER(19)	   NOT NULL,
	WORKSPACE_ID							VARCHAR2(40)   NOT NULL,
	BRANCH_ID								VARCHAR2(40)   NOT NULL,
	IS_HEAD									NUMBER(1)	   NOT NULL,
	VERSION_DELETED							NUMBER(1)	   NOT NULL,
	VERSION_EDITABLE						NUMBER(1)	   NOT NULL,
	PRED_VERSION							NUMBER(19)	   NULL,
	CHECKIN_DATE							DATE	       NULL,
	AUGM_AUX_ID  							VARCHAR2(40) NOT NULL,
	DISPLAY_NAME 							VARCHAR2(100) NOT NULL,
	AUG_CAR_IMAGE_ID 						VARCHAR2(40) NOT NULL,
	AUG_TR_IMAGE_ID 						VARCHAR2(40) NOT NULL,
	PRIMARY KEY (AUGM_AUX_ID,ASSET_VERSION)
);

CREATE TABLE IPHONE_VIDEO(
	ASSET_VERSION							NUMBER(19)	   NOT NULL,
	WORKSPACE_ID							VARCHAR2(40)   NOT NULL,
	BRANCH_ID								VARCHAR2(40)   NOT NULL,
	IS_HEAD									NUMBER(1)	   NOT NULL,
	VERSION_DELETED							NUMBER(1)	   NOT NULL,
	VERSION_EDITABLE						NUMBER(1)	   NOT NULL,
	PRED_VERSION							NUMBER(19)	   NULL,
	CHECKIN_DATE							DATE	       NULL,
	IPHONE_VIDEO_ID  						VARCHAR2(40) NOT NULL,
	DISPLAY_NAME 							VARCHAR2(100) NOT NULL,
	SHORT_URL 								VARCHAR2(100) NOT NULL,
	LONG_URL 								VARCHAR2(250) NOT NULL,
	PRIMARY KEY (IPHONE_VIDEO_ID,ASSET_VERSION)
);

CREATE TABLE IPHONE_SKU_AUG_IMAGES (
	ASSET_VERSION	                        NUMBER(19)   NOT NULL,
	SEQ_NUM	       							INTEGER	            NOT NULL,
	SKU_ID                             		VARCHAR2(40)        NOT NULL,
	AUGM_AUX_ID                        		VARCHAR2(40)        NOT NULL,
	PRIMARY KEY (SKU_ID,AUGM_AUX_ID,ASSET_VERSION)
);

COMMIT;