alter table "CASTO_CCE_ITEM_LISTE_BACKUP" add constraint FK_CASTO_CCE_ITEM_LISTE_BACKUP foreign key("ORDER_ID") references "CASTO_ORDER_BACKUP"("ORDER_ID") on delete cascade;

CREATE TABLE CASTO_FAILED_NEWSLETTER(
  FR_URL VARCHAR2(1200 BYTE) NOT NULL ENABLE
);

commit;