ALTER TABLE CAST_PRODUCT ADD CAST_PRIORITY NUMBER(*,0);

CREATE TABLE CAST_CATALOG_ADDITION_PROP (
  CATALOG_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
  SEARCH_BY_PRODUCT NUMBER(1,0) DEFAULT 1, 
  SEARCH_BY_PIVOT NUMBER(1,0) DEFAULT 1, 
  SEARCH_BY_REGULAR NUMBER(1,0) DEFAULT 1,
  BODYSTYLE VARCHAR2(500), 
  PRIMARY KEY (CATALOG_ID), 
  FOREIGN KEY (CATALOG_ID)  REFERENCES DCS_CATALOG (CATALOG_ID) ENABLE
);

ALTER TABLE CAST_CATEGORY ADD FREE_TEXT VARCHAR2(1000 BYTE);