ALTER TABLE "MS_SYNC_JOURNAL" 
DISABLE CONSTRAINT "MS_SYNC_JOURNAL_PK"
;

ALTER TABLE "MS_SYNC_JOURNAL" 
DROP CONSTRAINT "MS_SYNC_JOURNAL_PK"
;

ALTER TABLE "MS_SYNC_JOURNAL" 
MODIFY ( "STORE_ID" NUMBER(4,0) )
;

ALTER TABLE "MS_SYNC_JOURNAL" 
ADD ( "ID" NUMBER(10,0) NOT NULL )
;

ALTER TABLE "MS_SYNC_JOURNAL" 
ADD CONSTRAINT "MS_SYNC_JOURNAL_PK" PRIMARY KEY ("ID") ENABLE
;

DROP SEQUENCE "MS_SYNC_JOURNAL_SEQ"
/

CREATE SEQUENCE "MS_SYNC_JOURNAL_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE
/

CREATE OR REPLACE TRIGGER  "BI_MS_SYNC_JOURNAL"
  before insert on "MS_SYNC_JOURNAL"
  for each row
begin
    select "MS_SYNC_JOURNAL_SEQ".nextval into :NEW.ID from dual;
end;
/
ALTER TRIGGER  "BI_MS_SYNC_JOURNAL" ENABLE
/



ALTER TABLE "MS_STOCK_SERVICE_ERR_LOG" 
ADD ( "ID" NUMBER(10,0) NOT NULL )
;

ALTER TABLE "MS_STOCK_SERVICE_ERR_LOG" 
ADD CONSTRAINT "MS_STOCK_SERVICE_ERR_LOG_PK" PRIMARY KEY ("ID") ENABLE
;

ALTER TABLE "MS_STOCK_SERVICE_ERR_LOG" 
DROP COLUMN "DATE"
;

ALTER TABLE "MS_STOCK_SERVICE_ERR_LOG" 
ADD ( "ERROR_DATE" DATE DEFAULT SYSDATE )
;

DROP SEQUENCE "MS_STOCK_SERVICE_ERR_LOG_SEQ"
/

CREATE SEQUENCE "MS_STOCK_SERVICE_ERR_LOG_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE
/

CREATE OR REPLACE TRIGGER "BI_MS_STOCK_SERVICE_ERR_LOG"
  before insert on "MS_STOCK_SERVICE_ERR_LOG"
  for each row
begin
    select "MS_STOCK_SERVICE_ERR_LOG_SEQ".nextval into :NEW.ID from dual;
end;
/
ALTER TRIGGER "BI_MS_STOCK_SERVICE_ERR_LOG" ENABLE
/

ALTER TABLE "MS_INVENTORY" 
MODIFY ( "PRODUCT_ID" VARCHAR2(40 BYTE) )
;

commit;