/* DROP TABLE "MS_INVENTORY";
DROP TABLE "MS_PCODE_TO_STORES";
DROP TABLE "MS_SYNC_JOURNAL";
DROP TABLE "MS_STOCK_SERVICE_ERR_LOG";
*/
CREATE TABLE "MS_INVENTORY" (
 "PRODUCT_ID" VARCHAR2(8 BYTE),
 "STORE_ID" NUMBER(4,0),
 "STOCK_SNAPSHOT_DATE" DATE,
 "FILE_SEQ" NUMBER(9,0),
 "CREATED_DATE" DATE,
 "UPDATED_DATE" DATE,
 "STOCK_THEORETICAL" NUMBER(12,2),
 "STOCK_RESERVED" NUMBER(12,2),
 CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("STORE_ID", "PRODUCT_ID")
);

CREATE TABLE "MS_PCODE_TO_STORES" (
 "POSTAL_CODE" VARCHAR2(6 BYTE) NOT NULL ENABLE,
 "STORE_1" NUMBER(4,0),
 "STORE_2" NUMBER(4,0),
 "STORE_3" NUMBER(4,0),
 "STORE_4" NUMBER(4,0),
 "STORE_5" NUMBER(4,0),
 "STORE_6" NUMBER(4,0),
 "STORE_7" NUMBER(4,0),
 "STORE_8" NUMBER(4,0),
 "STORE_9" NUMBER(4,0),
 "STORE_10" NUMBER(4,0),
 CONSTRAINT "MS_PCODE_TO_STORES_PK" PRIMARY KEY ("POSTAL_CODE")
);

CREATE TABLE "MS_SYNC_JOURNAL" (
 "STORE_ID" NUMBER(4,0) NOT NULL ENABLE,
 "ENTITY_NUMBER" NUMBER(9,0),
 "FILE_SEQ" NUMBER(9,0),
 "LAST_UPDATE" DATE,
 "STATUS" NUMBER(1,0),
 CONSTRAINT "MS_SYNC_JOURNAL_PK" PRIMARY KEY ("STORE_ID")
);

CREATE TABLE "MS_STOCK_SERVICE_ERR_LOG" (
 "POSTAL_CODE" VARCHAR2(255),
 "STORE_ID" VARCHAR2(255),
 "PROD_ID" VARCHAR2(255),
 "CHANNEL" VARCHAR2(255),
 "DATE" DATE DEFAULT SYSDATE,
 "ERROR_CODE" VARCHAR2(255)
);

CREATE TABLE "MS_INVENTORY" (
 "PRODUCT_ID" VARCHAR2(8 BYTE),
 "STORE_ID" NUMBER(4,0),
 "STOCK_SNAPSHOT_DATE" DATE,
 "FILE_SEQ" NUMBER(9,0),
 "CREATED_DATE" DATE,
 "UPDATED_DATE" DATE,
 "STOCK_THEORETICAL" NUMBER(12,2),
 "STOCK_RESERVED" NUMBER(12,2),
 CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("STORE_ID", "PRODUCT_ID")
);

CREATE INDEX MS_INVENTORY_STOREID_IDX ON MS_INVENTORY (STORE_ID);
CREATE INDEX MS_INVENTORY_PRODUCTID_IDX ON MS_INVENTORY (PRODUCT_ID);

CREATE TABLE "MS_PCODE_TO_STORES" (
 "POSTAL_CODE" VARCHAR2(6 BYTE) NOT NULL ENABLE,
 "STORE_1" NUMBER(4,0),
 "STORE_2" NUMBER(4,0),
 "STORE_3" NUMBER(4,0),
 "STORE_4" NUMBER(4,0),
 "STORE_5" NUMBER(4,0),
 "STORE_6" NUMBER(4,0),
 "STORE_7" NUMBER(4,0),
 "STORE_8" NUMBER(4,0),
 "STORE_9" NUMBER(4,0),
 "STORE_10" NUMBER(4,0),
 CONSTRAINT "MS_PCODE_TO_STORES_PK" PRIMARY KEY ("POSTAL_CODE")
);

CREATE TABLE "MS_SYNC_JOURNAL" (
 "STORE_ID" NUMBER(4,0) NOT NULL ENABLE,
 "ENTITY_NUMBER" NUMBER(9,0),
 "FILE_SEQ" NUMBER(9,0),
 "LAST_UPDATE" DATE,
 "STATUS" NUMBER(1,0),
 CONSTRAINT "MS_SYNC_JOURNAL_PK" PRIMARY KEY ("STORE_ID")
);

CREATE TABLE "MS_STOCK_SERVICE_ERR_LOG" (
 "POSTAL_CODE" VARCHAR2(255),
 "STORE_ID" VARCHAR2(255),
 "PROD_ID" VARCHAR2(255),
 "CHANNEL" VARCHAR2(255),
 "DATE" DATE DEFAULT SYSDATE,
 "ERROR_CODE" VARCHAR2(255)
);

commit;