
  CREATE TABLE "CAST_THEMATIQUE" 
   (	
    "THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
	"DESCRIPTION" VARCHAR2(2048 BYTE), 
    "S_IMAGE" VARCHAR2(40 BYTE), 
    "B_IMAGE" VARCHAR2(40 BYTE), 
    "BG_COLOR" VARCHAR2(25 BYTE), 
    "CHAPTER" VARCHAR2(40 BYTE),
    "FONT_COLOR" VARCHAR2(10 BYTE), 
	"TOP_DOC_TITLE" VARCHAR2(254 BYTE), 
	"TOP_DOC_DESCRIPTION" VARCHAR2(2048 BYTE), 
	"BOTTOM_DOC_TITLE" VARCHAR2(254 BYTE), 
	"BOTTOM_DOC_DESCRIPTION" VARCHAR2(2048 BYTE), 
	 CONSTRAINT "CAST_THEMATIQUE_P" PRIMARY KEY ("THEMATIQUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 


  CREATE TABLE "CAST_THEMATIQUE_DOCS_TOP" 
   (	"SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_TOP_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_TOP_C_F" FOREIGN KEY ("THEMATIQUE_ID")
	  REFERENCES "CAST_THEMATIQUE" ("THEMATIQUE_ID") ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_TOP_D_F" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "CAST_DOCUMENT" ("DOCUMENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;



  CREATE TABLE "CAST_THEMATIQUE_DOCS_BOTTOM" 
   (	"SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_BOTTOM_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_BOT_C_F" FOREIGN KEY ("THEMATIQUE_ID")
	  REFERENCES "CAST_THEMATIQUE" ("THEMATIQUE_ID") ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_BOT_D_F" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "CAST_DOCUMENT" ("DOCUMENT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

 

  CREATE TABLE "CAST_CHAPTERTHEM" 
   (	
    "CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
    "COLOR" VARCHAR2(25 BYTE), 
	 CONSTRAINT "CAST_CHAPTERTHEM_P" PRIMARY KEY ("CHAPTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

 

  CREATE TABLE "CAST_CONTTHEM" 
   (	
    "CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
	 CONSTRAINT "CAST_CONTTHEM_P" PRIMARY KEY ("CONTAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


  CREATE TABLE "CAST_CONT_THEM" 
   (	
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_CONT_THEM_P" PRIMARY KEY ("CONTAINER_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
	 CONSTRAINT "CAST_CONT_THEM_C_F" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CAST_CONTTHEM" ("CONTAINER_ID") ENABLE, 
	 CONSTRAINT "CAST_CONT_THEM_D_F" FOREIGN KEY ("THEMATIQUE_ID")
	  REFERENCES "CAST_THEMATIQUE" ("THEMATIQUE_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

CREATE TABLE "CAST_CONT_CHAPT" 
   (	
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_CONT_CHAPT_P" PRIMARY KEY ("CONTAINER_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
	 CONSTRAINT "CAST_CONT_CHAPT_C_F" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CAST_CONTTHEM" ("CONTAINER_ID") ENABLE, 
	 CONSTRAINT "CAST_CONT_CHAPT_D_F" FOREIGN KEY ("CHAPTER_ID")
	  REFERENCES "CAST_CHAPTERTHEM" ("CHAPTER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  ALTER TABLE "CAST_CHAPTERTHEM" ADD "H_IMAGE" VARCHAR2(40 BYTE);
  
  
  CREATE TABLE "CAST_GUIMENU" 
   (
    "MENU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
    "TITLE" VARCHAR2(254 BYTE), 
    "IMAGE" VARCHAR2(40 BYTE), 
    "CATEGORY" VARCHAR2(40) NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
    "VERSION" NUMBER(*,0) NOT NULL ENABLE,
    "TEMPLATE" VARCHAR2(254 BYTE), 
     CONSTRAINT "CAST_GUIMENU_P" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;



  CREATE TABLE "CAST_MENUITEM" 
   (
    "ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
    "TITLE" VARCHAR2(254 BYTE), 
    "IMAGE" VARCHAR2(40 BYTE), 
    "MENU" VARCHAR2(40) NULL REFERENCES CAST_GUIMENU(MENU_ID),
    "VERSION" NUMBER(*,0) NOT NULL ENABLE,
    "TEMPLATE" VARCHAR2(254 BYTE), 
     CONSTRAINT "CAST_MENUITEM_P" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

ALTER TABLE "CAST_MENUITEM" ADD "URL" VARCHAR2(2048 BYTE);
ALTER TABLE "CAST_MENUITEM" ADD "NEW_TAB" NUMBER(1,0) DEFAULT 0 NOT NULL;



  CREATE TABLE "CAST_GUIMENU_ITEMS" 
   (
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
    "MENU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
    "ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
     CONSTRAINT "CAST_GUIMENU_ITEMS_P" PRIMARY KEY ("ITEM_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
     CONSTRAINT "CAST_GUIMENU_ITEMS_C_F" FOREIGN KEY ("ITEM_ID")
      REFERENCES "CAST_MENUITEM" ("ITEM_ID") ENABLE, 
     CONSTRAINT "CAST_GUIMENU_ITEMS_D_F" FOREIGN KEY ("MENU_ID")
      REFERENCES "CAST_GUIMENU" ("MENU_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  CREATE TABLE "CAST_THEMATIQUE_CHAPT" 
   (	
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_CHAPT_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_CHAPT_C_F" FOREIGN KEY ("THEMATIQUE_ID")
	  REFERENCES "CAST_THEMATIQUE" ("THEMATIQUE_ID") ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_CHAPT_D_F" FOREIGN KEY ("CHAPTER_ID")
	  REFERENCES "CAST_CHAPTERTHEM" ("CHAPTER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


ALTER TABLE "CAST_DOCUMENT" ADD "EXTERNAL_URL"	VARCHAR2(2048 BYTE)	NULL;

ALTER TABLE  "CAST_THEMATIQUE" DROP COLUMN "CHAPTER";

ALTER TABLE "CAST_THEMATIQUE" MODIFY
	(
	"TITLE" VARCHAR2(510 BYTE), 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"TOP_DOC_TITLE" VARCHAR2(510 BYTE), 
	"TOP_DOC_DESCRIPTION" VARCHAR2(3000 BYTE), 
	"BOTTOM_DOC_TITLE" VARCHAR2(510 BYTE), 
	"BOTTOM_DOC_DESCRIPTION" VARCHAR2(3000 BYTE)
	);