CREATE TABLE CASTO_PAYBOX_NUMQUESTION
(
  NUMQUESTION_DATE DATE          NOT NULL ENABLE,
  NUMQUESTION      NUMBER(10, 0) NOT NULL ENABLE
);

INSERT INTO CASTO_PAYBOX_NUMQUESTION (NUMQUESTION_DATE, NUMQUESTION) VALUES (SYSDATE, 1);

COMMIT;