-- 	Expected
-- &1 DESTINATION SCHEMA NAME

ALTER TABLE "&1".dps_contact_info MODIFY PHONE_NUMBER VARCHAR2 (50);
ALTER TABLE "&1".dps_contact_info MODIFY FAX_NUMBER VARCHAR2 (50);
ALTER TABLE "&1".dps_contact_info MODIFY ADDRESS1 VARCHAR2 (120);
ALTER TABLE "&1".dps_contact_info MODIFY ADDRESS2 VARCHAR2 (120);

ALTER TABLE "&1".dps_user MODIFY PASSWORD VARCHAR2(40);

DISCONNECT;
quit;