-- 	Expected
-- &1 MIGRATION SCHEMA NAME


CREATE TABLE "&1".DPS_CONTACT_INFO
(
  ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR2 (40),
  FIRST_NAME VARCHAR2 (120),
  MIDDLE_NAME VARCHAR2 (120),
  LAST_NAME VARCHAR2 (120),
  ADDRESS1 VARCHAR2 (120),
  ADDRESS2 VARCHAR2 (120),
  CITY VARCHAR2 (40),
  STATE VARCHAR2 (25),
  POSTAL_CODE VARCHAR2 (15),
  COUNTRY VARCHAR2 (50),
  PHONE_NUMBER VARCHAR2 (50),
  FAX_NUMBER VARCHAR2 (50),
  PREFIX VARCHAR2 (50),
  SUFFIX VARCHAR2 (50),
  JOB_TITLE VARCHAR2 (120),
  COMPANY_NAME VARCHAR2 (50),
  ADDRESS3 VARCHAR2 (50),
  COUNTY VARCHAR2 (50)
);

CREATE TABLE "&1".CASTO_CONTACT_INFO
(
  ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  CIVILITE NUMBER,
  SOCIETE VARCHAR2 (100),
  TYPE_ADRESSE NUMBER (1,0),
  EMAIL VARCHAR2 (255),
  TEL_GSM VARCHAR2 (30),
  TEL_PROFESSIONNEL VARCHAR2 (30),
  NUMERO_TVA VARCHAR2 (25),
  INFOS_SMS VARCHAR2 (1),
  ACTIVE_ADRESSE NUMBER (1,0),
  CONSTRAINT CASTO_CONTACT_INFO_FK FOREIGN KEY (ID) REFERENCES DPS_CONTACT_INFO(ID)
);

CREATE TABLE "&1".DPS_USER
(
  ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  LOGIN VARCHAR2 (60) NOT NULL,
  PASSWORD VARCHAR2 (40),
  MEMBER NUMBER (1,0),
  FIRST_NAME VARCHAR2 (50),
  MIDDLE_NAME VARCHAR2 (50),
  LAST_NAME VARCHAR2 (50),
  USER_TYPE NUMBER,
  LOCALE NUMBER,
  LASTACTIVITY_DATE DATE,
  REGISTRATION_DATE DATE,
  EMAIL VARCHAR2 (320),
  EMAIL_STATUS NUMBER,
  RECEIVE_EMAIL NUMBER,
  GENDER NUMBER,
  DATE_OF_BIRTH DATE,
  SECURITYSTATUS NUMBER,
  SOCIETE VARCHAR2 (120),
  AUTO_LOGIN NUMBER (1,0),
  LASTPWDUPDATE DATE,
  GENERATEDPWD NUMBER (1,0),
  LAST_EMAILED DATE,
  DESCRIPTION VARCHAR2 (320)
);

ALTER TABLE "&1".DPS_USER ADD
(
  CONSTRAINT DPS_USER2_C
  CHECK 
  (
    member in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);

ALTER TABLE "&1".DPS_USER ADD
(
  CONSTRAINT DPS_USER1_C
  CHECK 
  (
    auto_login in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);

CREATE TABLE "&1".DPS_USER_ADDRESS
(
  ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  HOME_ADDR_ID VARCHAR2 (40),
  BILLING_ADDR_ID VARCHAR2 (40),
  SHIPPING_ADDR_ID VARCHAR2 (40),
  CONSTRAINT DPS_USER_ADDRESS_USER_FK FOREIGN KEY (ID) REFERENCES DPS_USER(ID)
);

CREATE TABLE "&1".DCS_USER
(
  USER_ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  ALLOW_PARTIAL_SHIP NUMBER (1,0),
  DEFAULT_CREDITCARD VARCHAR2 (50),
  DAYTIME_PHONE_NUM VARCHAR2 (50),
  EXPRESS_CHECKOUT NUMBER (1,0),
  DEFAULT_CARRIER VARCHAR2 (320),
  PRICE_LIST VARCHAR2 (50),
  SALE_PRICE_LIST VARCHAR2 (50)
);

ALTER TABLE "&1".DCS_USER ADD
(
  CONSTRAINT DCS_USER1_C
  CHECK 
  (
    allow_partial_ship in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);

ALTER TABLE "&1".DCS_USER ADD
(
  CONSTRAINT DCS_USER2_C
  CHECK 
  (
    express_checkout in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);

CREATE TABLE "&1".DPS_OTHER_ADDR
(
  USER_ID VARCHAR2 (40) NOT NULL,
  TAG VARCHAR2 (50) NOT NULL,
  ADDRESS_ID VARCHAR2 (40) NOT NULL,
  CONSTRAINT DPS_OTHER_ADDR_PK PRIMARY KEY (USER_ID,TAG),
  CONSTRAINT DPS_OTHER_ADDR_USER_FK FOREIGN KEY (USER_ID) REFERENCES DPS_USER(ID)
);

CREATE TABLE "&1".CASTO_USER
(
  ID VARCHAR2 (40) NOT NULL PRIMARY KEY,
  PROSPECT_SINCE DATE,
  STATUT NUMBER,
  DATE_CHANGE_STATUT DATE,
  CIVILITE NUMBER,
  PROFESSION_ID NUMBER,
  TOP_ROBINSON_LIST NUMBER,
  NB_RECLAMATIONS NUMBER,
  NB_APPELS_CALLCENTER NUMBER,
  PROVENANCE_URL VARCHAR2 (60),
  CARTE_ATOUT NUMBER,
  ADRESSE_FACTURATION_ID VARCHAR2 (40),
  ADRESSE_LIVRAISON1_ID VARCHAR2 (40),
  ADRESSE_LIVRAISON2_ID VARCHAR2 (40),
  SOCIETE VARCHAR2 (120),
  BLOQUE NUMBER (1,0),
  ID_MAGASIN_REF VARCHAR2 (320),
  ACCES_FO NUMBER (22,0),
  NUMEROCARTEATOUT VARCHAR2 (120),
  SUPPRIME NUMBER (1,0),
  TYPEMAJPROFIL NUMBER,
  DATEMAJPROFIL DATE,
  DATE_DERNIERE_COMMANDE DATE,
  UTILISATEUR_CONCEPTION_CUISINE NUMBER (1,0),
  CONSTRAINT CASTO_USER_LIVRAISON1_FK FOREIGN KEY (ADRESSE_LIVRAISON1_ID) REFERENCES DPS_CONTACT_INFO(ID),
  CONSTRAINT CASTO_USER_FACTURATION_FK FOREIGN KEY (ADRESSE_FACTURATION_ID) REFERENCES DPS_CONTACT_INFO(ID),
  CONSTRAINT CASTO_USER_ID_FK FOREIGN KEY (ID) REFERENCES DPS_USER(ID),
  CONSTRAINT CASTO_USER_LIVRAISON2_FK FOREIGN KEY (ADRESSE_LIVRAISON2_ID) REFERENCES DPS_CONTACT_INFO(ID)
);

CREATE TABLE "&1".CASTO_OTHER_BILLING_ADDR
(
  USER_ID VARCHAR2 (40) NOT NULL,
  TAG VARCHAR2 (50) NOT NULL,
  ADDRESS_ID VARCHAR2 (40) NOT NULL,
  CONSTRAINT CASTO_OTHER_BILLING_ADDR_PK PRIMARY KEY (TAG,USER_ID)
);

CREATE TABLE "&1".CASTO_OTHER_BILLSHIP_ADDR
(
  USER_ID VARCHAR2 (40) NOT NULL,
  TAG VARCHAR2 (50) NOT NULL,
  ADDRESS_ID VARCHAR2 (40) NOT NULL,
  CONSTRAINT CASTO_OTHER_BILLSHIP_ADDR_PK PRIMARY KEY (TAG,USER_ID)
);

CREATE TABLE "&1".CASTO_ABONNEMENT_NEWSLETTER
(
  EMAIL VARCHAR2 (120) NOT NULL PRIMARY KEY,
  NOM VARCHAR2 (60),
  PRENOM VARCHAR2 (60),
  FORMAT NUMBER,
  ACCES_PARTENAIRES_CASTO NUMBER,
  IS_TEST NUMBER,
  VALID NUMBER,
  DATECREATION DATE,
  EMAIL_STATUS NUMBER,
  RECEIVE_EMAIL NUMBER,
  LOCALE NUMBER,
  NBEMAILFAILURE NUMBER,
  LASTFAILUREDATE DATE,
  CIVILITE VARCHAR2 (20),
  VILLE VARCHAR2 (120),
  CODEPOSTAL VARCHAR2 (20),
  AGE VARCHAR2 (20),
  PROPRIETAIRE_LOCATAIRE VARCHAR2 (30),
  NBPERSONNES VARCHAR2 (20),
  CARTEATOUT NUMBER,
  MAISONCAMPAGNE NUMBER,
  MAISON NUMBER,
  JARDIN NUMBER,
  CANALINSCRIPTION VARCHAR2 (60),
  CANALDESINSCRIPTION VARCHAR2 (60),
  DATEDESINCRPTION DATE,
  DATEDERNIEREMODIFICATION DATE,
  QUESTIONDES1 VARCHAR2 (60),
  QUESTIONDES2 VARCHAR2 (60),
  QUESTIONDES3 VARCHAR2 (60),
  QUESTIONDES4 VARCHAR2 (60),
  QUESTIONDES5 VARCHAR2 (60),
  REMARQUEDES VARCHAR2 (600),
  B2B VARCHAR2 (60),
  JOUEUR NUMBER,
  MAGASIN VARCHAR2 (60),
  DATE_REPONSE_ENQUETE_MAGASIN DATE,
  REPONSE_LOI_LEN VARCHAR2 (50),
  DATE_REPONSE_LOI_LEN DATE,
  PAYS VARCHAR2 (50),
  ESPRIT_CONTEMPORAIN NUMBER (22,0),
  ESPRIT_TECHNICOLOR NUMBER (22,0),
  ESPRIT_CHARME NUMBER (22,0),
  ESPRIT_AUTHENTIQUE NUMBER (22,0),
  DATEINSCRIPTION DATE
);

CREATE TABLE "&1".CASTO_USER_NEWSLETTER
(
  ID VARCHAR2 (50) NOT NULL PRIMARY KEY,
  ABONNEMENT_NEWSLETTER_ID VARCHAR2 (60),
  CONSTRAINT CASTO_USER_NEWSLETTER_USER_FK FOREIGN KEY (ID) REFERENCES DPS_USER(ID)
);

CREATE TABLE "&1".CASTO_ABONNEMENT_NEWSLETTER_T
(
  EMAIL VARCHAR2 (120) NOT NULL PRIMARY KEY,
  NOM VARCHAR2 (60),
  PRENOM VARCHAR2 (60),
  FORMAT NUMBER,
  ACCES_PARTENAIRES_CASTO NUMBER,
  IS_TEST NUMBER,
  VALID NUMBER,
  DATECREATION DATE,
  EMAIL_STATUS NUMBER,
  RECEIVE_EMAIL NUMBER,
  LOCALE NUMBER,
  NBEMAILFAILURE NUMBER,
  LASTFAILUREDATE DATE,
  CIVILITE VARCHAR2 (20),
  VILLE VARCHAR2 (120),
  CODEPOSTAL VARCHAR2 (20),
  AGE VARCHAR2 (20),
  PROPRIETAIRE_LOCATAIRE VARCHAR2 (30),
  NBPERSONNES VARCHAR2 (20),
  CARTEATOUT NUMBER,
  MAISONCAMPAGNE NUMBER,
  MAISON NUMBER,
  JARDIN NUMBER,
  CANALINSCRIPTION VARCHAR2 (60),
  CANALDESINSCRIPTION VARCHAR2 (60),
  DATEDESINCRPTION DATE,
  DATEDERNIEREMODIFICATION DATE,
  QUESTIONDES1 VARCHAR2 (60),
  QUESTIONDES2 VARCHAR2 (60),
  QUESTIONDES3 VARCHAR2 (60),
  QUESTIONDES4 VARCHAR2 (60),
  QUESTIONDES5 VARCHAR2 (60),
  REMARQUEDES VARCHAR2 (600),
  B2B VARCHAR2 (60),
  JOUEUR NUMBER,
  MAGASIN VARCHAR2 (60),
  DATE_REPONSE_ENQUETE_MAGASIN DATE,
  REPONSE_LOI_LEN VARCHAR2 (50),
  DATE_REPONSE_LOI_LEN DATE,
  PAYS VARCHAR2 (50),
  ESPRIT_CONTEMPORAIN NUMBER (22,0),
  ESPRIT_TECHNICOLOR NUMBER (22,0),
  ESPRIT_CHARME NUMBER (22,0),
  ESPRIT_AUTHENTIQUE NUMBER (22,0),
  DATEINSCRIPTION DATE,
  PROFILE_ID VARCHAR2 (50) NULL 
);

CREATE TABLE "&1".DPS_OTHER_ADDR_T
(
  USER_ID VARCHAR2 (40) NOT NULL,
  ADDRESS_ID VARCHAR2 (40) NOT NULL
);

ALTER TABLE "&1".DPS_OTHER_ADDR_T
  ADD CONSTRAINT DPS_OTHER_ADDR_T_PK PRIMARY KEY (USER_ID, ADDRESS_ID)
USING INDEX;

DISCONNECT;
quit;