-- 	Expected
-- &1 DESTINATION SCHEMA NAME

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATETIME FROM DUAL;

SELECT COUNT(1) FROM "&1".CASTO_CONTACT_INFO;

DELETE FROM "&1".CASTO_CONTACT_INFO a
 WHERE NOT EXISTS (SELECT 1 FROM "&1".DPS_OTHER_ADDR b
                    WHERE b.ADDRESS_ID = a.ID
                   UNION
                   SELECT 1 FROM "&1".DPS_USER_ADDRESS b
                    WHERE b.BILLING_ADDR_ID = a.ID
                       OR b.SHIPPING_ADDR_ID = a.ID);

COMMIT;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATETIME FROM DUAL;

SELECT COUNT(1) FROM "&1".CASTO_CONTACT_INFO;

SELECT COUNT(1) FROM "&1".DPS_CONTACT_INFO;

DELETE FROM "&1".DPS_CONTACT_INFO a
 WHERE NOT EXISTS (SELECT 1 FROM "&1".DPS_OTHER_ADDR b
                    WHERE b.ADDRESS_ID = a.ID)
    OR NOT EXISTS (SELECT 1 FROM "&1".DPS_USER_ADDRESS b
                    WHERE b.BILLING_ADDR_ID = a.ID
                       OR b.SHIPPING_ADDR_ID = a.ID);

COMMIT;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATETIME FROM DUAL;

SELECT COUNT(1) FROM "&1".DPS_CONTACT_INFO;

DISCONNECT;
quit;