-- 	Expected
-- &1 DESTINATION SCHEMA NAME

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATETIME FROM DUAL;

UPDATE "&1".DPS_USER SET EMAIL = REPLACE(EMAIL, '#', '@');

COMMIT;

UPDATE "&1".DPS_USER SET LOGIN = REPLACE(LOGIN, '#', '@');

COMMIT;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATETIME FROM DUAL;

DISCONNECT;
quit;