-- 	Expected
-- &1 DESTINATION SCHEMA NAME
-- &2 MIGRATION SCHEMA NAME
-- &3 CATALOG SCHEMA NAME

SELECT 'Migrated accounts:' FROM DUAL;

SELECT 
  'DPS_USER:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".DPS_USER) AS V3,
  (SELECT COUNT(1)
     FROM "&1".DPS_USER) AS V4
  FROM DUAL
UNION  
SELECT 
  'DCS_USER:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".DCS_USER) AS V3,
  (SELECT COUNT(1)
     FROM "&1".DCS_USER) AS V4
  FROM DUAL
UNION  
SELECT 
  'CASTO_USER:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".CASTO_USER) AS V3,
  (SELECT COUNT(1)
     FROM "&1".CASTO_USER) AS V4
  FROM DUAL;

SELECT 'Migrated addresses:' FROM DUAL;

SELECT 
  'DPS_CONTACT_INFO:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".DPS_CONTACT_INFO) AS V3,
  (SELECT COUNT(1)
     FROM "&1".DPS_CONTACT_INFO) AS V4
  FROM DUAL
UNION  
SELECT 
  'CASTO_CONTACT_INFO:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".CASTO_CONTACT_INFO) AS V3,
  (SELECT COUNT(1)
     FROM "&1".CASTO_CONTACT_INFO) AS V4
  FROM DUAL;

SELECT 
  'DPS_USER_ADDRESS:' AS "TABLE",
  (SELECT COUNT(1)
     FROM "&2".DPS_USER_ADDRESS) AS V3,
  (SELECT COUNT(1)
     FROM "&1".DPS_USER_ADDRESS) AS V4
  FROM DUAL;

SELECT 'Migrated newsletter subscriptions:' FROM DUAL;

SELECT 
  'V3:' AS "DB",
  (SELECT COUNT(1)
     FROM "&2".CASTO_ABONNEMENT_NEWSLETTER) AS "ALL",
  (SELECT COUNT(1)
     FROM "&2".CASTO_ABONNEMENT_NEWSLETTER A,
          "&2".CASTO_USER B,
          (SELECT MAX(ID) PROFILE_ID, ABONNEMENT_NEWSLETTER_ID
             FROM "&2".CASTO_USER_NEWSLETTER
            GROUP BY ABONNEMENT_NEWSLETTER_ID) C
    WHERE A.EMAIL = C.ABONNEMENT_NEWSLETTER_ID
      AND C.PROFILE_ID = B.ID) AS "ATTACHED",
  (SELECT COUNT(1)
     FROM "&2".CASTO_ABONNEMENT_NEWSLETTER A
    WHERE NOT EXISTS (SELECT 1 FROM "&2".CASTO_USER_NEWSLETTER B
                       WHERE A.EMAIL = B.ABONNEMENT_NEWSLETTER_ID)) AS "ANONYMOUS"
  FROM DUAL
UNION
SELECT 
  'V4:' AS "DB",
  (SELECT COUNT(1)
     FROM "&1".CASTO_ABONNEMENT_NEWSLETTER) AS "ALL",
  (SELECT COUNT(1)
     FROM "&1".CASTO_ABONNEMENT_NEWSLETTER
    WHERE PROFILE_ID IS NOT NULL) AS "ATTACHED",
  (SELECT COUNT(1)
     FROM "&1".CASTO_ABONNEMENT_NEWSLETTER
    WHERE PROFILE_ID IS NULL) AS "ANONYMOUS"
  FROM DUAL;

SELECT 'Migrated preferred store references:' FROM DUAL;

SELECT
  'V3:' AS "DB",
  (SELECT COUNT(1) 
     FROM
       (SELECT DISTINCT EMAIL
          FROM
            (SELECT C.EMAIL
               FROM "&2".CASTO_USER A, 
                    (SELECT MAX(ID) PROFILE_ID, ABONNEMENT_NEWSLETTER_ID
                       FROM "&2".CASTO_USER_NEWSLETTER
                      GROUP BY ABONNEMENT_NEWSLETTER_ID) B,
                    "&2".CASTO_ABONNEMENT_NEWSLETTER C
              WHERE A.ID = B.PROFILE_ID
                AND B.ABONNEMENT_NEWSLETTER_ID = C.EMAIL
                AND A.ID_MAGASIN_REF IS NOT NULL
             UNION
             SELECT EMAIL
               FROM "&2".CASTO_ABONNEMENT_NEWSLETTER
              WHERE MAGASIN IS NOT NULL))) AS "ALL",
  (SELECT COUNT(1)  
     FROM
       (SELECT DISTINCT EMAIL
          FROM
            (SELECT C.EMAIL
               FROM "&2".CASTO_USER A, 
                    (SELECT MAX(ID) PROFILE_ID, ABONNEMENT_NEWSLETTER_ID
                       FROM "&2".CASTO_USER_NEWSLETTER
                      GROUP BY ABONNEMENT_NEWSLETTER_ID) B,
                    "&2".CASTO_ABONNEMENT_NEWSLETTER C
              WHERE EXISTS (SELECT 1 FROM "&3".CASTO_MAGASIN T1
                             WHERE A.ID_MAGASIN_REF = T1.ID)
                AND A.ID = B.PROFILE_ID
                AND B.ABONNEMENT_NEWSLETTER_ID = C.EMAIL
                AND A.ID_MAGASIN_REF IS NOT NULL
             UNION
            SELECT A.EMAIL
              FROM "&2".CASTO_ABONNEMENT_NEWSLETTER A
             WHERE EXISTS (SELECT 1 FROM "&3".CASTO_MAGASIN B
                            WHERE UPPER(A.MAGASIN) = UPPER(B.NOM))
               AND A.MAGASIN IS NOT NULL))) AS "RIGHT"
  FROM DUAL
UNION
SELECT
  'V4:' AS "DB",
  (SELECT COUNT(1)
     FROM "&1".CASTO_ABONNEMENT_NEWSLETTER a
    WHERE a.MAGASIN IS NOT NULL) AS "ALL",
 (SELECT COUNT(1)
     FROM "&1".CASTO_ABONNEMENT_NEWSLETTER a
    WHERE EXISTS (SELECT 1 FROM "&3".CASTO_MAGASIN b
                   WHERE a.MAGASIN = b.ID)
      AND a.MAGASIN IS NOT NULL) AS "RIGHT"
  FROM DUAL;

DISCONNECT;
quit;