ALTER TABLE "SCD_FACTURE_AVOIR" MODIFY (
  "LADRESSE_1_FACTURE" VARCHAR2(80 BYTE),
  "LADRESSE_2_FACTURE" VARCHAR2(80 BYTE),
  "LADRESSE_3_FACTURE" VARCHAR2(80 BYTE),
  "LADRESSE_1_LIVRAISON" VARCHAR2(80 BYTE),
  "LADRESSE_2_LIVRAISON" VARCHAR2(80 BYTE),
  "LADRESSE_3_LIVRAISON" VARCHAR2(80 BYTE)
);

ALTER TABLE "VTE_ENLEVEMENT" MODIFY (
  "LADRESSE_1_LIVRAISON" VARCHAR2(80 BYTE),
  "LADRESSE_2_LIVRAISON" VARCHAR2(80 BYTE),
  "LADRESSE_3_LIVRAISON" VARCHAR2(80 BYTE)
);

ALTER TABLE "SCD_VENTE_WEB" MODIFY (
  "LCOMMENTAIRE_TRANSPORT" VARCHAR2(240 BYTE),
  "LBANQUE_CHEQUE" VARCHAR2(40 BYTE),
  "LCOMMENTAIRE" VARCHAR2(480 BYTE)
);

ALTER TABLE "SCD_RETOUR" MODIFY (
  "LCOMMENTAIRE_AU_TRANSPORTEUR" VARCHAR2(240 BYTE),
  "LCOMMENTAIRE" VARCHAR2(240 BYTE)
);