ALTER TABLE DCSPP_BILL_ADDR MODIFY (   
    FIRST_NAME          varchar2(100),  
    LAST_NAME           varchar2(100),
    ADDRESS_1            varchar2(100),  
    ADDRESS_2            varchar2(100),
    ADDRESS_3            varchar2(100),
    POSTAL_CODE         varchar2(16),
    CITY                varchar2(100)
);


ALTER TABLE DCSPP_SHIP_ADDR MODIFY (   
    FIRST_NAME          varchar2(100),  
    LAST_NAME           varchar2(100),
    ADDRESS_1            varchar2(100),  
    ADDRESS_2            varchar2(100),
    ADDRESS_3            varchar2(100),
    POSTAL_CODE         varchar2(16),
    CITY                varchar2(100)
);

ALTER TABLE CASTO_ORDER ADD (
                TOTAL_DISCOUNT NUMBER (10,2) NULL,
                PROCESSING_FEES NUMBER (10,2) NULL,
                SHIPPING_FEES NUMBER (10,2) NULL,
                SHIPPING_DISCOUNT NUMBER (10,2) NULL,
                TOTAL_WEIGHT NUMBER (10,2) NULL
);

ALTER TABLE CASTO_COMMERCE_ITEM ADD DELIVERY_PERIOD NUMBER (4,0) NULL;

ALTER TABLE CASTO_ORDER ADD TOTAL_DISCOUNT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD PROCESSING_FEES NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD SHIPPING_FEES NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD SHIPPING_DISCOUNT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD TOTAL_WEIGHT NUMBER (10,2) NULL;
ALTER TABLE CASTO_ORDER ADD ITEMS_DISCOUNT NUMBER (10,2) NULL;

ALTER TABLE CASTO_COMMERCE_ITEM ADD DELIVERY_PERIOD NUMBER (4,0) NULL;
