ALTER TABLE CASTO_SKU DROP COLUMN CASTORAMA_PRICE_START_DATE;
ALTER TABLE CASTO_SKU DROP COLUMN CASTORAMA_PRICE_END_DATE;

ALTER TABLE CASTO_SKU MODIFY EAN VARCHAR2(260);

ALTER TABLE CASTO_SKU DROP COLUMN SHOW_M2_FIRST;
ALTER TABLE CASTO_SKU DROP COLUMN EMISSION_LEVEL;
ALTER TABLE CASTO_SKU DROP COLUMN SHOW_CARD_PRICE;



commit;
