CREATE TABLE IPH_CAT_DISPLAY_IMAGE (
    CATEGORY_ID                             VARCHAR2(40) NOT NULL REFERENCES DCS_CATEGORY(CATEGORY_ID),
    CAT_DISPLAY_IMAGE                  		VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),
	PRIMARY KEY (CATEGORY_ID));

CREATE TABLE IPHONE_AUG_AUX_IMAGE(
	AUGM_AUX_ID  							VARCHAR2(40) NOT NULL,
	DISPLAY_NAME 							VARCHAR2(100) NOT NULL,
	AUG_CAR_IMAGE_ID 						VARCHAR2(40) NOT NULL REFERENCES DCS_MEDIA(MEDIA_ID),
	AUG_TR_IMAGE_ID 						VARCHAR2(40) NOT NULL REFERENCES DCS_MEDIA(MEDIA_ID),
	CONSTRAINT IPHONE_AUG_AUX_IMAGE_P PRIMARY KEY (AUGM_AUX_ID)
);

CREATE TABLE IPHONE_VIDEO(
	IPHONE_VIDEO_ID  						VARCHAR2(40) NOT NULL,
	DISPLAY_NAME 							VARCHAR2(100) NOT NULL,
	SHORT_URL 								VARCHAR2(100) NOT NULL,
	LONG_URL 								VARCHAR2(250) NOT NULL,
	CONSTRAINT IPHONE_VIDEO_P PRIMARY KEY (IPHONE_VIDEO_ID)
);

CREATE TABLE IPHONE_SKU_AUG_IMAGES (
	SEQ_NUM	       							INTEGER	            NOT NULL,
	SKU_ID                             		VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU(SKU_ID),
	AUGM_AUX_ID                        		VARCHAR2(40)        NOT NULL REFERENCES IPHONE_AUG_AUX_IMAGE(AUGM_AUX_ID),
	PRIMARY KEY (SKU_ID, AUGM_AUX_ID)
);

COMMIT;