CREATE TABLE CAST_IPHONE_CATALOG (
	CATALOG_ID                              VARCHAR2(40)        NOT NULL REFERENCES DCS_CATALOG(CATALOG_ID),
	CATEGORY_ID                             VARCHAR2(40)        NULL,
	PRIMARY KEY (CATALOG_ID));

CREATE TABLE CAST_IPHONE_SKU_IMAGES (
    SKU_ID                                  VARCHAR2(40) NOT NULL REFERENCES DCS_SKU(SKU_ID),
    AUG_TRANSP_IMAGE_ID                     VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),
    AUG_CAROUSEL_IMAGE_ID                   VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID),  
	PRIMARY KEY (SKU_ID));

ALTER TABLE CAST_IPHONE_SKU_IMAGES ADD (AUG_RETINA_IMAGE_ID VARCHAR2(40) NULL REFERENCES DCS_MEDIA(MEDIA_ID));

CREATE TABLE CAST_STORE_GEOLOCATION (
	ID							VARCHAR2(40)		NOT NULL REFERENCES CASTO_MAGASIN(ID),
	LONGITUDE					NUMBER(12,7)		NULL,
	LATITUDE 					NUMBER(12,7)		NULL,	
	CONSTRAINT CAST_STORE_GEOLOCATION_P PRIMARY KEY (ID));



COMMIT;