
  CREATE TABLE "EMPLACEMENT_ILOT" 
   (	"CETAB" NUMBER(4,0) NOT NULL ENABLE, 
	"CILOT" NUMBER(4,0) NOT NULL ENABLE, 
	"CEMPLACEMENT" NUMBER(6,0) NOT NULL ENABLE, 
	"CESCLAVE" NUMBER(6,0) NOT NULL ENABLE, 
	"DMODIFICATION" DATE NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  CREATE TABLE "LOCALISATION_ILOT" 
   (	"CETAB" NUMBER(4,0) NOT NULL ENABLE, 
	"CILOT" NUMBER(4,0) NOT NULL ENABLE, 
	"CRITERE1" NUMBER(4,0) NOT NULL ENABLE, 
	"CRITERE2" NUMBER(4,0) NOT NULL ENABLE, 
	"CRITERE3" NUMBER(4,0), 
	"CRITERE4" NUMBER(4,0), 
	"CRITERE5" NUMBER(4,0), 
	"DCREATION" DATE NOT NULL ENABLE, 
	"TMODIFICATION" NUMBER(1,0), 
	"DMODIFICATION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  ALTER TABLE "LOCALISATION_ILOT"
    ADD CONSTRAINT "PK_LOCALISATION_ILOT" PRIMARY KEY ("CILOT", "CETAB");

  CREATE INDEX "EMPLACEMENT_ILOT_CESCLAVE" ON "EMPLACEMENT_ILOT" ("CESCLAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "EMPLACEMENT_ILOT_CETAB" ON "EMPLACEMENT_ILOT" ("CETAB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
commit;