CREATE TABLE CASTO_COULEUR (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID       								VARCHAR2(32)  		NOT NULL,
  	COULEUR  								VARCHAR2(32)   		NOT NULL,
  	NOM      								VARCHAR2(100)  		NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE INDEX CASTO_COULEUR_WORKSPACE_ID on CASTO_COULEUR (WORKSPACE_ID);
CREATE INDEX CASTO_COULEUR_CHECKIN_DATE on CASTO_COULEUR (CHECKIN_DATE);

CREATE TABLE CASTO_SKU (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	CODEARTICLE 							INTEGER				NULL, 
	MODELE 									VARCHAR2(45)		NULL, 
	MARQUECOMMERCIAL 						VARCHAR2(100)		NULL, 
	RESTRICTIONSUSAGE 						VARCHAR2(300)		NULL, 
	MENTIONSLEGALESOBLIGATOIRES 			VARCHAR2(1200)		NULL, 
	CONTRAINTESUTILISATION 					VARCHAR2(1200), 
	PLUSDUPRODUIT 							VARCHAR2(1200)		NULL, 
	LIBELLECLIENTCOURT 						VARCHAR2(2200)		NULL, 
	GENERALEMENTLIVREENHEURES 				NUMBER(2, 0)		NULL, 
	LIVRAISONDIRECTEFOURNISSEUR 			NUMBER(1, 0), 
	CHAMPSDYNAMIQUE 						NUMBER(1, 0)		NULL, 
	ENVENTE 								NUMBER(1, 0)		NULL, 
	HORSNORMES 								NUMBER(1, 0)		NULL, 
	CODEFOURNISSEUR 						INTEGER				NULL, 
	NOMFOURNISSEUR 							VARCHAR2(45)		NULL, 
	POIDSUV 								INTEGER				NULL, 
	CODERAYON 								INTEGER				NULL, 
	CODEFAMILLE 							INTEGER				NULL, 
	CODEMODULE 								INTEGER				NULL,	
	TAUXTVA 								NUMBER(12, 2)		NULL, 
	PRIXVENTETTCFRANCS 						NUMBER(12, 2)		NULL, 
	PRIXVENTETTCEURO 						NUMBER(12, 2)		NULL, 
	PRIXVENTEHTFRANCS 						NUMBER(12, 2)		NULL, 
	PRIXVENTEHTEURO 						NUMBER(12, 2)		NULL, 
	HAUTEURUV 								INTEGER				NULL, 
	LARGEURUV								INTEGER				NULL, 
	PROFONDEURUV 							INTEGER				NULL, 
	DATECREATIONCODEARTICLE 				DATE				NULL, 
	DATEFINVIE 								DATE				NULL, 
	FRAISEXCEPTIONNEL 						NUMBER(12, 2)		NULL, 
	GARANTIE 								VARCHAR2(70)		NULL, 
	LIBELLEDESCRIPTIFARTICLE 				VARCHAR2(300)		NULL, 
	LIBELLECLIENTLONG 						VARCHAR2(1200)		NULL, 
	UNITEUV 								VARCHAR2(30)		NULL, 
	NORMESTEXT 								VARCHAR2(400)		NULL, 
	CADEAU 									NUMBER(1, 0)		NULL, 
	VENTEENMAGASINSEULEMENT 				NUMBER(1, 0)		NULL, 
	COULEUR 								VARCHAR2(32)		NULL, 
	COEFFICIENTDESATISFACTION 				NUMBER(10, 2)		NULL, 
	TYPE_DE_TRANSPORT 						INTEGER				NULL,  --unused
	EXONERATION_PFE							NUMBER(1, 0)		NULL, 
	LIBELLEPROMOTIONNEL 					VARCHAR2(80)		NULL, 
	URLGRANDPICTOREMISE 					VARCHAR2(80)		NULL, 
	URLPETITPICTOREMISE 					VARCHAR2(80)		NULL, 
	DATEDEBUTFONCTIONNELLE 					DATE				NULL, 
	DATEFINFONCTIONNELLE 					DATE				NULL, 
	DATEDEBUTAFFICHAGE 						DATE				NULL, 
	UNIQUEMENTSURLESITE 					NUMBER(1, 0)		NULL, 
	LISTPRICEXLS 							NUMBER(19, 7)		NULL, 
	TYPEEXPEDITION							NUMBER(8, 0)		NULL, 
	TYPEARTICLE 							NUMBER(8, 0)		NULL, 
	TRANSPORTEUR 							VARCHAR2(40)		NULL, 
	EXONERATIONPFT 							NUMBER(1, 0)		NULL, 
	RETRAITMOMENTANEDATEDEBUT 				DATE				NULL, 
	RETRAITMOMENTANEDATEFIN 				DATE				NULL, 
	RETRAITMOMENTANEMOTIFSCODIFIES 			NUMBER(8, 0)		NULL, 
	RETRAITMOMENTANEUTILISATEUR 			VARCHAR2(40)		NULL, 
	DELAIEXPEDITIONBO 						NUMBER(8, 0)		NULL, --unused
	ECOTAXEENEURO							NUMBER(14, 2)		NULL, 
	VIDEO_URL 								VARCHAR2(50)		NULL, 
	BAROMETRE 								NUMBER				NULL, 
	CHAPO_CONTENU 							VARCHAR2(100)		NULL, 
	CHAPO_STYLE 							NUMBER				NULL, 
	PROMOTIONSEXCLUES 						NUMBER(1, 0)		NULL, 
	PRIXDETAIL 								NUMBER(12, 0)		NULL, 
	PRIXTYPEDETAIL 							NUMBER				NULL, 
	FIABILITESTOCK 							NUMBER(3, 0)		NULL, 
	CACHESKUCOMPTEUR 						NUMBER(11, 2)		NULL, 
	CODENEWMODULE 							VARCHAR2(100)		NULL, 
	SOUMISAD3E 								NUMBER(1, 0)		NULL, 
	PRMP 									NUMBER(12, 2)		NULL, 
	DELAIAPPROFOURNISSEUR 					NUMBER(12, 2)		NULL, 
	PROMOTIONCARTEATOUT 					NUMBER(1, 0)		NULL, 
	PURCENTPROMOCARTEATOUT 					INTEGER				NULL, 
	ISPURCENT 								INTEGER				NULL, 
	QUANTITE_LIMITEE 						NUMBER(1, 0)		NULL, 
	THEME_SKU 								VARCHAR2(70)		NULL, 
	URL_PAGE 								VARCHAR2(260)		NULL, 
	CONDITIONSPARTICULIERES 				NUMBER				NULL,
	EXCLUSIONLIVRAISONCORSE 				NUMBER				NULL, 
	SOMMEFORFAITAIRE 						NUMBER(19, 7)		NULL, 
	FLASH_PRODUIT 							VARCHAR2(100)		NULL, 
	FLASH_ZOOM 								VARCHAR2(100)		NULL, 
	DATE_DEB_DESTOCK 						DATE				NULL, 
	DATE_FIN_DESTOCK 						DATE				NULL, 
	DATE_INIT_DESTOCK 						DATE				NULL, 
	VAL_STOCK_DESTOCK 						NUMBER(6, 0)		NULL, 
	CUV 									VARCHAR2(2)			NULL, 
	CUP 									VARCHAR2(2)			NULL, 
	PUPUV 									NUMBER(10, 6)		NULL,
	PRIX_REF 								NUMBER(12, 2)		NULL,
	PRIX_SOLDE								NUMBER(12, 2)		NULL,
	F_SOLDE									NUMBER(1, 0)		NULL,	
	DATE_FIN_SOLDE							DATE				NULL,
	PRIMARY KEY (SKU_ID, ASSET_VERSION));

CREATE TABLE CASTO_SKU_PICTO (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	SEQ_NUM 								INTEGER	 			NOT NULL, 
	URL_PICTO 								VARCHAR2(100)		NULL,
	PRIMARY KEY (SKU_ID, SEQ_NUM, ASSET_VERSION)); 

CREATE TABLE CASTO_SKU_RELATED (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SEC_ASSET_VERSION	                    NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	AUX_ID 									VARCHAR2(40) 		NOT NULL,
	PRIMARY KEY (SKU_ID, AUX_ID, ASSET_VERSION, SEC_ASSET_VERSION));

CREATE TABLE CASTO_SKU_CROSS_SELLING (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	CROSS_ID 								VARCHAR2(40) 		NOT NULL, 
	SKU_ID 									VARCHAR2(40)		NULL, 
	PRODUCT_ID 								VARCHAR2(40)		NULL,
	PRIMARY KEY (CROSS_ID, ASSET_VERSION));

CREATE INDEX CASTO_SKCRSSELL_WORKSPACE_ID on CASTO_SKU_CROSS_SELLING (WORKSPACE_ID);
CREATE INDEX CASTO_SKCRSSELL_CHECKIN_DATE on CASTO_SKU_CROSS_SELLING (CHECKIN_DATE);

CREATE TABLE CASTO_SKU_CROSS_SELLING_ASSOC (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40)		NOT NULL, 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	CROSS_ID 								VARCHAR2(40)		NULL,
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM, ASSET_VERSION));	
	
CREATE TABLE CASTO_SKU_IK_CS_ASSOC (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40)		NOT NULL, 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	CROSS_ID 								VARCHAR2(40)		NULL,
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM, ASSET_VERSION));	

CREATE TABLE CASTO_SKU_ATTR_VALUE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ATTRIBUTE_ID 							VARCHAR2(40)		NOT NULL, 
	ATTRIBUTE_NAME 							VARCHAR2(42)		NULL, 
	DISPLAYNAME 							VARCHAR2(50)		NULL, 
	VALUEINTEGER							INTEGER				NULL, 
	VALUESTRING 							VARCHAR2(255)		NULL,	 
	VALUEFLOAT 								NUMBER(12, 2)		NULL, 
	VALUEDATE 								DATE				NULL, 
	VALUEBOOLEAN 							NUMBER(1, 0)		NULL, 
	UNIT 									VARCHAR2(10)		NULL, 
	TYPE 									INTEGER				NULL,
	PRIMARY KEY (ATTRIBUTE_ID, ASSET_VERSION)); 

CREATE INDEX CASTO_SKATTRVAL_WORKSPACE_ID on CASTO_SKU_ATTR_VALUE (WORKSPACE_ID);
CREATE INDEX CASTO_SKATTRVAL_CHECKIN_DATE on CASTO_SKU_ATTR_VALUE (CHECKIN_DATE);

CREATE TABLE CASTO_SKU_ATTR (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	ATTRIBUTE_ID 							VARCHAR2(40)		NULL,
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM, ASSET_VERSION));

CREATE INDEX CASTO_ATTR_SKUID_IDX ON CASTO_SKU_ATTR (ATTRIBUTE_ID DESC);

CREATE TABLE CASTO_NORMES (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	NORMES_ID 								VARCHAR2(40) 		NOT NULL, 
	URLPICTOGRAMME 							VARCHAR2(254)		NULL, 
	URLPAGE 								VARCHAR2(254)		NULL, 
	DESCRIPTION 							LONG				NULL, 
	NOMCOURT 								VARCHAR2(20)		NULL,
	PRIMARY KEY (NORMES_ID, ASSET_VERSION));

CREATE INDEX CASTO_NORMES_WORKSPACE_ID on CASTO_NORMES (WORKSPACE_ID);
CREATE INDEX CASTO_NORMES_CHECKIN_DATE on CASTO_NORMES (CHECKIN_DATE);

CREATE TABLE CASTO_SKU_NORMES (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	SKU_ID 									VARCHAR2(40) 		 NOT NULL, 
	SEQUENCE_NUM 							INTEGER	 			 NOT NULL, 
	NORMES_ID 								VARCHAR2(40) 		 NOT NULL,
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM, ASSET_VERSION));

CREATE TABLE CASTO_SKU_SERVICE_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	ID_COUPLE 								VARCHAR2(40)		NOT NULL,	
	PRIMARY KEY (SKU_ID, ID_COUPLE, ASSET_VERSION));

CREATE TABLE CASTO_SKU_MEDIA (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	QUAL_ID 								VARCHAR2(1) 		NOT NULL, 
	MEDIA_ID 								VARCHAR2(40) 		NOT NULL,
	PRIMARY KEY (MEDIA_ID, QUAL_ID, ASSET_VERSION));


CREATE TABLE CASTO_AFFINAGE_QUESTION (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ID 										VARCHAR2(40) 		NOT NULL, 
	LIBELLE 								VARCHAR2(500)		NULL, 
	CONTENTGROUP 							VARCHAR2(500)		NULL, 
	MULTIVALUE 								NUMBER 				DEFAULT 0	NOT NULL, 
	MEDIA_ID VARCHAR2(40) 					NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE INDEX CASTO_AFFIN_QUEST_WRKSPC_ID on CASTO_AFFINAGE_QUESTION (WORKSPACE_ID);
CREATE INDEX CASTO_AFFIN_QUEST_CHCKIN_DT on CASTO_AFFINAGE_QUESTION (CHECKIN_DATE);

CREATE TABLE CASTO_AFFINAGE_REPONSE ( 
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID           							VARCHAR2(32)        NOT NULL,
  	LIBELLE       							VARCHAR2(32)        NOT NULL,
  	CONTENTGROUP  							VARCHAR2(32),
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE INDEX CASTO_AFFIN_REP_WRKSPC_ID on CASTO_AFFINAGE_REPONSE (WORKSPACE_ID);
CREATE INDEX CASTO_AFFIN_REP_CHCKIN_DT on CASTO_AFFINAGE_REPONSE (CHECKIN_DATE);

CREATE TABLE CASTO_AFFINAGE_QUEST_REP (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
  	QUESTION_ID   							VARCHAR2(32)        NOT NULL,
  	SEQUENCE_NUM  							INTEGER             NOT NULL,
  	REPONSE_ID    							VARCHAR2(32)		NULL,
	PRIMARY KEY (QUESTION_ID, SEQUENCE_NUM, ASSET_VERSION));


CREATE TABLE CASTO_DATA_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ID_COUPLE 								VARCHAR2(40) 		NOT NULL, 
	DELAI_APPRO_FOURNISSEUR 				NUMBER(12, 2)		NULL, 
	ECO_TAXE 								NUMBER(19, 7)		NULL, 
	SOUMISAD3E 								NUMBER(1, 0)		NULL, 
	COEFFICIENTDESATISFACTION 				NUMBER(10, 2)		NULL, 
	PRMP 									NUMBER(10, 2)		NULL, 
	PROMCORDRE 								NUMBER(4, 0)		NULL, 
	PROMFNAT 								NUMBER(2, 0)		NULL, 
	PRIXLIVRE 								NUMBER(1, 0)		NULL, 
	DDEBPROMO 								DATE				NULL, 
	DFINPROMO 								DATE				NULL,
	PRODUITDETENU							NUMBER(1, 0)		NULL, 
	PRIXVENTETTCEURO 						NUMBER(10, 2)		NULL, 
	PRIXVENTEHTEURO 						NUMBER(10, 2)		NULL,
	PRIMARY KEY (ID_COUPLE, ASSET_VERSION));

CREATE INDEX CASTO_DATA_MAGASIN_WRKSPC_ID on CASTO_DATA_MAGASIN (WORKSPACE_ID);
CREATE INDEX CASTO_DATA_MAGASIN_CHCKIN_DT on CASTO_DATA_MAGASIN (CHECKIN_DATE);

CREATE TABLE CASTO_SKU_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	SKU_ID 									VARCHAR2(40)	NOT	NULL, 
	ID_MAGASIN 								VARCHAR2(40)	NOT	NULL, 
	ID_COUPLE 								VARCHAR2(40)	NOT	NULL,
	PRIMARY KEY (ASSET_VERSION, SKU_ID, ID_MAGASIN, ID_COUPLE));

CREATE TABLE CASTO_PRODUCT (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	PRODUCT_ID								VARCHAR2(40) 		NOT NULL, 
	BOUTIQUEMARQUES							NUMBER(1, 0)		NULL, 
	PRODUCT_TETEDEGONDOLE					VARCHAR2(40)		NULL, 
	PRODUCT_FIXEDRELATEDPRODUCTUP			VARCHAR2(40)		NULL, 
	COULEUR									VARCHAR2(32)		NULL, 
	AFFICHAGE_ARTICLECOMPARABLE				NUMBER(1, 0)		NULL,	 
	MARQUECOMMERCIAL						VARCHAR2(100)		NULL, 
	URL_FICHE_TECHNIQUE						VARCHAR2(50)		NULL, 
	URL_MODE_EMPLOI 						VARCHAR2(50)		NULL, 
	CHAPO_CONTENU							VARCHAR2(100)		NULL, 
	CHAPO_STYLE								NUMBER				NULL, 
	NATURE_TETE_GONDOLE						NUMBER(1, 0)		NULL, 
	TYPE_AFFICHAGE_PROMO					NUMBER(1, 0)		NULL, 
	VIDEO_URL								VARCHAR2(50)		NULL, 
	URL_PAGE								VARCHAR2(260)		NULL,
	PRIMARY KEY (PRODUCT_ID, ASSET_VERSION));

CREATE TABLE CASTO_PRODUCT_QUESTION (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	PRODUCT_ID								VARCHAR2(40) 		NOT NULL, 
	SEQ 									INTEGER	 			NOT NULL, 
	QUESTION_ID								VARCHAR2(40) 		NOT NULL,
	PRIMARY KEY (PRODUCT_ID, SEQ, ASSET_VERSION)); 

CREATE TABLE CASTO_PRODUCT_AFFINAGE (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	PRODUCT_ID 								VARCHAR2(40) 		NOT NULL,
	AFFINAGE 								INTEGER				NULL,
	PRIMARY KEY (PRODUCT_ID, ASSET_VERSION)); 

CREATE TABLE CASTO_PRODUCT_LISTE_MULTISKU (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	PRODUCT_ID								VARCHAR2(40)  NOT NULL, 
	LIBELLE_LISTE_ID						VARCHAR2(40)  NULL,
	CONSTRAINT CASTO_PRODUCT_LISTE_MULTI_PK PRIMARY KEY (PRODUCT_ID, ASSET_VERSION));  

CREATE TABLE CASTO_IK_CATEGORY_TYPE (
	ASSET_VERSION							NUMBER(19,0) 		NOT NULL ENABLE, 
	WORKSPACE_ID 							VARCHAR2(40 BYTE)	NOT NULL ENABLE, 
	BRANCH_ID								VARCHAR2(40 BYTE)	NOT NULL ENABLE, 
	IS_HEAD									NUMBER(1,0) 		NOT NULL ENABLE, 
	VERSION_DELETED							NUMBER(1,0)			NOT NULL ENABLE, 
	VERSION_EDITABLE						NUMBER(1,0) 		NOT NULL ENABLE, 
	PRED_VERSION							NUMBER(19,0), 
	CHECKIN_DATE 							DATE,
	TYPE_NAME								VARCHAR2(255)		NOT NULL,
	PRIMARY KEY (TYPE_NAME, ASSET_VERSION));

CREATE TABLE CASTO_CATEGORY (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	CATEGORY_ID                             VARCHAR2(40)        NOT NULL,
	DROPDOWNTEMPLATE                        VARCHAR2(100)       NULL,
    PIVOT	                                NUMBER(1,0)	        NULL,
	PROMOTEMPLATE                           VARCHAR2(100)       NULL,
    PRODUCTS_COUNT	                        INTEGER		        NULL,
  	BOUTIQUEMARQUES             			NUMBER(1),
  	REDACTIONNELFAMILLEMARQUE1  			VARCHAR2(255),
  	TITREBOUTIQUEMARQUE         			VARCHAR2(254),
	COULEUR                     			VARCHAR2(32),
	HEADER_PAGE_LISTE           			NUMBER(1),
	TYPE_TETE_GONDOLE          				NUMBER(1),
	BOUTIQUE_EVENT             				NUMBER(1)         	DEFAULT 0,
	IMAGE_URL                   			VARCHAR2(255),
	URL_EDITO                   			VARCHAR2(255),
	DESCRIPTIF_CATEGORIE        			VARCHAR2(255),
	URL_INSPIRATION             			VARCHAR2(255),
	URL_AIDE_AU_CHOIX           			VARCHAR2(255),
	ACTIVATION_COMPARATEUR      			NUMBER(1)        	DEFAULT 1,
	REDACTIONNELFAMILLEMARQUE3  			VARCHAR2(100),
	STYLECATEGORIE              			NUMBER(2)         	DEFAULT 0,
	REDACTIONNELFAMILLEMARQUE2  			NUMBER(2)         	DEFAULT 0,
	TITRE_REFERENCEMENT         			VARCHAR2(200),
	DESTOCKAGE                  			INTEGER,
	BONNES_AFFAIRES             			NUMBER(1,0),
	FOOTER                      			CLOB,
	COEFFIABILITE              				NUMBER(14,2),
	IK_CATEGORY_TYPE						VARCHAR2(255),
	IK_CATEGORY_TYPE_NAV 					NUMBER(2) 			DEFAULT 0,
	URL_PAGE                    			VARCHAR2(260),
	NE_PAS_AFFICHER             			INTEGER,
CONSTRAINT CASTO_CATEGORY_P PRIMARY KEY (CATEGORY_ID,ASSET_VERSION));

CREATE TABLE CASTO_INSPI (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
  	INSPI_ID  								VARCHAR2(100)	              NOT NULL,
	PRIMARY KEY (INSPI_ID, ASSET_VERSION));


CREATE TABLE CASTO_CATEGORY_ESPRIT(
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
  	ESPRIT_ID  								VARCHAR2(100)	              NOT NULL,
  	SEQ        								INTEGER                       NOT NULL,
  	INSPI_ID   								VARCHAR2(100)	              NOT NULL,
	PRIMARY KEY  (ESPRIT_ID, INSPI_ID, ASSET_VERSION));

CREATE TABLE CASTO_INSPI_NUANCIER(
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
  	INSPI_ID  								VARCHAR2(100 )	              NOT NULL,
  	SEQ       								INTEGER                       NOT NULL,
  	ID        								VARCHAR2(100)		          NOT NULL,
	PRIMARY KEY  (INSPI_ID, ID, ASSET_VERSION));

CREATE TABLE CASTO_NUANCIER(
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID            							VARCHAR2(100)	    NOT NULL,
  	LIBELLE       							VARCHAR2(255)	    NOT NULL,
  	CODE_COULEUR  							VARCHAR2(500)	    NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE INDEX CASTO_NUANCIER_WRKSPC_ID on CASTO_NUANCIER (WORKSPACE_ID);
CREATE INDEX CASTO_NUANCIER_CHCKIN_DT on CASTO_NUANCIER (CHECKIN_DATE);

CREATE TABLE CASTO_CATEGORY_INSPI(
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	CATEGORY_ID  							VARCHAR2(100)   	NOT NULL,
  	SEQ          							INTEGER             NOT NULL,
  	INSPI_ID     							VARCHAR2(100)     	NOT NULL,
	PRIMARY KEY (CATEGORY_ID, INSPI_ID, ASSET_VERSION));

CREATE TABLE CASTO_CATEGORY_SEQUENCE(
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	CAT_ID   								VARCHAR2(40)        NOT NULL,
  	SEQ_NUM  								INTEGER             NOT NULL,
  	SEQ_ID   								VARCHAR2(50),
	PRIMARY KEY (CAT_ID, SEQ_NUM, ASSET_VERSION));

CREATE TABLE CASTO_CATEGORY_BOUTIQUE_MAG(
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	ID_CATEGORY  							VARCHAR2(40)        NOT NULL,
  	ID_MAGASIN   							VARCHAR2(40)        NOT NULL,
	PRIMARY KEY (ID_CATEGORY, ID_MAGASIN, ASSET_VERSION));

CREATE TABLE CASTO_THEMES_NORMES (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	THEME_ID     							VARCHAR2(40)   		NOT NULL,
 	NAME         							VARCHAR2(254)		NULL,
  	DESCRIPTION  							LONG				NULL,
	PRIMARY KEY (THEME_ID, ASSET_VERSION));

CREATE INDEX CASTO_THMSNRMS_WRKSPC_ID on CASTO_THEMES_NORMES (WORKSPACE_ID);
CREATE INDEX CASTO_THMSNRMS_CHCKIN_DT on CASTO_THEMES_NORMES (CHECKIN_DATE);

CREATE TABLE CASTO_THEMES_NORMES_ASSOC (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	THEME_ID      							VARCHAR2(40)        NOT NULL,
  	SEQUENCE_NUM  							INTEGER             NOT NULL,
  	NORMES_ID     							VARCHAR2(40)        NOT NULL,
	PRIMARY KEY (THEME_ID, SEQUENCE_NUM, ASSET_VERSION));

CREATE TABLE CASTO_MARQUE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	MARQUE_ID            					VARCHAR2(40)        NOT NULL,
  	NOMMARQUE           					VARCHAR2(254)       NOT NULL,
  	DESCRIPTION          					LONG,
  	LOGOMARQUE           					VARCHAR2(40),
  	PREMIER_PRIX         					VARCHAR2(20),
  	QUALITE_PRIX         					VARCHAR2(20),
  	SELECTION_EXCLUSIVE  					VARCHAR2(20),
  	GRANDE_MARQUE        					VARCHAR2(20),
	URL 									VARCHAR2(254),
	PRIMARY KEY (MARQUE_ID, ASSET_VERSION));

CREATE INDEX CASTO_MARQUE_WRKSPC_ID on CASTO_MARQUE (WORKSPACE_ID);
CREATE INDEX CASTO_MARQUE_CHCKIN_DT on CASTO_MARQUE (CHECKIN_DATE);

CREATE TABLE CASTO_CODES_UNITE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	CODE_UNITE            					VARCHAR2(2),
  	DESIGNATION           					VARCHAR2(50),
  	FLAG_AFFICHAGE_UP     					VARCHAR2(1),
  	LIBELLE_AFFICHAGE_UP  					VARCHAR2(10),
	PRIMARY KEY (ASSET_VERSION, CODE_UNITE));

CREATE INDEX CASTO_CODES_UNITE_WRKSPC_ID on CASTO_CODES_UNITE (WORKSPACE_ID);
CREATE INDEX CASTO_CODES_UNITE_CHCKIN_DT on CASTO_CODES_UNITE (CHECKIN_DATE);

--------------------------- EPAM -----------------------------------------

CREATE TABLE CAST_SKU (
  asset_version	number(19)	not null,
  SKU_ID                    VARCHAR2(40)        NOT NULL,
  TEST                      VARCHAR2(40),
  MESSAGE_INFORMATION	    VARCHAR2(500)
,constraint CAST_SKU_p primary key (sku_id,asset_version));

CREATE TABLE CAST_CATEGORY (
	ASSET_VERSION	                        NUMBER(19)	  NOT NULL,
	CATEGORY_ID                             VARCHAR2(40)  NOT NULL,
	DROPDOWNTEMPLATE                        VARCHAR2(100) NULL,
    PIVOT	                                NUMBER(1,0)	  NULL,
	FEATUREDPRODUCT	                        VARCHAR2(60)  NULL,
	PROMOTEMPLATE                           VARCHAR2(100) NULL,
    PRODUCTS_COUNT	                  	    integer       NULL,
	META_KEYWORDS_PATTERN					VARCHAR2(300)	NULL,	
	META_DESCRIPTION_PATTERN				VARCHAR2(300)	NULL,
	PAGE_TITLE_PATTERN				 		VARCHAR2(300)	NULL,
    INFO_TEXT                               VARCHAR2(500)   NULL,
    COMMERCE_TEXT                           VARCHAR2(500)   NULL,
CONSTRAINT CAST_CATEGORY_P PRIMARY KEY (CATEGORY_ID,ASSET_VERSION));

CREATE TABLE CAST_CATALOG_CATEGORY (
	ASSET_VERSION							NUMBER(19)	  NOT NULL,
	SEQUENCE_NUM 							INTEGER       NOT NULL,
	CATEGORY_ID 							VARCHAR2(40)  NOT NULL,
	CATALOG_ID                      		VARCHAR2(40)  NOT NULL
,CONSTRAINT CAST_CATALOG_CATEGORY_P PRIMARY KEY (CATEGORY_ID,CATALOG_ID,ASSET_VERSION,SEQUENCE_NUM));

CREATE TABLE CAST_TEMPLATE_INFORMATION (
	ASSET_VERSION	                        NUMBER(19)	        NOT NULL,
	PROMO_TEMPLATE_ID                       VARCHAR2(40)        NOT NULL,
	PROMO_INFORMATION_ID                    VARCHAR2(40)        NOT NULL,
	PROMO_KEY                               INTEGER             NOT NULL,
	PRIMARY KEY (PROMO_TEMPLATE_ID, PROMO_INFORMATION_ID, PROMO_KEY, ASSET_VERSION));

CREATE TABLE CAST_PROMO_INFORMATION (
	asset_version							number(19)		not null,
	workspace_id							varchar2(40)	not null,
	branch_id								varchar2(40)	not null,
	is_head									number(1)		not null,
	version_deleted							number(1)		not null,
	version_editable						number(1)		not null,
	pred_version							number(19)		null,
	checkin_date							date			null,
	PROMO_INFORMATION_ID 					VARCHAR2(40) 	NOT NULL,
	IMAGE 									VARCHAR2(40) 	NULL,
	FLASH                                   VARCHAR2(40)    NULL,
	DESCRIPTION 							VARCHAR2(400) 	NULL,
	URL 									VARCHAR2(255) 	NULL,
	VIDEOURL                                VARCHAR2(500)   NULL,
	TITLE									VARCHAR2(100)	NULL,
	DOCUMENT_ID								VARCHAR2(40)    NULL,
	PRODUCT_ID 								VARCHAR2(40)	NULL,
	CATEGORY_ID								VARCHAR2(40) 	NULL
,constraint CAST_PROMO_INFORMATION_p primary key (PROMO_INFORMATION_ID,asset_version));

CREATE TABLE CAST_PROMO_TEMPLATE (
	ASSET_VERSION							NUMBER(19)	 NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) NOT NULL,
	BRANCH_ID								VARCHAR2(40) NOT NULL,
	IS_HEAD									NUMBER(1)	 NOT NULL,
	VERSION_DELETED							NUMBER(1)	 NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 NOT NULL,
	PRED_VERSION							NUMBER(19)	 NULL,
	CHECKIN_DATE							DATE	     NULL,
	PROMO_TEMPLATE_ID                       VARCHAR2(40) NOT NULL,
	LAYOUTTYPE                              INTEGER      NOT NULL
,CONSTRAINT CAST_PROMO_TEMPLATE_P PRIMARY KEY (PROMO_TEMPLATE_ID,ASSET_VERSION));

CREATE TABLE CAST_GROUPED_PRODUCT (
	ASSET_VERSION							NUMBER(19)	 NOT NULL,
	GROUPED_PRODUCT_ID                      VARCHAR2(40) NOT NULL,
	GROUPINGTYPE 							INTEGER      NOT NULL
,constraint CAST_GROUPED_PRODUCT_p primary key (GROUPED_PRODUCT_ID,ASSET_VERSION));

CREATE TABLE CAST_SKU_LINK (
	ASSET_VERSION							NUMBER(19)	 NOT NULL,
    SKU_LINK_ID                             VARCHAR2(40) NOT NULL,
    TABNAME									VARCHAR2(60) NULL
,constraint CAST_SKU_LINK_p primary key (SKU_LINK_ID,ASSET_VERSION));

CREATE TABLE CAST_SKU_PACKS (
	ASSET_VERSION							NUMBER(19)	 NOT NULL,
	SKU_ID                                  VARCHAR2(40) NOT NULL,
	PACKS_ID                                VARCHAR2(40) NOT NULL 
,constraint CAST_SKU_PACKS_p primary key (SKU_ID,PACKS_ID,ASSET_VERSION));

CREATE TABLE CAST_DOCUMENT (
    ASSET_VERSION							NUMBER(19)	   NOT NULL,
	WORKSPACE_ID							VARCHAR2(40)   NOT NULL,
	BRANCH_ID								VARCHAR2(40)   NOT NULL,
	IS_HEAD									NUMBER(1)	   NOT NULL,
	VERSION_DELETED							NUMBER(1)	   NOT NULL,
	VERSION_EDITABLE						NUMBER(1)	   NOT NULL,
	PRED_VERSION							NUMBER(19)	   NULL,
	CHECKIN_DATE							DATE	       NULL,
    DOCUMENT_ID								VARCHAR2(40)   NOT NULL,
	DOCUMENT_TYPE 							INTEGER	       NULL,
	TITLE									VARCHAR2(254)  NULL,
	IMAGE									VARCHAR2(40)   NULL,
	DESCRIPTION								VARCHAR2(2048) NULL,
	RELATIVE_URL							VARCHAR2(2048) NULL,
	RATING                                  NUMBER(19,3)	   NULL,
	TEMPLATE_ID								VARCHAR2(40)   NULL
,CONSTRAINT CAST_DOCUMENT_P PRIMARY KEY (DOCUMENT_ID,ASSET_VERSION));

CREATE TABLE CAST_CAT_DOCUMENT (
	SEC_ASSET_VERSION                       NUMBER(19)          NOT NULL,    
	ASSET_VERSION                           NUMBER(19)          NOT NULL,
	CATEGORY_ID 							VARCHAR2(40)    NOT NULL,
	SEQUENCE_NUM	       					INTEGER	        NOT NULL,
	DOCUMENT_ID 							VARCHAR2(40)    NOT NULL,	
CONSTRAINT CAST_CAT_DOCUMENT_P PRIMARY KEY(CATEGORY_ID, SEQUENCE_NUM, ASSET_VERSION,  SEC_ASSET_VERSION));

CREATE TABLE CAST_DOC_KEYWRDS (
	ASSET_VERSION                           NUMBER(19)          NOT NULL,
	ID 										VARCHAR2(40) 		NOT NULL ,
	SEQ_NUM 								INTEGER 			NOT NULL,
	KEYWORDS 								VARCHAR2(254) 		NULL,
	PRIMARY KEY(ID, SEQ_NUM, ASSET_VERSION));

CREATE TABLE CAST_PRODUCT (
    ASSET_VERSION	                        NUMBER(19)	    NOT NULL,
	PRODUCT_ID	                            VARCHAR2(40)	NOT NULL,
	RATING                                  NUMBER(19,3)		NULL,	
	PRODUCT_BENEFIT                         VARCHAR2(80)	NULL,
	PRODUCT_PROMO_DESCRIPTION               VARCHAR2(80)	NULL,
	PROMO_BACKGROUND_COLOR					VARCHAR2(40)	NULL,
	PROMO_FONT_COLOR					 	VARCHAR2(40)	NULL,
	PROMO_START_DATE					 	DATE           NULL,
	PROMO_EXPIRATION_DATE					DATE           NULL,
	META_KEYWORDS_PATTERN					VARCHAR2(300)	NULL,	
	META_DESCRIPTION_PATTERN				VARCHAR2(300)	NULL,
	PAGE_TITLE_PATTERN				 		VARCHAR2(300)	NULL,
	SHOW_BRAND_LINK_PDP						NUMBER(1, 0)	NULL,
CONSTRAINT CAST_PRODUCT_P PRIMARY KEY (PRODUCT_ID,ASSET_VERSION));

CREATE TABLE cast_style (
	asset_version NUMBER(19) NOT NULL,
	workspace_id VARCHAR2(40) NOT NULL,
	branch_id VARCHAR2(40) NOT NULL,
	is_head NUMBER(1) NOT NULL,
	version_deleted NUMBER(1) NOT NULL,
	version_editable NUMBER(1) NOT NULL,
	pred_version NUMBER(19) NULL,
	checkin_date DATE NULL,
    style_id VARCHAR2 (40) NOT NULL,
    color VARCHAR2 (7) DEFAULT '#000000',
    foreground VARCHAR2 (7) DEFAULT '#FFFFFF',
    dropdown_color VARCHAR2 (7),
    font_name VARCHAR2 (30),
    font_size VARCHAR2 (5),
    font_weight NUMBER DEFAULT 0 NOT NULL,	
	tab_style VARCHAR2 (30),
	bg_style VARCHAR2 (30),
	link_style VARCHAR2 (30),
	facet_style VARCHAR2 (30),
	breadcrumbs_style VARCHAR2 (30),
	product_promo_style VARCHAR2 (30),
	paging_style VARCHAR2 (30),
	cloud_style VARCHAR2 (30),
	right_menu_style VARCHAR2 (30),
	list_style VARCHAR2 (30),
	border_style  VARCHAR2 (30),
    CONSTRAINT cast_style_pk PRIMARY KEY (style_id, asset_version)
);
CREATE INDEX cast_style_wsx ON cast_style (workspace_id);
CREATE INDEX cast_style_cix ON cast_style (checkin_date);


CREATE TABLE cast_category_style (
	asset_version NUMBER(19) NOT NULL,	
    category_id VARCHAR2 (40) NOT NULL,
    style_id VARCHAR2 (40) NOT NULL,
    CONSTRAINT cast_category_style_pk PRIMARY KEY (category_id, asset_version)
);


CREATE TABLE CAST_SKU_IMAGES (
	ASSET_VERSION	                        NUMBER(19)   NOT NULL,
    SKU_ID                                  VARCHAR2(40) NOT NULL,
    MINIATURE_IMAGE_ID                      VARCHAR2(40) NULL,
    CAROUSEL_IMAGE_ID                       VARCHAR2(40) NULL,  
	SUPPORTING_IMAGE_ID                     VARCHAR2(40) NULL,
	COMPARATOR_IMAGE_ID						VARCHAR2(40) NULL,
	PRIMARY KEY (SKU_ID, ASSET_VERSION)); 


CREATE TABLE CASTO_GESTPROMO_ACTIONCO (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ACTIONCO_ID 							VARCHAR2(50) 		NOT NULL, 
	ACTIONCO_NOM 							VARCHAR2(50), 
	ACTIONCO_DESCRIPTION 					VARCHAR2(100), 
	NOTICE 									VARCHAR2(100),
	PRIMARY KEY (ACTIONCO_ID, ASSET_VERSION) 
);

CREATE TABLE CASTO_GESTPROMO_OPECO (
	ASSET_VERSION	        NUMBER(19)   NOT NULL,
	PROMOTION_ID 			VARCHAR2(50), 
	CREATEUR 				VARCHAR2(50), 
	CONDITIONAPPLICATION 	VARCHAR2(2000), 
	MESSAGECOUPON 			VARCHAR2(2000), 
	TYPEAFFICHAGE 			NUMBER(*,0), 
	APPLICATIONMAGASIN 		NUMBER(*,0), 
	ACTIONCO_ID 			VARCHAR2(50), 
	CHAPO 					VARCHAR2(255), 
	USAGEUNIQUE 			NUMBER(*,0), 
	OPECO_NC_ALL 			NUMBER(*,0),
	PRIMARY KEY (PROMOTION_ID, ASSET_VERSION) 
);  

CREATE TABLE CASTO_GESTPROMO_ELEMENT (
	ASSET_VERSION	        NUMBER(19)   	NOT NULL,
	PROMOTION_ID 			VARCHAR2(50) 	NOT NULL, 
	SEQUENCE_NUM 			NUMBER(*,0) 	NOT NULL, 
	ELEMENT 				VARCHAR2(100),
	PRIMARY KEY (PROMOTION_ID, SEQUENCE_NUM, ASSET_VERSION) 
);

CREATE TABLE CASTO_GESTPROMO_OPECO_NC (
	ASSET_VERSION	        NUMBER(19)   	NOT NULL,
	PROMOTION_ID 			VARCHAR2(50) 	NOT NULL, 
	SEQUENCE_NUM 			NUMBER(*,0) 	NOT NULL, 
	PROMOTIONNC_ID 			VARCHAR2(50),
	PRIMARY KEY (PROMOTION_ID, SEQUENCE_NUM, ASSET_VERSION) 
); 

CREATE TABLE CASTO_PROMOTION (
	ASSET_VERSION	        NUMBER(19)   NOT NULL,
	PROMOTION_ID 			VARCHAR2(50) NOT NULL, 
	TYPAGE_PROMOTION 		NUMBER(*,0),
	PRIMARY KEY (PROMOTION_ID, ASSET_VERSION) 
);

CREATE TABLE CAST_PRODUCT_CHARACTERISTICS (
	ASSET_VERSION                           NUMBER(19)          NOT NULL,
	CATALOG_ID								VARCHAR2(40) 		NOT NULL,
	SEQUENCE_NUM 							INTEGER 			NOT NULL,
	CHARACTERISTIC_PROPERTY					VARCHAR2(50)	        NULL,
	PRIMARY KEY(CATALOG_ID, SEQUENCE_NUM, ASSET_VERSION));

ALTER TABLE DCS_CATEGORY 
	MODIFY (DESCRIPTION VARCHAR2(300));

CREATE TABLE CASTO_LEGACY_URL (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ID 										VARCHAR2(40) 		NOT NULL, 
	URI 									VARCHAR2(400) 		NOT NULL,
	CATEGORY_ID   							VARCHAR2(40) 		NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION) 
);

CREATE TABLE CASTO_STAGE (
	ASSET_VERSION	    NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID		VARCHAR2(40) 		NOT NULL,
	BRANCH_ID			VARCHAR2(40) 		NOT NULL,
	IS_HEAD				NUMBER(1)	 		NOT NULL,
	VERSION_DELETED		NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	NUMBER(1)	 		NOT NULL,
	PRED_VERSION		NUMBER(19)			NULL,
	CHECKIN_DATE		DATE	     		NULL,
	ID                  VARCHAR2(40) NOT NULL,
	NOM                 VARCHAR2(100),
	descriptif          VARCHAR2(800),
	datestage           DATE,	
	horaires            VARCHAR2(100),
	VIDEO_URL 			VARCHAR2(400),
	PRIMARY KEY(ID, ASSET_VERSION));

CREATE TABLE CAST_CATALOGUE (
	ASSET_VERSION	    NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID		VARCHAR2(40) 		NOT NULL,
	BRANCH_ID			VARCHAR2(40) 		NOT NULL,
	IS_HEAD				NUMBER(1)	 		NOT NULL,
	VERSION_DELETED		NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	NUMBER(1)	 		NOT NULL,
	PRED_VERSION		NUMBER(19)			NULL,
	CHECKIN_DATE		DATE	     		NULL,
	ID					VARCHAR2(40) 	NOT NULL,
	TITLE				VARCHAR2(100) 	NOT NULL,
	DESCRIPTION			VARCHAR2(300) 	NOT NULL,
	PROMO_MESSAGE		VARCHAR2(300) 	NULL,
	ACTIVE				NUMBER(1,0)		default 0 not null,
	FEATURED			NUMBER(1,0)		default 0 not null,
	BOOKABLE			NUMBER(1,0)		default 0 not null,
	IMAGE				VARCHAR2(40) 	NOT NULL,
	BROWSE_URL			VARCHAR2(300) 		NULL,
	DISPLAY_ORDER		NUMBER(*,0)		default 0,
	RELEASE_DATE		DATE,
	AVAILABLE_COPIES	NUMBER(*,0),
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_RESERVATION_CATALOGUE (
	ASSET_VERSION	    NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID		VARCHAR2(40) 		NOT NULL,
	BRANCH_ID			VARCHAR2(40) 		NOT NULL,
	IS_HEAD				NUMBER(1)	 		NOT NULL,
	VERSION_DELETED		NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	NUMBER(1)	 		NOT NULL,
	PRED_VERSION		NUMBER(19)			NULL,
	CHECKIN_DATE		DATE	     		NULL,
	ID 					VARCHAR2(40) 	NOT NULL, 
	EMAIL 				VARCHAR2(255) 		NULL, 
	CIVILITE 			VARCHAR2(50) 	NOT NULL, 
	PRENOM 				VARCHAR2(100) 	NOT NULL, 
	NOM 				VARCHAR2(100) 	NOT NULL, 
	ADRESSE 			VARCHAR2(100) 	NOT NULL,
	ADRESSE2 			VARCHAR2(100),
	ADRESSE3 			VARCHAR2(100),
	ADRESSE4 			VARCHAR2(100),
	CPLTADRESSE 		VARCHAR2(100), 
	VILLE 				VARCHAR2(100) 	NOT NULL, 
	CODEPOSTAL 			VARCHAR2(10) 	NOT NULL, 
	PAYS 				VARCHAR2(40) 	NOT NULL, 
	DATENAISSANCE 		DATE, 
	DATERESERVATION 	DATE 			NOT NULL, 
	NOUVEAUCOMPTE 		NUMBER(*,0) 	NULL, 
	OPTIN 				NUMBER(*,0) 	NULL,
	PHONE_NUMBER_1		varchar2(15) 	NOT NULL,
	PHONE_NUMBER_2		varchar2(15),
	CATALOGUE_ID		VARCHAR2(40) 	NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_SKU_INTEGRATION (
	SKU_ID 									VARCHAR2(40) 		NOT NULL, 
	ASSET_VERSION	    					NUMBER(19)		NOT NULL,
	CYBERCOACH		 						NUMBER(1, 0)		NULL, 
	RATIO 									NUMBER(8, 2)		NULL,
	BORNES		 							NUMBER(1, 0)		NULL, 
	KITCHEN_PLANNER	 						NUMBER(1, 0)		NULL, 
	PRIMARY KEY (SKU_ID, ASSET_VERSION)); 

CREATE TABLE CAST_SKU_INSTRUCTIONS (
    ASSET_VERSION                           NUMBER(19)          NOT NULL,
    SKU_ID                                  VARCHAR2(40)        NOT NULL,
    MEDIA_ID                                VARCHAR2(40)        NOT NULL,
    INSTRUCTION_NAME                        VARCHAR2(100)       NOT NULL,
    PRIMARY KEY(ASSET_VERSION, SKU_ID, MEDIA_ID));

CREATE TABLE CAST_GROUPED_ASSEMBLY_OPTIONS (
    ASSET_VERSION                           NUMBER(19)   NOT NULL,
    SEQUENCE_NUM                            INTEGER      NOT NULL,
    GROUPED_PRODUCT_ID                      VARCHAR2(40) NOT NULL,
    SKU_LINK_ID                             VARCHAR2(40) NOT NULL
,constraint CAST_GROUPED_ASSEMBLY_OPT_p primary key (GROUPED_PRODUCT_ID,SKU_LINK_ID,ASSET_VERSION));

ALTER TABLE CAST_PROMO_INFORMATION ADD HTMLURL VARCHAR2(255) NULL;

ALTER TABLE CAST_STYLE ADD LIST_VIEW NUMBER DEFAULT 0 NOT NULL;

CREATE INDEX CAST_CATALOGUE_WSX ON CAST_CATALOGUE (WORKSPACE_ID);
CREATE INDEX CAST_CATALOGUE_CIX ON CAST_CATALOGUE (CHECKIN_DATE);

CREATE INDEX CAST_DOCUMENT_WSX ON CAST_DOCUMENT (WORKSPACE_ID);
CREATE INDEX CAST_DOCUMENT_CIX ON CAST_DOCUMENT (CHECKIN_DATE);

CREATE INDEX CASTO_GESTPROMO_ACTIONCO_WSX ON CASTO_GESTPROMO_ACTIONCO (WORKSPACE_ID);
CREATE INDEX CASTO_GESTPROMO_ACTIONCO_CIX ON CASTO_GESTPROMO_ACTIONCO (CHECKIN_DATE);

CREATE INDEX CASTO_LEGACY_URL_WSX ON CASTO_LEGACY_URL (WORKSPACE_ID);
CREATE INDEX CASTO_LEGACY_URL_CIX ON CASTO_LEGACY_URL (CHECKIN_DATE);

CREATE INDEX CASTO_STAGE_WSX ON CASTO_STAGE (WORKSPACE_ID);
CREATE INDEX CASTO_STAGE_CIX ON CASTO_STAGE (CHECKIN_DATE);

ALTER TABLE CAST_PROMO_INFORMATION MODIFY TITLE VARCHAR2 (200);
ALTER TABLE CAST_PROMO_INFORMATION MODIFY DESCRIPTION VARCHAR2 (500);

ALTER TABLE CAST_PROMO_INFORMATION ADD WRAPPAGE NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE CAST_GROUPED_PRODUCT ADD PROMOTEMPLATE VARCHAR2(100) NULL;
ALTER TABLE CAST_SKU ADD ON_SALE_DISCOUNT_DISPLAY NUMBER(1,0) DEFAULT 0 NULL;
ALTER TABLE CASTO_SKU MODIFY FLASH_PRODUIT VARCHAR2(255);

ALTER TABLE CAST_DOCUMENT ADD PROMOTEMPLATE VARCHAR2(100)  NULL;

ALTER TABLE CAST_PRODUCT ADD FLAG_IMAGE	VARCHAR2(100)	NULL;
ALTER TABLE CAST_PRODUCT ADD FLAG_TEXT	VARCHAR2(200)	NULL;

ALTER TABLE CASTO_SKU ADD video_aux_url	VARCHAR2(2000) NULL;
ALTER TABLE CASTO_SKU ADD video_full_size NUMBER(1, 0) DEFAULT 0;

alter table CAST_CATEGORY modify info_text varchar2(1000);
alter table CAST_CATEGORY modify commerce_text varchar2(1000);

ALTER TABLE CASTO_SKU RENAME COLUMN URL_PAGE TO EAN;

ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_START_DATE DATE NULL;
ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_END_DATE DATE NULL;

update CASTO_SKU set EAN = substr(EAN, 1, 13);
ALTER TABLE CASTO_SKU MODIFY EAN VARCHAR2(13);
