CREATE TABLE CASTO_REGION_MESSAGES (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,	
  	MESSAGE_ID  							VARCHAR2(40),
  	REGION_ID   							VARCHAR2(40),
  	SEQ         							INTEGER,
	PRIMARY KEY (MESSAGE_ID, REGION_ID, ASSET_VERSION));

CREATE TABLE CASTO_MESSAGES (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	MESSAGE_ID     							VARCHAR2(40),
  	MESSAGE_NOM    							VARCHAR2(50),
  	MESSAGE_TEXTE  							VARCHAR2(4000),
	PRIMARY KEY (MESSAGE_ID, ASSET_VERSION));

CREATE TABLE CASTO_DEPARTEMENT_OLD (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	ID      								VARCHAR2(40)             NOT NULL,
	NUMERO  								VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_DEPARTEMENT(
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ID         								VARCHAR2(40)        NOT NULL,
	NUMERO     								VARCHAR2(40)        NOT NULL,
	NOM        								VARCHAR2(100)		NOT NULL,
	REGION_ID  								VARCHAR2(40)		NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_ADRESSE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
	ID             VARCHAR2(40)             NOT NULL,
	DEPARTEMENTID  VARCHAR2(40)                  NOT NULL,
	VILLE          VARCHAR2(128)            NOT NULL,
	CP             VARCHAR2(10),
	RUE            VARCHAR2(128),
	TEL            VARCHAR2(32),
	FAX            VARCHAR2(32),
	COMMENTAIRE    VARCHAR2(500),
	PRIMARY KEY (ID, ASSET_VERSION));


CREATE TABLE CASTO_ENTITE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID           							VARCHAR2(40)                    NOT NULL,
  	ADRESSEID    							VARCHAR2(40)                    NOT NULL,
  	NOM          							VARCHAR2(64)               NOT NULL,
  	LOGIN_ADMIN  							VARCHAR2(64)               NOT NULL,
  	PASS_ADMIN   							VARCHAR2(64)               NOT NULL,
  	EMAIL        							VARCHAR2(255),
	PRIMARY KEY (ID, ASSET_VERSION));


CREATE TABLE CASTO_COMMANDE_SERVICE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID_SERVICE           					VARCHAR2(40)             NOT NULL,
  	LIBELLE              					VARCHAR2(255)       NOT NULL,
  	URL_BOUTON           					VARCHAR2(255)       NOT NULL,
  	SHIPPING_GROUP_NAME  					VARCHAR2(255)       NOT NULL,  
	PRIMARY KEY (ID_SERVICE, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID                      				VARCHAR2(40)               NOT NULL,
  	ENTITE_ID               				VARCHAR2(40)               NOT NULL,
  	NOM                     				VARCHAR2(64),
  	URL_IMG_PLAN            				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PDF_PLAN            				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	ACCES_ROUTE             				VARCHAR2(500),
  	ACCES_ROUTE2           					VARCHAR2(500),
  	ACCES_AUTOROUTE         				VARCHAR2(500),
  	ACCES_TRANSPORT_COMMUN  				VARCHAR2(500),
  	HORAIRES                				VARCHAR2(500),
  	NOM_SECONDAIRE          				VARCHAR2(64),
  	URL_IMG_PLAN_MASSE      				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PDF_PLAN_MASSE      				VARCHAR2(128)    	  DEFAULT 0                     NOT NULL,
  	URL_PHOTO               				VARCHAR2(128)   	  DEFAULT 0                     NOT NULL,
  	POSITION_TOP            				INTEGER             DEFAULT 0                     NOT NULL,
  	POSITION_LEFT           				INTEGER             DEFAULT 0                     NOT NULL,
  	KEYWORDS                				VARCHAR2(254),
  	DESCRIPTION             				VARCHAR2(254),
  	DELAI_PREPARATION       				NUMBER(14),
  	DELAI_LIVRAISON         				NUMBER(14),
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN_COMM_SERVICE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,	
  	ID_SERVICE  							VARCHAR2(40)             NOT NULL,
  	ID_MAGASIN  							VARCHAR2(40)             NOT NULL,  	
	PRIMARY KEY (ID_SERVICE, ID_MAGASIN, ASSET_VERSION));

CREATE TABLE CASTO_MAGAS_COUPLE_SERVICE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID_SERVICE  							VARCHAR2(40)             NOT NULL ,
  	ID_MAGASIN  							VARCHAR2(40)             NOT NULL,
  	ID_COUPLE   							VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (ID_COUPLE, ASSET_VERSION));

CREATE TABLE CASTO_REGION (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID               						VARCHAR2(40)          NOT NULL,
  	NOM              						VARCHAR2(64)   		NOT NULL,
  	URL_IMG_REGION   						VARCHAR2(128),
  	ORDRE_AFFICHAGE  						VARCHAR2(10),
	PRIMARY KEY (ID, ASSET_VERSION));


CREATE TABLE CASTO_SERVICE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID   									VARCHAR2(40)             NOT NULL,
  	NOM  									VARCHAR2(64)   		NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN_SERVICE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)             NOT NULL,
  	SEQ         							INTEGER             NOT NULL,
  	SERVICE_ID  							VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (MAGASIN_ID, SERVICE_ID, ASSET_VERSION));

CREATE TABLE CASTO_OFFRE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID           							VARCHAR2(40)          NOT NULL,
  	REFERENCE    							VARCHAR2(16)        NOT NULL,
  	TITRE        							VARCHAR2(128),
  	DATEMIN     							DATE,
  	DATEMAX      							DATE,
  	ACTIVATE     							NUMBER(1),
  	DESCRIPTION  							LONG,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_ACTUALITE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID        								VARCHAR2(40)          NOT NULL,
  	TITRE     								VARCHAR2(128),
  	DATEMIN  								DATE,
  	DATEMAX   								DATE,
  	CONTENU   								VARCHAR2(1000),
  	ACTIVATE  								NUMBER(1),
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_OPERATION_SPECIALE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID            							VARCHAR2(40)                      	NOT NULL,
  	TITRE_HP      							VARCHAR2(255)              		NOT NULL,
  	LIBELLE_LIEN  							VARCHAR2(255)              		NOT NULL,
  	TITRE         							VARCHAR2(255)              		NOT NULL,
  	INTRODUCTION  							VARCHAR2(2000)             		NOT NULL,
  	DATE_DEBUT    							DATE                            NOT NULL,
  	DATE_FIN      							DATE                            NOT NULL,
  	ACTIVATE      							NUMBER                          DEFAULT 0                     NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_OPERATION_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	ID         								VARCHAR2(40)              NOT NULL,
  	SEQ         							INTEGER              NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)              NOT NULL,
	PRIMARY KEY (ID, SEQ, ASSET_VERSION));

CREATE TABLE CASTO_IMAGE_AUX (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	IMAGE_AUX_ID     						VARCHAR2(40)         NOT NULL,
  	MAGASIN_ID       						VARCHAR2(40)           NOT NULL,
  	SMALL_IMAGE_URL  						VARCHAR2(128)       NOT NULL,
  	LARGE_IMAGE_URL  						VARCHAR2(128)       NOT NULL,
	PRIMARY KEY  (IMAGE_AUX_ID, ASSET_VERSION));

CREATE TABLE CASTO_OUVERTURE_EXCEP (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	WORKSPACE_ID							VARCHAR2(40) 		NOT NULL,
	BRANCH_ID								VARCHAR2(40) 		NOT NULL,
	IS_HEAD									NUMBER(1)	 		NOT NULL,
	VERSION_DELETED							NUMBER(1)	 		NOT NULL,
	VERSION_EDITABLE	  					NUMBER(1)	 		NOT NULL,
	PRED_VERSION							NUMBER(19)			NULL,
	CHECKIN_DATE							DATE	     		NULL,
  	ID                 						VARCHAR2(40)        NOT NULL,
  	MAGASIN_ID         						VARCHAR2(40)        NOT NULL,
  	LIBELLE            						VARCHAR2(100),
  	DATE_FIN_VALIDITE  						DATE                NOT NULL,
	PRIMARY KEY (ID, ASSET_VERSION));

CREATE TABLE CASTO_OFFRE_MAGASIN (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	OFFRE_ID    							VARCHAR2(40)          NOT NULL,
  	SEQ         							INTEGER          NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (OFFRE_ID, MAGASIN_ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASINS_ACTU (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	MAGASIN_ID  							VARCHAR2(40)        NOT NULL,
  	SEQ         							INTEGER          	NOT NULL,
  	ACTU_ID     							VARCHAR2(40)        NOT NULL,
	PRIMARY KEY (MAGASIN_ID, ACTU_ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN_IMAGE_AUX (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	MAGASIN_ID    							VARCHAR2(40)             NOT NULL,
  	SEQ           							INTEGER             NOT NULL,
  	IMAGE_AUX_ID  							VARCHAR2(40)             NOT NULL,
	PRIMARY KEY (MAGASIN_ID, IMAGE_AUX_ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN_OUVERTURE_EXCEP (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	MAGASIN_ID  							VARCHAR2(40)             NOT NULL,
  	SEQ         							INTEGER             NOT NULL,
  	ID          							VARCHAR2(40)          NOT NULL,
	PRIMARY KEY  (MAGASIN_ID, ID, ASSET_VERSION));

CREATE TABLE CASTO_MAGASIN_PROCHE (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
  	MAGASIN_REF     						VARCHAR2(40)             NOT NULL,
  	SEQ             						INTEGER             NOT NULL,
  	MAGASIN_PROCHE  						VARCHAR2(40)             NOT NULL,
	PRIMARY KEY  (MAGASIN_REF, MAGASIN_PROCHE, ASSET_VERSION));

CREATE INDEX CASTO_IMAGE_AUX_WSX ON CASTO_IMAGE_AUX (WORKSPACE_ID);
CREATE INDEX CASTO_IMAGE_AUX_CIX ON CASTO_IMAGE_AUX (CHECKIN_DATE);

CREATE INDEX CASTO_DEPARTEMENT_WSX ON CASTO_DEPARTEMENT (WORKSPACE_ID);
CREATE INDEX CASTO_DEPARTEMENT_CIX ON CASTO_DEPARTEMENT (CHECKIN_DATE);

CREATE INDEX CASTO_ENTITE_WSX ON CASTO_ENTITE (WORKSPACE_ID);
CREATE INDEX CASTO_ENTITE_CIX ON CASTO_ENTITE (CHECKIN_DATE);

CREATE INDEX CASTO_ACTUALITE_WSX ON CASTO_ACTUALITE (WORKSPACE_ID);
CREATE INDEX CASTO_ACTUALITE_CIX ON CASTO_ACTUALITE (CHECKIN_DATE);

CREATE INDEX CASTO_ADRESSE_WSX ON CASTO_ADRESSE (WORKSPACE_ID);
CREATE INDEX CASTO_ADRESSE_CIX ON CASTO_ADRESSE (CHECKIN_DATE);

CREATE INDEX CASTO_COMMANDE_SERVICE_WSX ON CASTO_COMMANDE_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_COMMANDE_SERVICE_CIX ON CASTO_COMMANDE_SERVICE (CHECKIN_DATE);

CREATE INDEX CASTO_MAGAS_COUPLE_SERVICE_WSX ON CASTO_MAGAS_COUPLE_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_MAGAS_COUPLE_SERVICE_CIX ON CASTO_MAGAS_COUPLE_SERVICE (CHECKIN_DATE);

CREATE INDEX CASTO_MAGASIN_WSX ON CASTO_MAGASIN (WORKSPACE_ID);
CREATE INDEX CASTO_MAGASIN_CIX ON CASTO_MAGASIN (CHECKIN_DATE);

CREATE INDEX CASTO_MESSAGES_WSX ON CASTO_MESSAGES (WORKSPACE_ID);
CREATE INDEX CASTO_MESSAGES_CIX ON CASTO_MESSAGES (CHECKIN_DATE);

CREATE INDEX CASTO_OFFRE_WSX ON CASTO_OFFRE (WORKSPACE_ID);
CREATE INDEX CASTO_OFFRE_CIX ON CASTO_OFFRE (CHECKIN_DATE);

CREATE INDEX CASTO_OPERATION_SPECIALE_WSX ON CASTO_OPERATION_SPECIALE (WORKSPACE_ID);
CREATE INDEX CASTO_OPERATION_SPECIALE_CIX ON CASTO_OPERATION_SPECIALE (CHECKIN_DATE);

CREATE INDEX CASTO_OUVERTURE_EXCEP_WSX ON CASTO_OUVERTURE_EXCEP (WORKSPACE_ID);
CREATE INDEX CASTO_OUVERTURE_EXCEP_CIX ON CASTO_OUVERTURE_EXCEP (CHECKIN_DATE);

CREATE INDEX CASTO_REGION_WSX ON CASTO_REGION (WORKSPACE_ID);
CREATE INDEX CASTO_REGION_CIX ON CASTO_REGION (CHECKIN_DATE);

CREATE INDEX CASTO_SERVICE_WSX ON CASTO_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_SERVICE_CIX ON CASTO_SERVICE (CHECKIN_DATE);