DROP USER CAST_STORE_LOCAL_PRICES CASCADE;

CREATE USER          CAST_STORE_LOCAL_PRICES
IDENTIFIED BY        CAST_STORE_LOCAL_PRICES
DEFAULT   TABLESPACE CAST_LOCAL_PRICES
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_STORE_LOCAL_PRICES;