DROP USER CAST_CATA CASCADE;
DROP USER CAST_CATB CASCADE;
DROP USER CAST_CORE CASCADE;
DROP USER CAST_PUB CASCADE;

CREATE USER          CAST_CATA
IDENTIFIED BY         CAST_CATA
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_CATA;

CREATE USER          CAST_CATB
IDENTIFIED BY         CAST_CATB
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_CATB;

CREATE USER          CAST_CORE
IDENTIFIED BY         CAST_CORE
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_CORE;

CREATE USER          CAST_PUB
IDENTIFIED BY         CAST_PUB
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_PUB;

CREATE USER          CAST_STOCK
IDENTIFIED BY         CAST_STOCK
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_STOCK;

CREATE USER          CAST_LOC
IDENTIFIED BY         CAST_LOC
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_LOC;

CREATE USER          CAST_LOC_PR
IDENTIFIED BY         CAST_LOC_PR
DEFAULT   TABLESPACE CAST_USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO CAST_LOC_PR;

