ALTER TABLE "SCD_FACTURE_AVOIR_LIGNE" MODIFY (
  "LARTICLE" VARCHAR2(100)
);

ALTER TABLE "SCD_CONTACT" MODIFY (
  "LCONTACT" VARCHAR2(2400)
);

ALTER TABLE "SCD_VENTE_WEB" MODIFY (
  "LCODE_CHEQUE" VARCHAR2(60)
);