
  CREATE TABLE "CAST_THEMATIQUE" 
   (	
    "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(19,0), 
	"CHECKIN_DATE" DATE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
	"DESCRIPTION" VARCHAR2(2048 BYTE), 
    "S_IMAGE" VARCHAR2(40 BYTE), 
    "B_IMAGE" VARCHAR2(40 BYTE), 
    "CHAPTER" VARCHAR2(40 BYTE),
    "BG_COLOR" VARCHAR2(25 BYTE), 
    "FONT_COLOR" VARCHAR2(25 BYTE), 
	"TOP_DOC_TITLE" VARCHAR2(254 BYTE), 
	"TOP_DOC_DESCRIPTION" VARCHAR2(2048 BYTE), 
	"BOTTOM_DOC_TITLE" VARCHAR2(254 BYTE), 
	"BOTTOM_DOC_DESCRIPTION" VARCHAR2(2048 BYTE), 
	"PAGE_TITLE_PATTERN" VARCHAR2(300 BYTE), 
	"META_DESCRIPTION_PATTERN" VARCHAR2(300 BYTE), 
	 CONSTRAINT "CAST_THEMATIQUE_P" PRIMARY KEY ("THEMATIQUE_ID", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 

  CREATE INDEX "CAST_THEMATIQUE_CIX" ON "CAST_THEMATIQUE" ("CHECKIN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "CAST_THEMATIQUE_WSX" ON "CAST_THEMATIQUE" ("WORKSPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 



  CREATE TABLE "CAST_THEMATIQUE_DOCS_TOP" 
   (	
	"ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_TOP_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


  CREATE TABLE "CAST_THEMATIQUE_DOCS_BOTTOM" 
   (	
	"ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"DOCUMENT_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_DOCS_BOTTOM_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM", "ASSET_VERSION" )
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


 


  CREATE TABLE "CAST_CHAPTERTHEM" 
   (	"ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(19,0), 
	"CHECKIN_DATE" DATE, 
	"CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
    "COLOR" VARCHAR2(25 BYTE), 
	 CONSTRAINT "CAST_CHAPTERTHEM_P" PRIMARY KEY ("CHAPTER_ID", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 

  CREATE INDEX "CAST_CHAPTERTHEM_CIX" ON "CAST_CHAPTERTHEM" ("CHECKIN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "CAST_CHAPTERTHEM_WSX" ON "CAST_CHAPTERTHEM" ("WORKSPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;



  CREATE TABLE "CAST_CONTTHEM" 
   (	
    "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(19,0), 
	"CHECKIN_DATE" DATE, 
	"CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
	 CONSTRAINT "CAST_CONTTHEME_P" PRIMARY KEY ("CONTAINER_ID", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 

  CREATE INDEX "CAST_CONTTHEM_CIX" ON "CAST_CONTTHEM" ("CHECKIN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "CAST_CONTTHEM_WSX" ON "CAST_CONTTHEM" ("WORKSPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


 CREATE TABLE "CAST_CONT_THEM" 
   (	
	"ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_CONT_THEM_P" PRIMARY KEY ("CONTAINER_ID", "SEQUENCE_NUM", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

CREATE TABLE "CAST_CONT_CHAPT" 
   (	
    "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"CONTAINER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_CONT_CHAPT_P" PRIMARY KEY ("CONTAINER_ID", "SEQUENCE_NUM", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
  
  ALTER TABLE "CAST_CHAPTERTHEM" ADD "H_IMAGE" VARCHAR2(40 BYTE);
  
  CREATE TABLE "CAST_GUIMENU" 
   (	
    "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(19,0), 
	"CHECKIN_DATE" DATE,
    "MENU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
    "IMAGE" VARCHAR2(40 BYTE), 
    "CATEGORY" VARCHAR2(40) NULL ,
    "VERSION" NUMBER(*,0) NOT NULL ENABLE,
    "TEMPLATE" VARCHAR2(254 BYTE), 
	 CONSTRAINT "CAST_GUIMENU_P" PRIMARY KEY ("MENU_ID", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  CREATE INDEX "CAST_GUIMENU_CIX" ON "CAST_GUIMENU" ("CHECKIN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "CAST_GUIMENU_WSX" ON "CAST_GUIMENU" ("WORKSPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


  CREATE TABLE "CAST_MENUITEM" 
   (
    "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(19,0), 
	"CHECKIN_DATE" DATE,
    "ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(254 BYTE), 
    "IMAGE" VARCHAR2(40 BYTE), 
    "VERSION" NUMBER(*,0) NOT NULL ENABLE,
    "MENU" VARCHAR2(40) NULL,
    "TEMPLATE" VARCHAR2(254 BYTE), 
	 CONSTRAINT "CAST_MENUITEM_P" PRIMARY KEY ("ITEM_ID", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

  CREATE INDEX "CAST_MENUITEM_CIX" ON "CAST_MENUITEM" ("CHECKIN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
 
  CREATE INDEX "CAST_MENUITEM_WSX" ON "CAST_MENUITEM" ("WORKSPACE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;


  ALTER TABLE "CAST_MENUITEM" ADD "URL" VARCHAR2(2048 BYTE);
  ALTER TABLE "CAST_MENUITEM" ADD "NEW_TAB" NUMBER(1,0) DEFAULT 0 NOT NULL;

  
  CREATE TABLE "CAST_GUIMENU_ITEMS" 
   (
   "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
    "MENU_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
    "ITEM_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
     CONSTRAINT "CAST_GUIMENU_ITEMS_P" PRIMARY KEY ("ITEM_ID", "SEQUENCE_NUM", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;
  
  CREATE TABLE "CAST_THEMATIQUE_CHAPT" 
   (	
   "ASSET_VERSION" NUMBER(19,0) NOT NULL ENABLE, 
    "SEQUENCE_NUM" NUMBER(*,0) NOT NULL ENABLE, 
	"THEMATIQUE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CHAPTER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CAST_THEMATIQUE_CHAPT_P" PRIMARY KEY ("THEMATIQUE_ID", "SEQUENCE_NUM", "ASSET_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CAST_USERS" ;

ALTER TABLE "CAST_DOCUMENT" ADD "EXTERNAL_URL"	VARCHAR2(2048 BYTE)	NULL;

ALTER TABLE  "CAST_THEMATIQUE" DROP COLUMN "CHAPTER";

ALTER TABLE "CAST_THEMATIQUE" MODIFY
	(
	"TITLE" VARCHAR2(510 BYTE), 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"TOP_DOC_TITLE" VARCHAR2(510 BYTE), 
	"TOP_DOC_DESCRIPTION" VARCHAR2(3000 BYTE), 
	"BOTTOM_DOC_TITLE" VARCHAR2(510 BYTE), 
	"BOTTOM_DOC_DESCRIPTION" VARCHAR2(3000 BYTE)
	);