drop TABLE "CAST_CORE"."CASTO_COMMERCE_ITEM_BACKUP_TMP";
create table "CAST_CORE".CASTO_COMMERCE_ITEM_BACKUP_TMP as select * from "CAST_CORE"."CASTO_COMMERCE_ITEM_BACKUP" where '1' = '1';
alter table "CASTO_CCE_ITEM_LISTE_BACKUP" drop constraint "FK_CASTO_CCE_ITEMS_BACKUP";
drop TABLE "CAST_CORE"."CASTO_COMMERCE_ITEM_BACKUP"cascade constraints;
alter table "CAST_CORE"."CASTO_COMMERCE_ITEM_BACKUP_TMP" rename to CASTO_COMMERCE_ITEM_BACKUP;
alter table "CASTO_COMMERCE_ITEM_BACKUP" add constraint PK_CASTO_COMMERCE_ITEM_BACKUP primary key("COMMERCE_ITEM_ID");
alter table "CASTO_CCE_ITEM_LISTE_BACKUP" add constraint FK_CASTO_CCE_ITEMS_BACKUP foreign key("COMMERCE_ITEM_ID") references "CASTO_COMMERCE_ITEM_BACKUP"("COMMERCE_ITEM_ID") ON DELETE CASCADE ENABLE; 
commit;