ALTER TABLE CASTO_CATEGORY ADD IK_CATEGORY_TYPE	VARCHAR2(255);
ALTER TABLE CASTO_CATEGORY ADD IK_CATEGORY_TYPE_NAV NUMBER(2) DEFAULT 0;

CREATE TABLE CASTO_SKU_IK_CS_ASSOC (
	ASSET_VERSION	                        NUMBER(19)	  		NOT NULL,
	SKU_ID 									VARCHAR2(40)		NOT NULL, 
	SEQUENCE_NUM 							INTEGER	 			NOT NULL, 
	CROSS_ID 								VARCHAR2(40)		NULL,
	PRIMARY KEY (SKU_ID, SEQUENCE_NUM, ASSET_VERSION));	

CREATE TABLE CASTO_IK_CATEGORY_TYPE (
	ASSET_VERSION							NUMBER(19,0) 		NOT NULL ENABLE, 
	WORKSPACE_ID 							VARCHAR2(40 BYTE)	NOT NULL ENABLE, 
	BRANCH_ID								VARCHAR2(40 BYTE)	NOT NULL ENABLE, 
	IS_HEAD									NUMBER(1,0) 		NOT NULL ENABLE, 
	VERSION_DELETED							NUMBER(1,0)			NOT NULL ENABLE, 
	VERSION_EDITABLE						NUMBER(1,0) 		NOT NULL ENABLE, 
	PRED_VERSION							NUMBER(19,0), 
	CHECKIN_DATE 							DATE,
	TYPE_NAME								VARCHAR2(255)		NOT NULL,
	PRIMARY KEY (TYPE_NAME, ASSET_VERSION));
	

commit;