alter table CASTO_FAST_LAB_CONFIGS add (
"CHOOSE_STORE_LABEL" VARCHAR2(75 BYTE), 
"CHOOSE_STORE_DESCR" VARCHAR2(300 BYTE), 
"SEARCH_INPUT_TITLE" VARCHAR2(300 BYTE), 
"LEADFORMANCE_LINK_VALUE" VARCHAR2(75 BYTE), 
"BEST_OFFERS" VARCHAR2(75 BYTE), 
"CC_STORE_MESSAGE_LONG" VARCHAR2(75 BYTE), 
"CC_STORE_MESSAGE_SHORT" VARCHAR2(75 BYTE), 
"CHANGE_STORE_LABEL" VARCHAR2(75 BYTE), 
"CHOOSE_OTHER_STORE_LABEL" VARCHAR2(75 BYTE), 
"CHOOSE_THIS_STORE_LABEL" VARCHAR2(75 BYTE), 
"YOUR_STORE_LABEL" VARCHAR2(75 BYTE), 
"SEARCH_STORE_LABEL" VARCHAR2(75 BYTE), 
"CATALOG_PAGE_LINK" VARCHAR2(150 BYTE),
"CLOSE_BUTTON_ENABLED" NUMBER(1,0) DEFAULT 0);


ALTER TABLE CAST_PROMO_INFORMATION ADD META_KEYWORDS_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_PROMO_INFORMATION ADD META_DESCRIPTION_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_PROMO_INFORMATION ADD SHORT_DESCRIPTION	VARCHAR2(300)	NULL;

CREATE TABLE CAST_PROMO_INFO_KEYWRDS (
	ASSET_VERSION NUMBER(19) NOT NULL, 
	ID VARCHAR2(40) NOT NULL,
	SEQUENCE_NUM INTEGER NOT NULL,
	KEYWORDS VARCHAR2(254) NULL,
	PRIMARY KEY(ID, SEQUENCE_NUM, ASSET_VERSION));
	
commit;