echo on
REM !!!==

ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_START_DATE DATE NULL;
ALTER TABLE CASTO_SKU ADD CASTORAMA_PRICE_END_DATE DATE NULL;
ALTER TABLE CASTO_SKU ADD SHOW_M2_FIRST NUMBER(1,0) DEFAULT 1;
ALTER TABLE CASTO_SKU ADD SHOW_CARD_PRICE NUMBER(1,0);
ALTER TABLE CASTO_SKU ADD EMISSION_LEVEL VARCHAR2(40);

update CASTO_SKU set EAN = substr(EAN, 1, 13);
ALTER TABLE CASTO_SKU MODIFY EAN VARCHAR2(13);

commit;
