ALTER TABLE CASTO_MAGASIN DROP COLUMN STORE_ID;

ALTER TABLE CAST_DOCUMENT DROP COLUMN PAGE_TITLE_PATTERN;
ALTER TABLE CAST_DOCUMENT DROP COLUMN META_KEYWORDS_PATTERN;
ALTER TABLE CAST_DOCUMENT DROP COLUMN META_DESCRIPTION_PATTERN;

ALTER TABLE CAST_PROMO_INFORMATION DROP COLUMN PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT DROP COLUMN PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;

ALTER TABLE CAST_PRODUCT DROP COLUMN FLAG_IMAGE	VARCHAR2(100)	NULL;
ALTER TABLE CAST_PRODUCT DROP COLUMN FLAG_TEXT	VARCHAR2(200)	NULL;

ALTER TABLE CASTO_ORDER_BACKUP MODIFY (
    LOGIN varchar2(40)
);

commit;