alter table CASTO_FAST_LAB_CONFIGS drop (
"CHOOSE_STORE_LABEL", 
"CHOOSE_STORE_DESCR", 
"SEARCH_INPUT_TITLE", 
"LEADFORMANCE_LINK_VALUE", 
"BEST_OFFERS", 
"CC_STORE_MESSAGE_LONG", 
"CC_STORE_MESSAGE_SHORT", 
"CHANGE_STORE_LABEL", 
"CHOOSE_OTHER_STORE_LABEL", 
"CHOOSE_THIS_STORE_LABEL", 
"YOUR_STORE_LABEL", 
"SEARCH_STORE_LABEL", 
"CATALOG_PAGE_LINK",
"CLOSE_BUTTON_ENABLED");

ALTER TABLE CAST_PROMO_INFORMATION DROP COLUMN META_KEYWORDS_PATTERN;
ALTER TABLE CAST_PROMO_INFORMATION DROP COLUMN META_DESCRIPTION_PATTERN;
ALTER TABLE CAST_PROMO_INFORMATION DROP COLUMN SHORT_DESCRIPTION;

DROP TABLE CAST_PROMO_INFO_KEYWRDS CASCADE CONSTRAINTS;

commit;
