DROP TABLE CASTO_TICKET_LINE;
DROP TABLE CASTO_TICKET_METHOD;
DROP TABLE CASTO_TICKET_HEADER;
DROP TABLE CASTO_TICKET_MAPPING;
DROP TABLE CASTO_TICKET_STATISTIC;

DROP INDEX CASTO_TICKET_HEADER_TK_IDX;
DROP INDEX CASTO_TICKET_HEADER_HM_IDX;
DROP INDEX CASTO_TICKET_HEADER_ST_IDX;
DROP INDEX CASTO_TICKET_HEADER_TD_IDX;

DROP INDEX CASTO_TICKET_LINE_HD_IDX;
DROP INDEX CASTO_TICKET_LINE_PL_IDX;

DROP INDEX CASTO_TICKET_METHOD_HD_IDX;

DROP TABLE CASTO_TICKET_MAPPING;
DROP TABLE CASTO_TICKET_HEADER;
DROP TABLE CASTO_TICKET_METHOD;
DROP TABLE CASTO_TICKET_LINE;
DROP TABLE CASTO_TICKET_STATISTIC;

ALTER TABLE CASTO_ORDER_BACKUP MODIFY (
  LOGIN varchar2(40)
);

commit;