ALTER TABLE CASTO_MAGASIN DROP COLUMN STORE_ID;

ALTER TABLE CAST_DOCUMENT DROP COLUMN PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT DROP COLUMN META_KEYWORDS_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT DROP COLUMN META_DESCRIPTION_PATTERN	VARCHAR2(300)	NULL;

ALTER TABLE CAST_PROMO_INFORMATION DROP COLUMN PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;
ALTER TABLE CAST_DOCUMENT DROP COLUMN PAGE_TITLE_PATTERN	VARCHAR2(300)	NULL;

ALTER TABLE CAST_PRODUCT DROP COLUMN FLAG_IMAGE	VARCHAR2(100)	NULL;
ALTER TABLE CAST_PRODUCT DROP COLUMN FLAG_TEXT	VARCHAR2(200)	NULL;

UPDATE CAST_DOCUMENT 
SET PAGE_TITLE_PATTERN = NULL WHERE PAGE_TITLE_PATTERN = '{title} - CASTORAMA';

UPDATE CAST_DOCUMENT 
SET META_KEYWORDS_PATTERN = NULL WHERE META_KEYWORDS_PATTERN = '{keywords,sep=,}';
     
UPDATE CAST_DOCUMENT 
SET META_KEYWORDS_PATTERN = NULL WHERE META_DESCRIPTION_PATTERN = '{description}';

UPDATE CAST_PROMO_INFORMATION 
SET PAGE_TITLE_PATTERN = NULL WHERE PAGE_TITLE_PATTERN = '{title} - CASTORAMA';

commit;