ALTER TABLE CAST_CATALOG_ADDITION_PROP DROP (
  DISPLAY_BANNER,
  DISPLAY_STORES,
  COOKIE_AGE,
  POPUP_TITLE,
  HEADER_TEXT,
  CC_PROMO_INFO
  );

ALTER TABLE CASTO_MAGASIN DROP (
  CC_DELAY_PERIOD_UNIT,
  CC_DELAY_PERIOD,
  CC_PROMO_INFO,
  CC_TOP_PROMO_INFO,
  RETRAIT_MAGASIN,
  LOCAL_PRIX
  );

ALTER TABLE CAST_CATALOG_ADDITION_PROP DROP (
  DELIVERY_TOOLTIP,
  CC_TOOLTIP
  );

ALTER TABLE CASTO_MAGASIN DROP (
  CC_PHONE
  );

ALTER TABLE CAST_CATALOG_ADDITION_PROP DROP (
  PROCESSING_FEE_NICE_WORD
  );

ALTER TABLE CASTO_ORDER DROP (
  DELIVERY_TYPE,
  MAGASIN_ID 
  );
  
ALTER TABLE CASTO_MAGASIN DROP (
  CC_DELIVERY_MESSAGE
  );  

ALTER TABLE CASTO_ORDER DROP (
  PROCESSING_FEE_NICE_WORD
  );

ALTER TABLE CAST_CATALOG_ADDITION_PROP DROP (
  SHOPPING_CART_D2H_BANNER,
  SHOPPING_CART_CC_BANNER);

ALTER TABLE CASTO_MAGASIN DROP (
  PBX_SITE,
  PBX_RANG,
  PBX_IDENTIFIANT);

ALTER TABLE CASTO_ABONNEMENT_NEWSLETTER DROP (
  ACCEPT_RECONTACT
  );
  
ALTER TABLE CASTO_MAGASIN DROP (
  LOCAL_PRICE_LIST
);

DROP INDEX PERF_DCS_PROMOTION_IDX;

ALTER TABLE CASTO_MAGASIN DROP (
  PBX_SITE_SOFINCO,
  PBX_RANG_SOFINCO);

ALTER TABLE CASTO_MAGASIN DROP (
  PBX_IDENTIFIANT_SOFINCO);
  
COMMIT;