CREATE TABLE CASTO_CGV_INFO (
  ID VARCHAR2 (10) NOT NULL PRIMARY KEY,
  LAST_MODIFIED_DATE DATE
);

INSERT INTO CASTO_CGV_INFO (ID, LAST_MODIFIED_DATE) VALUES ('CGV_HTML', TO_DATE('01-JAN-2014', 'DD-MON-YYYY'));

commit;