CREATE TABLE CAST_GROUPED_ASSEMBLY_OPTIONS (
    SEQUENCE_NUM                            INTEGER             NOT NULL,
    GROUPED_PRODUCT_ID                      VARCHAR2(40)        NOT NULL REFERENCES DCS_PRODUCT(PRODUCT_ID),
    SKU_LINK_ID                             VARCHAR2(40)        NOT NULL REFERENCES DCS_SKU_LINK(SKU_LINK_ID),
    PRIMARY KEY (GROUPED_PRODUCT_ID, SKU_LINK_ID));