ALTER TABLE CASTO_CATEGORY DROP COLUMN IK_CATEGORY_TYPE;
ALTER TABLE CASTO_CATEGORY DROP COLUMN IK_CATEGORY_TYPE_NAV;
ALTER TABLE CASTO_SKU_CROSS_SELLING_ASSOC DROP COLUMN IK_CROSS_ID;
DROP TABLE CASTO_IK_CATEGORY_TYPE;
commit;