
ALTER TABLE CASTO_ABONNEMENT_NEWSLETTER DROP COLUMN DATE_UNSUBSCRIBE;
ALTER TABLE CASTO_ABONNEMENT_NEWSLETTER DROP COLUMN DATE_OFFERS_UNSUBSCRIBE;

ALTER TABLE CASTO_ABONNEMENT_NEWSLETTER ADD DATE_OFFERS_DESINCRPTION DATE;


ALTER TABLE CASTO_REFEREE ADD REF_COUPON_ID VARCHAR2(40) NULL;


CREATE TABLE "CASTO_LOGS_ADMIN" 
(	
	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(254 BYTE), 
	"DATECREATION" DATE, 
	"NOMLOGIN" VARCHAR2(50 BYTE), 
	"ADRESSEIP" VARCHAR2(40 BYTE), 
	"ACTION" VARCHAR2(254 BYTE), 
	"COMMENTAIRE" VARCHAR2(4000 BYTE), 
	 PRIMARY KEY ("ID")
);


CREATE TABLE CASTO_ORDER_EMAILS (
	ORDER_ID VARCHAR2 (40) NOT NULL REFERENCES CASTO_ORDER(ORDER_ID),
	EMAIL_TYPE VARCHAR2 (50),
	IS_SENT NUMBER (1,0),
	PRIMARY KEY (ORDER_ID, EMAIL_TYPE) 
);



ALTER TABLE CASTO_USER ADD PASSWORD_HASHED NUMBER (1,0) DEFAULT 1;
ALTER TABLE CASTO_USER ADD
(
  CONSTRAINT CASTO_USER_PASSWORD_HASHED
  CHECK
  (
    PASSWORD_HASHED in (0,1)
  )
  NOT DEFERRABLE INITIALLY IMMEDIATE
  ENABLE
);


INSERT INTO CASTO_CODES_POSTAUX (REPOSITORYID, CODE_POSTAL, VILLE) VALUES ('36686', '98000', 'MONACO');
INSERT INTO CASTO_CODES_POSTAUX (REPOSITORYID, CODE_POSTAL, VILLE) VALUES ('36687', '20000', 'CORSE');
commit;