ALTER TABLE CASTO_SKU ADD (
	COLOR_LIBELLE_CONTENU VARCHAR2(2000 BYTE),
	COLOR_LIBELLE_COMMERCE VARCHAR2(2000 BYTE),
	PROMOTION_COMMERCE CLOB,
	PROMOTION_CONTENU CLOB,
	START_PROM_COMMERCE DATE,
	END_PROM_COMMERCE DATE,
	START_PROM_CONTENU DATE,
	END_PROM_CONTENU DATE,
	SOUMISAREP NUMBER(1, 0) NULL,
	TAXREP NUMBER(14, 2) NULL
);

commit;
