INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('24',	1,	2,	4.5,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('1',	0,	1,	0,	3.5,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('2',	2,	5,	3.1,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('3',	5,	10,	2,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('4',	10,	20,	1.4,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('5',	20,	30,	1,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('6',	30,	50,	1,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('7',	50,	100,	0.7,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('8',	100,	350,	0.6,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('9',	350,	2147483,0.55,	0,	0,	'1');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('10',	0,	2,	0,	6.5,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('11',	2,	5,	2.75,	0,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('12',	5,	10,	2,	0,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('13',	10,	20,	1.8,	0,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('14',	20,	30,	1.6,	0,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('15',	30,	40,	0,	110,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('16',	40,	50,	0,	125,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('17',	50,	60,	0,	135,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('18',	60,	70,	0,	150,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('19',	70,	80,	0,	160,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('20',	80,	90,	0,	175,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('21',	90,	100,	0,	185,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('22',	100,	350,	1.9,	0,	0,	'2');

INSERT INTO CASTO_PFE_POIDS 
(ID, POIDS_INF, POIDS_SUP, PRIX_AU_KG, FORFAIT_TTC, FORFAIT_HN_TTC, GRILLE_PFE_ID)
VALUES 
('23',	350,	2147483,1.41,	0,	0,	'2');

COMMIT;
