CREATE INDEX CAST_CATALOGUE_WSX ON CAST_CATALOGUE (WORKSPACE_ID);
CREATE INDEX CAST_CATALOGUE_CIX ON CAST_CATALOGUE (CHECKIN_DATE);

CREATE INDEX CAST_DOCUMENT_WSX ON CAST_DOCUMENT (WORKSPACE_ID);
CREATE INDEX CAST_DOCUMENT_CIX ON CAST_DOCUMENT (CHECKIN_DATE);

CREATE INDEX CASTO_ACTUALITE_WSX ON CASTO_ACTUALITE (WORKSPACE_ID);
CREATE INDEX CASTO_ACTUALITE_CIX ON CASTO_ACTUALITE (CHECKIN_DATE);

CREATE INDEX CASTO_ADRESSE_WSX ON CASTO_ADRESSE (WORKSPACE_ID);
CREATE INDEX CASTO_ADRESSE_CIX ON CASTO_ADRESSE (CHECKIN_DATE);

CREATE INDEX CASTO_COMMANDE_SERVICE_WSX ON CASTO_COMMANDE_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_COMMANDE_SERVICE_CIX ON CASTO_COMMANDE_SERVICE (CHECKIN_DATE);

CREATE INDEX CASTO_DEPARTEMENT_WSX ON CASTO_DEPARTEMENT (WORKSPACE_ID);
CREATE INDEX CASTO_DEPARTEMENT_CIX ON CASTO_DEPARTEMENT (CHECKIN_DATE);

CREATE INDEX CASTO_ENTITE_WSX ON CASTO_ENTITE (WORKSPACE_ID);
CREATE INDEX CASTO_ENTITE_CIX ON CASTO_ENTITE (CHECKIN_DATE);

CREATE INDEX CASTO_GESTPROMO_ACTIONCO_WSX ON CASTO_GESTPROMO_ACTIONCO (WORKSPACE_ID);
CREATE INDEX CASTO_GESTPROMO_ACTIONCO_CIX ON CASTO_GESTPROMO_ACTIONCO (CHECKIN_DATE);

CREATE INDEX CASTO_IMAGE_AUX_WSX ON CASTO_IMAGE_AUX (WORKSPACE_ID);
CREATE INDEX CASTO_IMAGE_AUX_CIX ON CASTO_IMAGE_AUX (CHECKIN_DATE);

CREATE INDEX CASTO_LEGACY_URL_WSX ON CASTO_LEGACY_URL (WORKSPACE_ID);
CREATE INDEX CASTO_LEGACY_URL_CIX ON CASTO_LEGACY_URL (CHECKIN_DATE);

CREATE INDEX CASTO_MAGAS_COUPLE_SERVICE_WSX ON CASTO_MAGAS_COUPLE_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_MAGAS_COUPLE_SERVICE_CIX ON CASTO_MAGAS_COUPLE_SERVICE (CHECKIN_DATE);

CREATE INDEX CASTO_MAGASIN_WSX ON CASTO_MAGASIN (WORKSPACE_ID);
CREATE INDEX CASTO_MAGASIN_CIX ON CASTO_MAGASIN (CHECKIN_DATE);

CREATE INDEX CASTO_MESSAGES_WSX ON CASTO_MESSAGES (WORKSPACE_ID);
CREATE INDEX CASTO_MESSAGES_CIX ON CASTO_MESSAGES (CHECKIN_DATE);

CREATE INDEX CASTO_OFFRE_WSX ON CASTO_OFFRE (WORKSPACE_ID);
CREATE INDEX CASTO_OFFRE_CIX ON CASTO_OFFRE (CHECKIN_DATE);

CREATE INDEX CASTO_OPERATION_SPECIALE_WSX ON CASTO_OPERATION_SPECIALE (WORKSPACE_ID);
CREATE INDEX CASTO_OPERATION_SPECIALE_CIX ON CASTO_OPERATION_SPECIALE (CHECKIN_DATE);

CREATE INDEX CASTO_OUVERTURE_EXCEP_WSX ON CASTO_OUVERTURE_EXCEP (WORKSPACE_ID);
CREATE INDEX CASTO_OUVERTURE_EXCEP_CIX ON CASTO_OUVERTURE_EXCEP (CHECKIN_DATE);

CREATE INDEX CASTO_REGION_WSX ON CASTO_REGION (WORKSPACE_ID);
CREATE INDEX CASTO_REGION_CIX ON CASTO_REGION (CHECKIN_DATE);

CREATE INDEX CASTO_SERVICE_WSX ON CASTO_SERVICE (WORKSPACE_ID);
CREATE INDEX CASTO_SERVICE_CIX ON CASTO_SERVICE (CHECKIN_DATE);

CREATE INDEX CASTO_STAGE_WSX ON CASTO_STAGE (WORKSPACE_ID);
CREATE INDEX CASTO_STAGE_CIX ON CASTO_STAGE (CHECKIN_DATE);

ALTER TABLE CAST_PROMO_INFORMATION MODIFY TITLE VARCHAR2 (200);
ALTER TABLE CAST_PROMO_INFORMATION MODIFY DESCRIPTION VARCHAR2 (500);