ALTER TABLE CASTO_SKU DROP (
	COLOR_LIBELLE_CONTENU,
	COLOR_LIBELLE_COMMERCE, 
	PROMOTION_COMMERCE,
	PROMOTION_CONTENU,
	START_PROM_COMMERCE,
	END_PROM_COMMERCE,
	START_PROM_CONTENU,
	END_PROM_CONTENU
	SOUMISAREP,
	TAXREP
) ;

commit;
